src/objects/Accounting_Invoice__c.object
<CustomObject>
    <description>For Commcare Integration</description>
    <label>Accounting</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Accounting #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accounting</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>accounting_subscriber_domain__c</fullName>
        <formula>IF(Text(Invoice_Type__c) = &apos;Subscription&apos;, 
Accounting_Subscription__r.Accounting_Subscriber__r.domain__c,
Project_Space__r.Name
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project Space</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Accounting_Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Accounting Subscription</label>
        <referenceTo>Accounting_Subscription__c</referenceTo>
        <relationshipName>Accounting_Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>date_created__c</fullName>
        <label>invoice_date_created</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Domain__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Domain</label>
        <referenceTo>Domain__c</referenceTo>
        <relationshipLabel>Accounting (Domain)</relationshipLabel>
        <relationshipName>Accounting1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>id__c</fullName>
        <externalId>true</externalId>
        <label>invoice_id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Space__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Space Link</label>
        <referenceTo>Domain__c</referenceTo>
        <relationshipLabel>Accounting</relationshipLabel>
        <relationshipName>Accounting</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Server_Name__c</fullName>
        <label>Server Name</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CommCareHQ</fullName>
                    <default>true</default>
                    <label>CommCareHQ</label>
                </value>
                <value>
                    <fullName>CommCareHQ India</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/objects/Accounting_Subscriber__c.object
<CustomObject>
    <label>Accounting_Subscriber</label>
    <nameField>
        <displayFormat>Subscriber-{00000}</displayFormat>
        <label>Subscriber#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accounting_Subscriber</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>domain_lookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>domain (lookup)</label>
        <referenceTo>Domain__c</referenceTo>
        <relationshipLabel>Accounting_Subscriber</relationshipLabel>
        <relationshipName>Accounting_Subscriber</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>domain__c</fullName>
        <label>domain</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>id__c</fullName>
        <externalId>true</externalId>
        <label>id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Server_Name__c</fullName>
        <label>Server Name</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CommCareHQ</fullName>
                    <default>true</default>
                    <label>CommCareHQ</label>
                </value>
                <value>
                    <fullName>CommCareHQ India</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/objects/Accounting_Subscription__c.object
<CustomObject>
    <fields>
        <fullName>Accounting_Subscriber__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Accounting_Subscriber</label>
        <referenceTo>Accounting_Subscriber__c</referenceTo>
        <relationshipLabel>Accounting Subscriptions</relationshipLabel>
        <relationshipName>Accounting_Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Accounting_subscriber_domain__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Domain</label>
        <referenceTo>Domain__c</referenceTo>
        <relationshipLabel>Accounting Subscriptions</relationshipLabel>
        <relationshipName>Accounting_Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Server_Name__c</fullName>
        <label>Server Name</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CommCareHQ</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>CommCareHQ India</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>account</label>
        <referenceTo>Accounting_BillingAccount__c</referenceTo>
        <relationshipLabel>Accounting Subscriptions</relationshipLabel>
        <relationshipName>Accounting_Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>date_created__c</fullName>
        <label>date_created</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>id__c</fullName>
        <externalId>true</externalId>
        <label>id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Accounting Subscription</label>
    <nameField>
        <displayFormat>AS-{00000}</displayFormat>
        <label>Accounting Subscription Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accounting Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BatchDefaultSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Batch Default Settings</label>
    <fields>
        <fullName>Error_Emails__c</fullName>
        <label>Error Emails</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Contract_Domain__c.object
<CustomObject>
    <label>Contract Domain</label>
    <nameField>
        <displayFormat>CD-{000000}</displayFormat>
        <label>Contract Domain Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Domains</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Domain__c</fullName>
        <label>Domain</label>
        <referenceTo>Domain__c</referenceTo>
        <relationshipLabel>Contract Domains</relationshipLabel>
        <relationshipName>Contract_Domains</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

src/objects/Domain__c.object
<CustomObject>
    <description>CommCare Integration</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SF Account (Organization)</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Domain</relationshipLabel>
        <relationshipName>Domain</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country_of_deployment_salesforce__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the lookup for Country in Salesforce, not CommCareHQ</description>
        <label>Country of deployment (salesforce)</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Domain</relationshipLabel>
        <relationshipName>Domain</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Domain_Deleted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If set to true it means that domain was marked as deleted in HQ. Do not update this field manually, it&apos;s automatically set by apex code.</description>
        <inlineHelpText>If set to true it means that domain was marked as deleted in HQ. Do not update this field manually, it&apos;s automatically set by apex code.</inlineHelpText>
        <label>Domain Deleted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Domain</relationshipLabel>
        <relationshipName>Domain</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Domain</relationshipLabel>
        <relationshipName>Domain</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Domain</relationshipLabel>
        <relationshipName>Domain</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Server_Name__c</fullName>
        <label>Server Name</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CommCareHQ</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>CommCareHQ India</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>date_created__c</fullName>
        <label>Domain_date_created</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>id__c</fullName>
        <externalId>true</externalId>
        <label>Domain_id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Domain</label>
    <nameField>
        <label>Domain Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Domain</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Domain_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>looks up the project space name from the Domain object</description>
        <inlineHelpText>DO NOT USE (CJ/AS TEST)</inlineHelpText>
        <label>Domain Name</label>
        <referenceTo>Domain__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <description>Used by snapshots to prepopulate fields.</description>
        <inlineHelpText>Used by snapshots to prepopulate fields.</inlineHelpText>
        <label>Snapshot Source Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Opportunity</fullName>
                    <default>true</default>
                    <label>Opportunity</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/classes/DomainDeactivationBatch.cls
public class DomainDeactivationBatch  implements Database.Batchable<DuplicateDomainWrapper>, Database.AllowsCallouts {

    public DomainDeactivationBatch() {}

    public List<DuplicateDomainWrapper> start(Database.BatchableContext context) {
        List<DuplicateDomainWrapper> result = new List<DuplicateDomainWrapper>();
        for (AggregateResult aggRes : [SELECT Server_Name__c, Name, Count(Id) FROM Domain__c WHERE Domain_Deleted__c = false GROUP BY Server_Name__c, Name HAVING Count(Id) > 1]) {
            String domainName = (String) aggRes.get('Name');
            String serverName = (String) aggRes.get('Server_Name__c');

            System.debug('Duplicate data : ' + domainName + ' - ' + serverName);
            result.add(new DuplicateDomainWrapper(domainName, serverName));
        }
        return result;
    }

    public void execute(Database.BatchableContext context, List<DuplicateDomainWrapper> scope) {
        List<Exception> errors = new List<Exception>();
        for (DuplicateDomainWrapper domainWrapper : scope) { // Additional loop to avoid "Uncomitted work pending"
            try {
                domainWrapper.realDomainId = HQSyncUtils.getRealDomainId(domainWrapper.domainName, domainWrapper.serverName);
            } catch (Exception e) {
                errors.add(e);
                System.debug('API Error : ' + e.getMessage());
                System.debug('API Error : ' + e.getCause());
                System.debug('API Error : ' + e.getLineNumber());
                System.debug('API Error : ' + e.getStackTraceString());
                System.debug('API Error : ' + e.getTypeName());
                continue;
            }
        }

        for (Exception e : errors) { // Additional loop to avoid "Uncomitted work pending"
            StatusLoggerUtils.logError(StatusLoggerUtils.HQ_SYNC_DUPLICATES_LOGGER, 'Cannot fetch duplicated domain data form HQ', 0, e.getMessage());
        }

        for (DuplicateDomainWrapper domainWrapper : scope) {
            String hqId = domainWrapper.realDomainId;

            if (hqId == null || hqId == '') {
                System.debug('Empty domain id : ' + domainWrapper.domainName + ' - ' + domainWrapper.serverName);
                StatusLoggerUtils.logError(StatusLoggerUtils.HQ_SYNC_DUPLICATES_LOGGER, 'Cannot fetch duplicated domain data form HQ', 0, 'API error ' + domainWrapper.domainName + ' - ' + domainWrapper.serverName);
                continue;
            }

            List<Domain__c> duplicates = [SELECT Id, id__c, Name, Domain_Deleted__c, date_created__c, Opportunity__c, Account__c, Lead__c, Primary_Contact__c, Country_of_deployment_salesforce__c FROM Domain__c
                                          WHERE Server_Name__c =: domainWrapper.serverName AND Name =: domainWrapper.domainName AND Domain_Deleted__c = false
                                          ORDER BY date_created__c];
            if (duplicates.size() < 1) { // no duplicates
                System.debug('No duplicated domains');
                continue;
            }

            Id oppId;
            Id leadId;
            Id accountId;
            Id contactId;
            Id deployId;

            Set<Id> opportunityMapping = new Set<Id>();
            Domain__c realDomain;
            for (Domain__c duplicate : duplicates) {
                if (duplicate.id__c == hqId) {
                    realDomain = duplicate;
                }
            }

            if (realDomain == null) {
                StatusLoggerUtils.logError(StatusLoggerUtils.HQ_SYNC_DUPLICATES_LOGGER, 'Cannot find real domain in DB', 0, 'Cannot find record');
                continue;
            }
            oppId = realDomain.Opportunity__c;
            leadId = realDomain.Lead__c;
            accountId = realDomain.Account__c;
            deployId = realDomain.Country_of_deployment_salesforce__c;
            contactId = realDomain.Primary_Contact__c;

            for (Domain__c duplicate : duplicates) {
                duplicate.Domain_Deleted__c = true;

                if (oppId == null && duplicate.Opportunity__c != null) {
                    oppId = duplicate.Opportunity__c;
                    opportunityMapping.add(oppId);
                }
                if (leadId == null && duplicate.Lead__c != null) { // test converted leads in unit tests
                    leadId = duplicate.Lead__c;
                }
                if (accountId == null && duplicate.Account__c != null) {
                    accountId = duplicate.Account__c;
                }
                if (contactId == null && duplicate.Primary_Contact__c != null) {
                    contactId = duplicate.Primary_Contact__c;
                }
                if (deployId == null && duplicate.Country_of_deployment_salesforce__c != null) {
                    deployId = duplicate.Country_of_deployment_salesforce__c;
                }
            }

            realDomain.Domain_Deleted__c = false;
            realDomain.Opportunity__c = oppId;
            realDomain.Lead__c = leadId;
            realDomain.Account__c = accountId;
            realDomain.Primary_Contact__c = contactId;
            realDomain.Country_of_deployment_salesforce__c = deployId;

            List<Opportunity> opps = new List<Opportunity>();
            for (Id oppIdFor : opportunityMapping) {
                opps.add(new Opportunity(Id = oppIdFor, Domain_Name__c = realDomain.Id));
            }

            List<Contract_Domain__c> contractDomains = [SELECT Id, Domain__c FROM Contract_Domain__c WHERE Domain__c IN: duplicates];
            for (Contract_Domain__c contractDomain : contractDomains) {
                contractDomain.Domain__c = realDomain.Id;
            }

            List<Accounting_Invoice__c> invoices = [SELECT Id, Project_Space__c FROM Accounting_Invoice__c WHERE Project_Space__c IN: duplicates];
            for (Accounting_Invoice__c invoice : invoices) {
                invoice.Project_Space__c = realDomain.Id;
            }

            List<Accounting_Subscriber__c> subscribers = [SELECT Id, domain_lookup__c FROM Accounting_Subscriber__c WHERE domain_lookup__c IN: duplicates];
            for (Accounting_Subscriber__c sub : subscribers) {
                sub.domain_lookup__c = realDomain.Id;
            }

            List<Accounting_Subscription__c> subscriptions = [SELECT Id, Accounting_subscriber_domain__c FROM Accounting_Subscription__c WHERE Accounting_subscriber_domain__c IN: duplicates];
            for (Accounting_Subscription__c sub : subscriptions) {
                sub.Accounting_subscriber_domain__c = realDomain.Id;
            }

            Savepoint sp = Database.setSavepoint();
            try {
                update duplicates;
                if (opps.size() > 0) {
                    update opps;
                }
                if (contractDomains.size() > 0) {
                    update contractDomains;
                }
                if (invoices.size() > 0) {
                    update invoices;
                }
                if (subscribers.size() > 0) {
                    update subscribers;
                }
                if (subscriptions.size() > 0) {
                    update subscriptions;
                }
            } catch (DMLException e) {
                StatusLoggerUtils.logError(StatusLoggerUtils.HQ_SYNC_DUPLICATES_LOGGER, 'Cannot update duplicated domains', 0, e.getMessage());
                Database.rollback(sp);
            }
        }
    }

    public void finish(Database.BatchableContext context) {
        if (!Test.isRunningTest()) {
            StatusLoggerUtils.sendLog(StatusLoggerUtils.HQ_SYNC_DUPLICATES_LOGGER,  BatchDefaultSettings__c.getOrgDefaults().Error_Emails__c.split(','));
        }
    }

    public class DuplicateDomainWrapper {

        public String domainName { get; set; }
        public String serverName { get; set; }
        public String realDomainId { get; set; }

        public DuplicateDomainWrapper(String domainName, String serverName) {
            this.domainName = domainName;
            this.serverName = serverName;
        }
    }
}