src/objects/Accounting_Subscriber__c.object
<CustomObject>
    <label>Accounting_Subscriber</label>
    <nameField>
        <displayFormat>Subscriber-{00000}</displayFormat>
        <label>Subscriber#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accounting_Subscriber</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>domain_lookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>domain (lookup)</label>
        <referenceTo>Domain__c</referenceTo>
        <relationshipLabel>Accounting_Subscriber</relationshipLabel>
        <relationshipName>Accounting_Subscriber</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>domain__c</fullName>
        <label>domain</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/DContract__c.object
<CustomObject>
    <description>Tracks all of Dimagi&apos;s Contracts</description>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Domain__c.object
<CustomObject>
    <description>CommCare Integration</description>
    <label>Domain</label>
    <nameField>
        <label>Domain Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Domain</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ContractDomainsRelatedListController.cls
public class ContractDomainsRelatedListController {

    public Accounting_Subscriber__c domainWrapper { get; set; }
    public DContract__c dContract { get; set; }

    public ContractDomainsRelatedListController() {
        String conId = ApexPages.currentPage().getParameters().get('contractId');
        if (conId != null) {
            this.dContract = [SELECT Id, Name FROM DContract__c WHERE Id =: conId LIMIT 1];
        }
        domainWrapper = new Accounting_Subscriber__c();
    }

    public PageReference save() {
        if (domainWrapper.domain_lookup__c == null) {
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR, 'Select domain to assign'));
            return null;
        }

        Domain__c selectedDomain = [SELECT Id, Name, Contract__c FROM Domain__c WHERE Id =: domainWrapper.domain_lookup__c];
        if (selectedDomain.Contract__c == dContract.Id) {
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR, 'Domain already connected with contract'));
            return null;
        }

        selectedDomain.Contract__c = dContract.Id;
        update selectedDomain;

        return new ApexPages.StandardController(dContract).view();
    }

    public PageReference cancel() {
        return new ApexPages.StandardController(dContract).view();
    }
}