src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Office_Type__c</fullName>
        <inlineHelpText>If this is a Headquarters account choose &quot;HQ&quot;. If it is a country-specific office choose &quot;Country Office&quot;.</inlineHelpText>
        <label>Office Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Country Office</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>HQ</fullName>
                </value>
                <value>
                    <fullName>Regional</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Validate = Need to contact; 
Connect = remind every 10 days; 
Active = an active opportunity; 
Passive = remind every 3 months.</inlineHelpText>
        <label>Status_old</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Validate</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Connect</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Passive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Country__c.object
<CustomObject>
    <description>The different countries we work in</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Location__c.object
<CustomObject>
    <description>Tracks where our projects are executed.  Countries, Regions, States, and Geopoint.</description>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <description>A Dimagi Project</description>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Implementing Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Implementing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The organization that is implementing the project.</inlineHelpText>
        <label>Implementing Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Space_Name__c</fullName>
        <inlineHelpText>The name of the Project Space in HQ</inlineHelpText>
        <label>HQ Project Space Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>&quot;Inactive&quot; means either not started or on hold. &quot;Complete&quot; means the project is closed.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Deployment</label>
    <nameField>
        <label>Deployment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deployments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project_Location__c.object
<CustomObject>
    <description>Joins Project, Opportunities, Contracts, and Locations</description>
    <label>Project Location</label>
    <nameField>
        <displayFormat>ProjLoc-{00000}</displayFormat>
        <label>Project Location Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Project Locations</relationshipLabel>
        <relationshipName>Project_Locations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Project_Locations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

src/classes/ProjectTriggerSyncTest.cls
@isTest
private class ProjectTriggerSyncTest {

    @isTest
    static void testProjectTriggerSyncFlow() {
        Country__c cntry = new Country__c(Name = 'Test');
        insert cntry;

        Account acct = new Account(Name='Test Account', Country__c = cntry.Id, Office_Type__c = 'HQ');
        insert acct;

        Project__c p = new Project__c(
            Name = 'Test',
            Project_Space_Name__c = 'Test',
            Status__c = 'Test',
            Implementing_Account__c = acct.Id
        );
        insert p;

        Country__c c = new Country__c(Name = 'United States');
        insert c; 

        Location__c l = new Location__c(Country__c = c.Id, Name = 'Los Angeles');
        insert l;

        Project_Location__c pl = new Project_Location__c(Project__c = p.Id, Location__c = l.Id);
        insert pl;

        Project_Location__c pl2 = new Project_Location__c(Project__c = p.Id, Location__c = l.Id);
        insert pl2;

        delete pl;

        p.Status__c = 'Complete';
        update p;
    }
}