src/objects/Accounting_BillingAccount__c.object
<CustomObject>
    <fields>
        <fullName>dimagi_contact__c</fullName>
        <label>Dimagi Contact</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Accounting BillingAccount</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounting BillingAccount</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Accounting_Subscription__c.object
<CustomObject>
    <fields>
        <fullName>Accounting_subscriber_domain__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Domain</label>
        <referenceTo>Domain__c</referenceTo>
        <relationshipLabel>Accounting Subscriptions</relationshipLabel>
        <relationshipName>Accounting_Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Dimagi_Contact__c</fullName>
        <formula>account__r.dimagi_contact__c</formula>
        <label>Dimagi Contact</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Software_Plan_Edition__c</fullName>
        <formula>plan_version__r.Accounting_SoftwarePlan__r.edition__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Software Plan Edition</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>account</label>
        <referenceTo>Accounting_BillingAccount__c</referenceTo>
        <relationshipLabel>Accounting Subscriptions</relationshipLabel>
        <relationshipName>Accounting_Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>accounting_software_monthly_fee__c</fullName>
        <formula>plan_version__r.Software_Product_Rate__r.monthly_fee__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Monthly fee</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>date_end__c</fullName>
        <label>date_end</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>do_not_invoice__c</fullName>
        <defaultValue>false</defaultValue>
        <label>do_not_invoice</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>service_type__c</fullName>
        <label>service_type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Accounting Subscription</label>
    <nameField>
        <displayFormat>AS-{00000}</displayFormat>
        <label>Accounting Subscription Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accounting Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BatchDefaultSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Batch Default Settings</label>
    <fields>
        <fullName>Error_Emails__c</fullName>
        <label>Error Emails</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Domain__c.object
<CustomObject>
    <description>CommCare Integration</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SF Account (Organization)</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Domain</relationshipLabel>
        <relationshipName>Domain</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Domain</relationshipLabel>
        <relationshipName>Domain</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>cpAllWebUsers__c</fullName>
        <label>Domain_cp_all_web_users</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Domain</label>
    <nameField>
        <label>Domain Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Domain</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Channel_Response__c</fullName>
        <description>What Channel is the Opportunity (Sales, B2B, Pre-Bid, Other Competitive Bid, etc.)? 
See https://confluence.dimagi.com/display/BD/BD+Channels</description>
        <inlineHelpText>What Channel is the Opportunity (Sales, B2B, Pre-Bid, Other Competitive Bid, etc.)? 
See https://confluence.dimagi.com/display/BD/BD+Channels</inlineHelpText>
        <label>Channel</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Inside Sales</fullName>
                </value>
                <value>
                    <fullName>B2B - Standard</fullName>
                </value>
                <value>
                    <fullName>B2B - Enterprise</fullName>
                </value>
                <value>
                    <fullName>Large Competitive Bid</fullName>
                </value>
                <value>
                    <fullName>Other Competitive Bid</fullName>
                </value>
                <value>
                    <fullName>NIH Prime Grant</fullName>
                </value>
                <value>
                    <fullName>CORE Funding (Gates)</fullName>
                </value>
                <value>
                    <fullName>Gates Enterprise</fullName>
                </value>
                <value>
                    <fullName>Chatbot</fullName>
                </value>
                <value>
                    <fullName>Always Exclude Reporting Only</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contract_Owner_BU__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Which Dimagi Subsidiary or registered Entity will sign the contract.</inlineHelpText>
        <label>Contract Owner (Entity)</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2 OR 3 OR 4 OR 5</booleanFilter>
            <filterItems>
                <field>Business_Unit__c.Name</field>
                <operation>equals</operation>
                <value>INC</value>
            </filterItems>
            <filterItems>
                <field>Business_Unit__c.Name</field>
                <operation>equals</operation>
                <value>DSA</value>
            </filterItems>
            <filterItems>
                <field>Business_Unit__c.Name</field>
                <operation>equals</operation>
                <value>DSI</value>
            </filterItems>
            <filterItems>
                <field>Business_Unit__c.Name</field>
                <operation>equals</operation>
                <value>DWA</value>
            </filterItems>
            <filterItems>
                <field>Business_Unit__c.Name</field>
                <operation>equals</operation>
                <value>Inc</value>
            </filterItems>
            <infoMessage>Only Inc, DSA, DSI, or (very infrequently DWA) can own a contract.</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Business_Unit__c</referenceTo>
        <relationshipLabel>Opportunities (Contract Owner)</relationshipLabel>
        <relationshipName>OpportunitiesContractOwner</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Domain_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>looks up the project space name from the Domain object</description>
        <inlineHelpText>DO NOT USE (CJ/AS TEST)</inlineHelpText>
        <label>Domain Name</label>
        <referenceTo>Domain__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Duration_months__c</fullName>
        <inlineHelpText>How long would this contract be spread over if we win?</inlineHelpText>
        <label>Duration (months)</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Expected_Buffer__c</fullName>
        <description>Percent of the Total Contract minus Expenses that will not be directly allocated via Fogbugz or Intacct data, and is expected to fund other core activities.</description>
        <inlineHelpText>Percent of the Total Contract minus Expenses that will not be directly allocated via Fogbugz or Intacct data, and is expected to fund other core activities.</inlineHelpText>
        <label>Expected Buffer (%)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Implementation_Type__c</fullName>
        <label>Implementation Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Bundles and Services</fullName>
                </value>
                <value>
                    <fullName>Enterprise</fullName>
                </value>
                <value>
                    <fullName>Self Service</fullName>
                </value>
                <value>
                    <fullName>Managed server</fullName>
                </value>
                <value>
                    <fullName>EMM</fullName>
                </value>
                <value>
                    <fullName>Chatbot</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Implementing_Business_Unit__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>The Dimagi BU that will manage the execution of the project.</inlineHelpText>
        <label>Execution Owner (BU)</label>
        <referenceTo>Business_Unit__c</referenceTo>
        <relationshipLabel>Opportunities (Execution)</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>of_Execution_budget_for_GS__c</fullName>
        <defaultValue>1</defaultValue>
        <description>This is the % of the remaining budget (after removing expenses and buffer %) that is planned for GS work</description>
        <inlineHelpText>This is the % of the remaining budget (after removing expenses and buffer %) that is planned for GS work</inlineHelpText>
        <label>% of Services budget for GS</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Opportunity_Owning_Entity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Which busniness unit owns this opportunity.</inlineHelpText>
        <label>Opportunity Owner (BU)</label>
        <referenceTo>Business_Unit__c</referenceTo>
        <relationshipLabel>Opportunities (Owning)</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <description>Used by snapshots to prepopulate fields.</description>
        <inlineHelpText>Used by snapshots to prepopulate fields.</inlineHelpText>
        <label>Snapshot Source Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Opportunity</fullName>
                    <default>true</default>
                    <label>Opportunity</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Prior_Dimagi_contact__c</fullName>
        <label>Prior Dimagi contact</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subscriptions_web_users__c</fullName>
        <label>Subscriptions web users</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

src/objects/Subscription_Renewal_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Default_Business_Unit__c</fullName>
        <label>Default Business Unit</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Error_Emails__c</fullName>
        <label>Error Emails</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Subscription Renewal Settings</label>
</CustomObject>

src/classes/RenewalSubscriptionsBatch.cls
/**
 * RenewalSubscriptionsBatch creates new Opps for ending Domain Subscriptions.
 */
public without sharing class RenewalSubscriptionsBatch implements Database.Batchable<Accounting_Subscription__c>, Database.AllowsCallouts, Database.Stateful {

    private static final String IMPL_RENEWAL = 'Implementation Renewal';
    private static final String PROD_RENEWAL = 'Product Renewal';

    private Integer recordCounter;
    private Date currentDate;
    private Business_Unit__c incBusinessUnit;
    private User implementationNonEnterpriseOwner;
    private User implementationEnterpriseOwner;
    private User productNonEnterpriseOwner;
    private User productEnterpriseOwner;
    private Subscription_Renewal_Settings__c settings;

    private Map<String, PricebookEntry> priceBookEntries;
    private PricebookEntry commCareEntry;
    // Grouping by billing account has to see every eligible subscription at once - a group
    // can span more than one execute() chunk (RenewalSubscriptionsScheduler uses a scope of
    // 10), and chunk order isn't guaranteed either. start() is the only place that sees the
    // whole candidate set in one call, so grouping and representative selection happen there;
    // only one already-validated representative per group is returned, to be chunked (and
    // its DML bounded) by Batch Apex as usual. The rest of each group's domain Ids are kept
    // here for execute() to stamp alongside the representative's own domain.
    private Map<Id, Set<Id>> domainIdsByGroup;

    public RenewalSubscriptionsBatch () {
        this(Date.today());
    }

    public RenewalSubscriptionsBatch (Date currentDate) {
        this.currentDate = currentDate;
        this.recordCounter = 0;
    }

    public List<Accounting_Subscription__c> start(Database.BatchableContext context) {
        List<Accounting_Subscription__c> subscriptions = getFutureSubscriptions();
        this.settings = Subscription_Renewal_Settings__c.getOrgDefaults();

        this.incBusinessUnit = [SELECT Id FROM Business_Unit__c WHERE Name =: settings.Default_Business_Unit__c];
        this.implementationNonEnterpriseOwner = [SELECT Id FROM User WHERE Name =: settings.Implementation_non_Enterprise_Owner__c];
        this.implementationEnterpriseOwner = [SELECT Id FROM User WHERE Name =: settings.Implementation_Enterprise_Owner__c];
        this.productNonEnterpriseOwner = [SELECT Id FROM User WHERE Name =: settings.Product_non_Enterprise_Owner__c];
        this.productEnterpriseOwner = [SELECT Id FROM User WHERE Name =: settings.Product_Enterprise_Owner__c];

        if (this.incBusinessUnit == null || this.implementationNonEnterpriseOwner == null || this.implementationEnterpriseOwner == null
                || this.productNonEnterpriseOwner == null || this.productEnterpriseOwner == null) {
            EmailHelper.sendEmail(settings.Error_Emails__c.split(','), 'Subscription Renewal ERROR',
                                  'Cannot find default Opportunity owner or Inc business unit');
            NoDataFoundException ex = new NoDataFoundException();
            ex.setMessage('Cannot find default Opportunity owner or INC business unit');
            throw ex;
        }

        Set<String> domainsWithFutureSubscriptions = new Set<String>();
        for (Accounting_Subscription__c sb : subscriptions) {
            if (!domainsWithFutureSubscriptions.contains(sb.Accounting_subscriber_domain__r.Name)) {
                domainsWithFutureSubscriptions.add(sb.Accounting_subscriber_domain__r.Name);
            }
        }

        this.priceBookEntries = new Map<String, PricebookEntry>();

        Set<String> productCodes = new Set<String> { 'Reseller', 'Managed Hosting', 'Advanced', 'Community', 'Enterprise', 'Pro', 'Standard' };
        PriceBook2 dimagiPriceBook = [SELECT Id FROM PriceBook2 WHERE Name = 'Dimagi'];
        List<PricebookEntry> entries = [SELECT Id, ProductCode, UnitPrice FROM PricebookEntry WHERE ProductCode IN: ProductCodes AND Pricebook2Id =: dimagiPriceBook.Id];

        for (PricebookEntry entry : entries) {
            this.priceBookEntries.put(entry.ProductCode, entry);
        }

        this.commCareEntry = [SELECT Id, ProductCode, UnitPrice FROM PricebookEntry WHERE ProductCode = 'CommCare' AND Pricebook2Id =: dimagiPriceBook.Id LIMIT 1];

        if (entries.size() != 7 || this.commCareEntry == null) {
            NoDataFoundException ex = new NoDataFoundException();
            ex.setMessage('Cannot find price book entries');
            throw ex;
        }

        return selectRepresentativesForRenewal(getSubscriptionsForRenewal(domainsWithFutureSubscriptions));
    }

    /**
     * Groups the full candidate set by billing account (Account__c, falling back to the
     * domain when there isn't one), picks one renewable representative subscription per
     * group, and records the rest of each group's domain Ids in domainIdsByGroup for
     * execute() to stamp later. Only ever called once, from start(), which is the only place
     * that sees every candidate for this run at the same time.
     */
    private List<Accounting_Subscription__c> selectRepresentativesForRenewal(List<Accounting_Subscription__c> allCandidates) {
        Map<Id, List<Accounting_Subscription__c>> subscriptionsByGroup = new Map<Id, List<Accounting_Subscription__c>>();
        for (Accounting_Subscription__c subscription : allCandidates) {
            Id groupKey = subscription.Account__c != null ? subscription.Account__c : subscription.Accounting_subscriber_domain__c;
            if (!subscriptionsByGroup.containsKey(groupKey)) {
                subscriptionsByGroup.put(groupKey, new List<Accounting_Subscription__c>());
            }
            subscriptionsByGroup.get(groupKey).add(subscription);
        }

        this.domainIdsByGroup = new Map<Id, Set<Id>>();
        List<Accounting_Subscription__c> representatives = new List<Accounting_Subscription__c>();

        for (Id groupKey : subscriptionsByGroup.keySet()) {
            List<Accounting_Subscription__c> groupSubs = subscriptionsByGroup.get(groupKey);

            // Drop candidates whose domain already has an open (or very recently closed)
            // renewal Opportunity - that domain has already been handled. Domains that
            // don't still get a shared Opportunity, even if a sibling domain in the same
            // group already has one from a prior run.
            List<Accounting_Subscription__c> eligibleSubs = new List<Accounting_Subscription__c>();
            for (Accounting_Subscription__c s : groupSubs) {
                Boolean domainAlreadyHasOpp = s.Accounting_subscriber_domain__r.Opportunity__c != null &&
                     (s.Accounting_subscriber_domain__r.Opportunity__r.IsClosed == false ||
                       (s.Accounting_subscriber_domain__r.Opportunity__r.IsClosed == true && s.Accounting_subscriber_domain__r.Opportunity__r.CloseDate >= this.currentDate));
                if (!domainAlreadyHasOpp) {
                    eligibleSubs.add(s);
                }
            }
            if (eligibleSubs.isEmpty()) {
                continue;
            }

            // Prefer the subscription that's actually billed (do_not_invoice__c = false),
            // then the one ending latest ("only the latest subscription which will end"),
            // then Id - fully deterministic regardless of data order. Walk candidates in
            // that order and use the first one that's actually renewable, so one bad
            // candidate (unmatched service type, missing Pricebook entry) doesn't take the
            // whole group down with it.
            eligibleSubs.sort(new RepresentativeCandidateComparator());

            Accounting_Subscription__c representative = null;
            for (Accounting_Subscription__c candidate : eligibleSubs) {
                if (resolveRenewalDetails(candidate) != null) {
                    representative = candidate;
                    break;
                }
            }
            if (representative == null) {
                List<String> attemptedNames = new List<String>();
                for (Accounting_Subscription__c s : eligibleSubs) {
                    attemptedNames.add(s.Name + ' (' + s.service_type__c + '/' + s.Software_Plan_Edition__c + ')');
                }
                StatusLoggerUtils.logError(
                    StatusLoggerUtils.RENEWAL_LOGGER,
                    String.join(attemptedNames, ', '),
                    0,
                    'No candidate subscription in this group could be turned into a renewal Opportunity - unrecognized service type or missing Pricebook entry/price for every candidate tried'
                );
                continue; // nothing in this group could be turned into a valid Opportunity this run
            }

            Set<Id> domainIds = new Set<Id>();
            for (Accounting_Subscription__c s : eligibleSubs) {
                domainIds.add(s.Accounting_subscriber_domain__c);
            }
            this.domainIdsByGroup.put(groupKey, domainIds);
            representatives.add(representative);
        }

        return representatives;
    }

    /**
     * Orders a group's candidate subscriptions for representative selection: the one
     * actually billed (do_not_invoice__c = false) first, then the one ending latest, then
     * Id - so the choice is fully deterministic regardless of data order.
     */
    private class RepresentativeCandidateComparator implements Comparator<Accounting_Subscription__c> {
        public Integer compare(Accounting_Subscription__c a, Accounting_Subscription__c b) {
            Boolean aBilled = a.do_not_invoice__c == false;
            Boolean bBilled = b.do_not_invoice__c == false;
            if (aBilled != bBilled) {
                return aBilled ? -1 : 1;
            }
            if (a.date_end__c != b.date_end__c) {
                return a.date_end__c > b.date_end__c ? -1 : 1;
            }
            return a.Id < b.Id ? -1 : (a.Id > b.Id ? 1 : 0);
        }
    }

    private class RenewalDetails {
        String oppSource;
        Id ownerId;
        PricebookEntry pbe;
        Decimal price;
    }

    /**
     * Resolves the renewal owner/source and price for a candidate subscription, or null if
     * it isn't renewable (unrecognized service type, or no usable Pricebook entry/fee).
     * Pure - no SOQL, no logging, no state changes - so it's cheap to call speculatively
     * while walking candidates in start(), and to call again in execute() to get the actual
     * values for the one candidate that was chosen.
     */
    private RenewalDetails resolveRenewalDetails(Accounting_Subscription__c candidate) {
        String oppSource = '';
        Id ownerId = null;
        if (candidate.service_type__c == 'IMPLEMENTATION' && candidate.Software_Plan_Edition__c != 'Enterprise') {
            oppSource = IMPL_RENEWAL;
            ownerId = this.implementationNonEnterpriseOwner.Id;
        } else if (candidate.service_type__c == 'IMPLEMENTATION' && candidate.Software_Plan_Edition__c == 'Enterprise') {
            oppSource = IMPL_RENEWAL;
            ownerId = this.implementationEnterpriseOwner.Id;
        } else if ((candidate.service_type__c == 'PRODUCT' || candidate.service_type__c == 'TRIAL' || candidate.service_type__c == 'NOT_SET')
                        && candidate.Software_Plan_Edition__c != 'Enterprise') {
            oppSource = PROD_RENEWAL;
            ownerId = this.productNonEnterpriseOwner.Id;
        } else if ((candidate.service_type__c == 'PRODUCT' || candidate.service_type__c == 'TRIAL' || candidate.service_type__c == 'NOT_SET')
                        && candidate.Software_Plan_Edition__c == 'Enterprise') {
            oppSource = PROD_RENEWAL;
            ownerId = this.productEnterpriseOwner.Id;
        } else {
            return null; // service type isn't renewable
        }

        PricebookEntry pbe = this.priceBookEntries.get(candidate.Software_Plan_Edition__c);
        // SAL-515: price the renewal from the subscription's current monthly fee;
        // fall back to the Pricebook list price (no custom setting / hardcoded values).
        Decimal price = (candidate.accounting_software_monthly_fee__c != null && candidate.accounting_software_monthly_fee__c > 0)
                            ? candidate.accounting_software_monthly_fee__c
                            : (pbe != null ? pbe.UnitPrice : null);
        if (pbe == null || price == null) {
            return null; // no usable price
        }

        RenewalDetails details = new RenewalDetails();
        details.oppSource = oppSource;
        details.ownerId = ownerId;
        details.pbe = pbe;
        details.price = price;
        return details;
    }

    public void execute(Database.BatchableContext context, List<Accounting_Subscription__c> representatives) {
        Set<Id> domainsSet = new Set<Id>();
        for (Accounting_Subscription__c representative : representatives) {
            Set<Id> groupDomainIds = this.domainIdsByGroup.get(groupKeyFor(representative));
            if (groupDomainIds != null) {
                domainsSet.addAll(groupDomainIds);
            }
        }
        Map<Id, Domain__c> domains = new Map<Id, Domain__c> ([SELECT Id, Name, Opportunity__c FROM Domain__c WHERE Id IN: domainsSet]);

        String dateString = (this.currentDate.month() < 10 ? '0' + this.currentDate.month() : '' + this.currentDate.month())
                                + (this.currentDate.day() < 10 ? '0' + this.currentDate.day() : '' + this.currentDate.day())
                                + ('' + this.currentDate.year());

        for (Accounting_Subscription__c subscription : representatives) {
            RenewalDetails details = resolveRenewalDetails(subscription);
            if (details == null) {
                // Shouldn't happen - start() already confirmed this candidate resolves.
                StatusLoggerUtils.logError(StatusLoggerUtils.RENEWAL_LOGGER, subscription.Name, 0,
                    'Representative subscription no longer resolves to a renewal (service type or Pricebook entry changed since start())');
                continue;
            }

            String oppNameFirstPart = subscription.Accounting_subscriber_domain__r.Account__r.Name != null && subscription.Accounting_subscriber_domain__r.Account__r.Name != '' ?
                                        subscription.Accounting_subscriber_domain__r.Account__r.Name : subscription.Accounting_subscriber_domain__r.Name;

            String oppNamesecondPart = '-' + subscription.Software_Plan_Edition__c + (subscription.service_type__c == 'IMPLEMENTATION' ? '-Implementation' : '') + ' Renewal ' + dateString;

            if (oppNameFirstPart.length() + oppNamesecondPart.length() > 120) {
                oppNameFirstPart = oppNameFirstPart.subString(0, 120 - oppNamesecondPart.length());
            }

            Opportunity newOpp = new Opportunity(
                                                    Prior_Dimagi_contact__c = subscription.Dimagi_Contact__c,
                                                    Name = oppNameFirstPart + oppNamesecondPart,
                                                    Subscriptions_web_users__c = subscription.Accounting_subscriber_domain__r.cpAllWebUsers__c,
                                                    Probability = 30,
                                                    Duration_months__c = 12,
                                                    Expected_Buffer__c = 100,
                                                    of_Execution_budget_for_GS__c = 0,
                                                    CloseDate = subscription.date_end__c,
                                                    // Domain_Name__c, AccountId, Prior_Dimagi_contact__c and
                                                    // Subscriptions_web_users__c all take a single value and can
                                                    // only reflect the representative domain - the full set of
                                                    // domains this Opportunity covers is on Domain__c.Opportunity__c
                                                    // below.
                                                    Domain_Name__c = subscription.Accounting_subscriber_domain__c,
                                                    StageName = 'Stage 3 - Prospect',
                                                    OwnerId = details.ownerId,
                                                    Implementation_Type__c = 'Self Service',
                                                    Channel_Response__c = 'Inside Sales',
                                                    Opportunity_Owning_Entity__c = this.incBusinessUnit.Id,
                                                    Contract_Owner_BU__c = this.incBusinessUnit.Id,
                                                    Implementing_Business_Unit__c = this.incBusinessUnit.Id,
                                                    Opportunity_Source__c = details.oppSource,
                                                    Opportunity_Owner_Division__c = 'CommCare',
                                                    Opportunity_Owner_Sub_Division__c = 'CommCare Sales',
                                                    AccountId = subscription.Accounting_subscriber_domain__r.Account__r.id
                                                );

            // Stamp every domain in the group, not just the representative's - that's what
            // makes next week's run skip them.
            List<Domain__c> domainsToUpdate = new List<Domain__c>();
            Set<Id> groupDomainIds = this.domainIdsByGroup.get(groupKeyFor(subscription));
            if (groupDomainIds != null) {
                for (Id domainId : groupDomainIds) {
                    Domain__c domainToUpdate = domains.get(domainId);
                    if (domainToUpdate != null) {
                        domainsToUpdate.add(domainToUpdate);
                    }
                }
            }

            Savepoint sp = Database.setSavepoint();
            try {
                insert newOpp;
                for (Domain__c domainToUpdate : domainsToUpdate) {
                    domainToUpdate.Opportunity__c = newOpp.Id;
                }
                update domainsToUpdate;

                insert new OpportunityLineItem(PricebookEntryId = details.pbe.Id, Quantity = 12, UnitPrice = details.price, OpportunityId = newOpp.Id);
                // SAL-48 removing commcare: product pricebook entry
                // insert new OpportunityLineItem(PricebookEntryId = commCareEntry.Id, Quantity = 1, UnitPrice = commCareEntry.UnitPrice, OpportunityId = newOpp.Id);
                this.recordCounter++;
            } catch (DMLException e) {
                Database.rollback(sp);
                StatusLoggerUtils.logError(StatusLoggerUtils.RENEWAL_LOGGER, subscription.Accounting_subscriber_domain__r.Name + ' - ' + subscription.Name, 0, e.getMessage());
            }
        }
    }

    private Id groupKeyFor(Accounting_Subscription__c subscription) {
        return subscription.Account__c != null ? subscription.Account__c : subscription.Accounting_subscriber_domain__c;
    }

    public void finish(Database.BatchableContext context) {
        StatusLoggerUtils.logInfo(StatusLoggerUtils.RENEWAL_LOGGER, 'Renewal Script', this.recordCounter,
                                                    'Finished Renewal Job with date : ' + this.currentDate);
        if (Test.isRunningTest()) {
            return;
        }
        StatusLoggerUtils.sendLog(StatusLoggerUtils.RENEWAL_LOGGER, BatchDefaultSettings__c.getOrgDefaults().Error_Emails__c.split(','));
    }


    /**
     * Returns Subscriptions which ends after 60 days
     */
    public List<Accounting_Subscription__c> getFutureSubscriptions() {
        List<String> service_type = new List<String>();

for (Accounting_Subscription_service_type__mdt record : [SELECT service_types__c FROM Accounting_Subscription_service_type__mdt]) {
    String serviceType = record.service_types__c;
    service_type.add(serviceType);
}
        return [SELECT Id, date_start__c, date_end__c, Accounting_subscriber_domain__r.Name FROM Accounting_Subscription__c
                WHERE service_type__c NOT IN :service_type AND Accounting_subscriber_domain__r.Name != '' AND is_trial__c = false AND is_hidden_to_ops__c = false
                AND date_start__c >: this.currentDate
                AND (Server_Name__c = 'CommCareHQ' OR Server_Name__c = 'CommCareHQ India' OR Server_Name__c = 'CommCareHQ EU')];
    }


    /**
     * Returns Subscriptions which ends in 60 days for domains which dosen't contain subscriptions from future (which ends after 60 days).
     */
    public List<Accounting_Subscription__c> getSubscriptionsForRenewal(Set<String> domainsWithFutureSubscriptions) {
        List<String> service_type = new List<String>();

for (Accounting_Subscription_service_type__mdt record : [SELECT service_types__c FROM Accounting_Subscription_service_type__mdt]) {
    String serviceType = record.service_types__c;
    service_type.add(serviceType);
}
        return [SELECT Id, Name, date_start__c, date_end__c, service_type__c, Accounting_subscriber_domain__c, Accounting_subscriber_domain__r.Name, Dimagi_Contact__c, Accounting_subscriber_domain__r.Account__r.Name,
                Accounting_subscriber_domain__r.cpAllWebUsers__c, Software_Plan_Edition__c, accounting_software_monthly_fee__c,
                Accounting_subscriber_domain__r.Opportunity__r.CreatedDate, Accounting_subscriber_domain__r.Opportunity__c,
                Accounting_subscriber_domain__r.Opportunity__r.CloseDate, Accounting_subscriber_domain__r.Opportunity__r.IsClosed,
                Account__c, do_not_invoice__c
                FROM Accounting_Subscription__c
                WHERE service_type__c NOT IN :service_type AND Accounting_subscriber_domain__r.Name != '' AND date_end__c != null AND date_end__c <=: this.currentDate.addDays(90)
                AND date_end__c >=: this.currentDate AND Accounting_subscriber_domain__r.Name NOT IN: domainsWithFutureSubscriptions AND is_active__c = true
                AND is_hidden_to_ops__c = false AND is_trial__c = false AND (Server_Name__c = 'CommCareHQ' OR Server_Name__c = 'CommCareHQ India' OR Server_Name__c = 'CommCareHQ EU')];
                // No ORDER BY: representative selection sorts explicitly and doesn't depend
                // on query order.
    }
}