src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Business_Unit__c.object
<CustomObject>
    <description>The various Dimagi contracting entities.</description>
    <label>Business Unit</label>
    <nameField>
        <label>Business Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Country__c.object
<CustomObject>
    <description>The different countries we work in</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Amount_Minus_Expense_Income__c</fullName>
        <description>Total Amount of Agreement minus Pass Through Amount</description>
        <formula>Amount - Expense_Income__c -  Interdivision_Expense_Income__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Total Amount of Agreement minus Pass Through Amount</inlineHelpText>
        <label>Amount Minus Expense Income</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Business_Unit_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Who owns the Biz Dev process for this business unit.</inlineHelpText>
        <label>Business Unit Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>What country is this opportunity taking place.</inlineHelpText>
        <label>Implementing Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Duration_months__c</fullName>
        <inlineHelpText>How long would this contract be spread over if we win?</inlineHelpText>
        <label>Duration (months)</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Funder_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>The account that is supplying the money for the opportunity. i.e. USAID funds CARE who then pays us. USAID is the &quot;Funder Account&quot;, CARE is the &quot;Account&quot;.</inlineHelpText>
        <label>Funding Source</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities (Funding Source)</relationshipLabel>
        <relationshipName>Opportunities_Funded</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <description>Used by snapshots to prepopulate fields.</description>
        <inlineHelpText>Used by snapshots to prepopulate fields.</inlineHelpText>
        <label>Snapshot Source Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Opportunity</fullName>
                    <default>true</default>
                    <label>Opportunity</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/objects/Pipeline_Snapshot__c.object
<CustomObject>
    <description>Used to store historic pipeline information for pipeline reporting. Automatically populated each month.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Opportunity_Snapshots</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Amount_Minus_Expense_Income__c</fullName>
        <label>Amount Minus Expense Income</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <inlineHelpText>Amount at the time of the snapshot.

For Opportuity:  Amount = Opp Amount
For Closed Contract: Amount = Total Amount of Contract
For Outstanding Contract: Total Amount Remaining</inlineHelpText>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Duration_months__c</fullName>
        <inlineHelpText>The Duration at the time the snapshot was taken.

Opps: entered on opportunity manually
Contracts: End Date - Start Date</inlineHelpText>
        <label>Duration (months)</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Expected_Value_Minus_Expense__c</fullName>
        <formula>Amount_Minus_Expense_Income__c * Probability__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Expected Value Minus Expense</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Funder_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Funding Source</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Opportunity_Snapshots1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Month_Date__c</fullName>
        <inlineHelpText>The month of this snapshot.</inlineHelpText>
        <label>Month</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity_Amount_Minus_Expense_Income__c</fullName>
        <label>Opportunity Amount Minus Expense Income</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity_Amount__c</fullName>
        <label>Opportunity Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity_Name__c</fullName>
        <formula>Opportunity__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opportunity_Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Opportunity_Snapshots</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Probability__c</fullName>
        <inlineHelpText>The probability at the time the snapshot was taken.  (Contracts = 100%)</inlineHelpText>
        <label>Probability (%)</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>X12_Month_Cash_Minus_Expense_Income_EV__c</fullName>
        <formula>if(ispickval(Source_Type__c,&apos;Opportunity&apos;), 
IF( (MONTH(CloseDate__c ) + 12*YEAR(CloseDate__c)) &gt; (Month( Month_Date__c ) + 12*YEAR( Month_Date__c ) + 12) 
|| (BLANKVALUE(Duration_months__c,0) = 0) 
|| (CloseDate__c &lt; Month_Date__c), 
0, 
if( (12*YEAR(Month_Date__c)+ MONTH(Month_Date__c) + 12) &gt; (12*YEAR(CloseDate__c)+MONTH(CloseDate__c)+Duration_months__c),  Expected_Value_Minus_Expense__c , 
( Expected_Value_Minus_Expense__c  / Duration_months__c) * (MONTH( Month_Date__c) + 12*YEAR( Month_Date__c ) + 12 - MONTH(CloseDate__c) - 12*YEAR(CloseDate__c)))), 


if( (month(Contract_End_Date__c)+12*year(Contract_End_Date__c)) &lt; (month(Month_Date__c)+12*Year(Month_Date__c) + 13), 
 Amount_Minus_Expense_Income__c , 
(12 *  Amount_Minus_Expense_Income__c ) / 
( 
(month(Contract_End_Date__c) + 12*year(Contract_End_Date__c)) - (month(Month_Date__c) + 12*year(Month_Date__c)))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>12 Month Cash Minus Expense Income (EV)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>X18_Month_Cash_Minus_Expenses_Income_EV__c</fullName>
        <formula>if(ispickval(Source_Type__c,&apos;Opportunity&apos;), 
IF( (MONTH(CloseDate__c ) + 12*YEAR(CloseDate__c)) &gt; (Month( Month_Date__c ) + 12*YEAR( Month_Date__c ) + 18) 
|| (BLANKVALUE(Duration_months__c,0) = 0) 
|| (CloseDate__c &lt; Month_Date__c), 
0, 
if( (12*YEAR(Month_Date__c)+ MONTH(Month_Date__c) + 18) &gt; (12*YEAR(CloseDate__c)+MONTH(CloseDate__c)+Duration_months__c), 
Expected_Value_Minus_Expense__c , 
( Expected_Value_Minus_Expense__c / Duration_months__c) * (MONTH( Month_Date__c) + 12*YEAR( Month_Date__c ) + 18 - MONTH(CloseDate__c) - 12*YEAR(CloseDate__c)))), 


if( (month(Contract_End_Date__c)+12*year(Contract_End_Date__c)) &lt; (month(Month_Date__c)+12*Year(Month_Date__c) + 19), 
Amount_Minus_Expense_Income__c , 
(18 * Amount_Minus_Expense_Income__c ) / 
( 
(month(Contract_End_Date__c) + 12*year(Contract_End_Date__c)) - (month(Month_Date__c) + 12*year(Month_Date__c)))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>18 Month Cash Minus Expenses Income (EV)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>X24_Month_Cash_Minus_Expense_Income_EV__c</fullName>
        <formula>if(ispickval(Source_Type__c,&apos;Opportunity&apos;), 
IF( (MONTH(CloseDate__c ) + 12*YEAR(CloseDate__c)) &gt; (Month( Month_Date__c ) + 12*YEAR( Month_Date__c ) + 24) 
|| (BLANKVALUE(Duration_months__c,0) = 0) 
|| (CloseDate__c &lt; Month_Date__c), 
0, 
if( (12*YEAR(Month_Date__c)+ MONTH(Month_Date__c) + 24) &gt; (12*YEAR(CloseDate__c)+MONTH(CloseDate__c)+Duration_months__c), 
Expected_Value_Minus_Expense__c , 
( Expected_Value_Minus_Expense__c / Duration_months__c) * (MONTH( Month_Date__c) + 12*YEAR( Month_Date__c ) + 24 - MONTH(CloseDate__c) - 12*YEAR(CloseDate__c)))), 


if( (month(Contract_End_Date__c)+12*year(Contract_End_Date__c)) &lt; (month(Month_Date__c)+12*Year(Month_Date__c) + 25), 
Amount_Minus_Expense_Income__c , 
(24 * Amount_Minus_Expense_Income__c ) / 
( 
(month(Contract_End_Date__c) + 12*year(Contract_End_Date__c)) - (month(Month_Date__c) + 12*year(Month_Date__c)))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>24 Month Cash Minus Expense Income (EV)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Pipeline Snapshot</label>
    <nameField>
        <label>Pipeline Snapshot Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pipeline Snapshots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Pipeline_Snapshot_EV_DIff__c.object
<CustomObject>
    <fields>
        <fullName>DIFF_12_Month_Cash_Minus_Expense_Income__c</fullName>
        <description>EV DIFF - 12 Month Cash Minus Expense Income (EV)</description>
        <label>DIFF-12 Month Cash Minus Expense Income</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>DIFF_18_Month_Cash_Minus_Expenses_Income__c</fullName>
        <description>EV DIFF - 18 Month Cash Minus Expenses Income (EV)</description>
        <label>DIFF-18 Month Cash Minus Expenses Income</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>DIFF_24_Month_Cash_Minus_Expense_Income__c</fullName>
        <description>EV DIFF - 24 Month Cash Minus Expense Income (EV)</description>
        <label>DIFF-24 Month Cash Minus Expense Income</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>DIFF_Amount_Minus_Expense_Income__c</fullName>
        <description>EV DIFF - Opportunity Amount Minus Expense Income</description>
        <label>DIFF-Amount Minus Expense Income</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>DIFF_Expected_Value_Minus_Expense__c</fullName>
        <description>EV DIFF - Expected Value Minus Expense</description>
        <label>DIFF-Expected Value Minus Expense</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Delta_Type__c</fullName>
        <label>Delta Type</label>
        <picklist>
            <picklistValues>
                <fullName>No Change</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Opp EV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Increased EV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Decreased EV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed Opp - Lost / No Go</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed Opp - Won</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Month_Date__c</fullName>
        <label>Month_Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity_Name__c</fullName>
        <label>Opportunity_Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Pipeline Snapshot EV DIff</label>
    <nameField>
        <label>Pipeline Snapshot EV DIff Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pipeline Snapshot EV DIffs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BatchCalculateEVDiffTest.cls
@isTest
public class BatchCalculateEVDiffTest {
    
    @isTest
    public static void TestWithSingleRecordForNewOpp()
    {
        Account snapShotAccount = new Account(Name='Test Account');
        insert snapShotAccount;
        Account funderAccount = new Account(Name='Test Funder Account');
        insert funderAccount;
        
        Business_Unit__c bizUnit = new Business_Unit__c(Name='Test Business Unit 1');
        
        Opportunity currentOpp = new Opportunity(Name='Test Opportunity 1', Business_Unit_Owner__c = bizUnit.Id, StageName = 'Stage 5 - Submitted', CloseDate = date.today().addMonths(5), Probability = 30);
        insert currentOpp;
        
        Pipeline_Snapshot__c snapShotForCurrentMonth = new Pipeline_Snapshot__c();
        snapShotForCurrentMonth.Opportunity__c = currentOpp.Id;
        snapShotForCurrentMonth.Opportunity_Amount_Minus_Expense_Income__c = 2000;
        snapShotForCurrentMonth.Amount_Minus_Expense_Income__c = 2000;
        snapShotForCurrentMonth.Probability__c = 30;
        snapShotForCurrentMonth.Opportunity_Amount__c = 2000;
        snapShotForCurrentMonth.Amount__c = 2000;
        snapShotForCurrentMonth.Account__c = snapShotAccount.Id;
        snapShotForCurrentMonth.Country__c = 'Test Country';
        snapShotForCurrentMonth.Duration_months__c = 4;
        snapShotForCurrentMonth.Funder_Account__c = funderAccount.Id;
        snapShotForCurrentMonth.Month_Date__c = date.today();
        snapShotForCurrentMonth.Name = 'Test PS for date  ' + snapShotForCurrentMonth.Month_Date__c;
        
        Pipeline_Snapshot__c snapShotForPriorMonth = new Pipeline_Snapshot__c();
        snapShotForPriorMonth.Opportunity__c = currentOpp.Id;
        snapShotForPriorMonth.Opportunity_Amount_Minus_Expense_Income__c = 200;
        snapShotForPriorMonth.Amount_Minus_Expense_Income__c = 200;
        snapShotForPriorMonth.Probability__c = 30;
        snapShotForPriorMonth.Opportunity_Amount__c = 2000;
        snapShotForPriorMonth.Amount__c = 2000;
        snapShotForPriorMonth.Account__c = snapShotAccount.Id;
        snapShotForPriorMonth.Country__c = 'Test Country';
        snapShotForPriorMonth.Duration_months__c = 4;
        snapShotForPriorMonth.Funder_Account__c = funderAccount.Id;
        snapShotForPriorMonth.Month_Date__c = date.today().addMonths(-1);
        snapShotForPriorMonth.Name = 'Test PS for date  ' + snapShotForPriorMonth.Month_Date__c;
        
        Test.startTest();
        insert snapShotForPriorMonth;
        insert snapShotForCurrentMonth;
        ExecuteForCurrentMonth(system.today());
        Test.stopTest();
        
        //test case EV diffs count
        List<Pipeline_Snapshot_EV_DIff__c> snapShotsEVDiffAll = [select Delta_Type__c, DIFF_12_Month_Cash_Minus_Expense_Income__c, DIFF_18_Month_Cash_Minus_Expenses_Income__c, DIFF_24_Month_Cash_Minus_Expense_Income__c, DIFF_Amount_Minus_Expense_Income__c, DIFF_Expected_Value_Minus_Expense__c, Month_Date__c, Opportunity_Name__c from Pipeline_Snapshot_EV_DIff__c];
        System.assert(snapShotsEVDiffAll.size() == 1);
        
        //test case New Opp EV
        Pipeline_Snapshot_EV_DIff__c snapShotEVDiff = [select Delta_Type__c, DIFF_12_Month_Cash_Minus_Expense_Income__c, DIFF_18_Month_Cash_Minus_Expenses_Income__c, DIFF_24_Month_Cash_Minus_Expense_Income__c, DIFF_Amount_Minus_Expense_Income__c, DIFF_Expected_Value_Minus_Expense__c, Month_Date__c, Opportunity_Name__c from Pipeline_Snapshot_EV_DIff__c where Delta_Type__c = 'New Opp EV' limit 1];
        System.assert(snapShotEVDiff != null);
    }
    
    @isTest
    public static void TestWithSingleRecordForIncreasedEV()
    {
        Account snapShotAccount = new Account(Name='Test Account');
        insert snapShotAccount;
        Account funderAccount = new Account(Name='Test Funder Account');
        insert funderAccount;
        
        Business_Unit__c bizUnit = new Business_Unit__c(Name='Test Business Unit 1');
        
        Opportunity currentOpp = new Opportunity(Name='Test Opportunity 1', Business_Unit_Owner__c = bizUnit.Id, StageName = 'Stage 5 - Submitted', CloseDate = date.today().addMonths(5), Probability = 30);
        insert currentOpp;
        
        //List<Pipeline_Snapshot__c> pipelineSnapShots = new List<Pipeline_Snapshot__c>();
        Pipeline_Snapshot__c snapShotForCurrentMonth = new Pipeline_Snapshot__c();
        snapShotForCurrentMonth.Opportunity__c = currentOpp.Id;
        snapShotForCurrentMonth.Opportunity_Amount_Minus_Expense_Income__c = 2000;
        snapShotForCurrentMonth.Amount_Minus_Expense_Income__c = 2000;
        snapShotForCurrentMonth.Probability__c = 90;
        snapShotForCurrentMonth.Opportunity_Amount__c = 2000;
        snapShotForCurrentMonth.Amount__c = 2000;
        snapShotForCurrentMonth.Account__c = snapShotAccount.Id;
        snapShotForCurrentMonth.Country__c = 'Test Country';
        snapShotForCurrentMonth.Duration_months__c = 4;
        snapShotForCurrentMonth.Funder_Account__c = funderAccount.Id;
        snapShotForCurrentMonth.Month_Date__c = date.today();
        snapShotForCurrentMonth.Name = 'Test PS for date  ' + snapShotForCurrentMonth.Month_Date__c;
        
        Pipeline_Snapshot__c snapShotForPriorMonth = new Pipeline_Snapshot__c();
        snapShotForPriorMonth.Opportunity__c = currentOpp.Id;
        snapShotForPriorMonth.Opportunity_Amount_Minus_Expense_Income__c = 200;
        snapShotForPriorMonth.Amount_Minus_Expense_Income__c = 200;
        snapShotForPriorMonth.Probability__c = 2;
        snapShotForPriorMonth.Opportunity_Amount__c = 200;
        snapShotForPriorMonth.Amount__c = 200;
        snapShotForPriorMonth.Account__c = snapShotAccount.Id;
        snapShotForPriorMonth.Country__c = 'Test Country';
        snapShotForPriorMonth.Duration_months__c = 4;
        snapShotForPriorMonth.Funder_Account__c = funderAccount.Id;
        snapShotForPriorMonth.Month_Date__c = date.today().addMonths(-1);
        snapShotForPriorMonth.Name = 'Test PS for date  ' + snapShotForPriorMonth.Month_Date__c;
        
        Pipeline_Snapshot__c snapShotForPriorToLastMonth = new Pipeline_Snapshot__c();
        snapShotForPriorToLastMonth.Opportunity__c = currentOpp.Id;
        snapShotForPriorToLastMonth.Opportunity_Amount_Minus_Expense_Income__c = 200;
        snapShotForPriorToLastMonth.Amount_Minus_Expense_Income__c = 200;
        snapShotForPriorToLastMonth.Probability__c = 30;
        snapShotForPriorToLastMonth.Opportunity_Amount__c = 2000;
        snapShotForPriorToLastMonth.Amount__c = 2000;
        snapShotForPriorToLastMonth.Account__c = snapShotAccount.Id;
        snapShotForPriorToLastMonth.Country__c = 'Test Country';
        snapShotForPriorToLastMonth.Duration_months__c = 4;
        snapShotForPriorToLastMonth.Funder_Account__c = funderAccount.Id;
        snapShotForPriorToLastMonth.Month_Date__c = date.today().addMonths(-2);
        snapShotForPriorToLastMonth.Name = 'Test PS for date  ' + snapShotForPriorToLastMonth.Month_Date__c;
        
        Date dateVal = date.today();
        Test.startTest();
        insert snapShotForPriorMonth;
        insert snapShotForPriorToLastMonth;
        insert snapShotForCurrentMonth;
        ExecuteForCurrentMonth(system.today());
        Test.stopTest();
        
        //test case EV diffs count
        List<Pipeline_Snapshot_EV_DIff__c> snapShotsEVDiffAll = [select Delta_Type__c, DIFF_12_Month_Cash_Minus_Expense_Income__c, DIFF_18_Month_Cash_Minus_Expenses_Income__c, DIFF_24_Month_Cash_Minus_Expense_Income__c, DIFF_Amount_Minus_Expense_Income__c, DIFF_Expected_Value_Minus_Expense__c, Month_Date__c, Opportunity_Name__c from Pipeline_Snapshot_EV_DIff__c];
        System.assert(snapShotsEVDiffAll.size() == 1);
        
        //test case Increased EV
        Pipeline_Snapshot_EV_DIff__c snapShotEVDiff = [select Delta_Type__c, DIFF_12_Month_Cash_Minus_Expense_Income__c, DIFF_18_Month_Cash_Minus_Expenses_Income__c, DIFF_24_Month_Cash_Minus_Expense_Income__c, DIFF_Amount_Minus_Expense_Income__c, DIFF_Expected_Value_Minus_Expense__c, Month_Date__c, Opportunity_Name__c from Pipeline_Snapshot_EV_DIff__c where Delta_Type__c = 'Increased EV' limit 1];
        System.assert(snapShotEVDiff != null);
    }
    
    @isTest
    public static void TestWithSingleRecordForDecreasedEV()
    {
        Account snapShotAccount = new Account(Name='Test Account');
        insert snapShotAccount;
        Account funderAccount = new Account(Name='Test Funder Account');
        insert funderAccount;
        
        Business_Unit__c bizUnit = new Business_Unit__c(Name='Test Business Unit 1');
        
        Opportunity currentOpp = new Opportunity(Name='Test Opportunity 1', Business_Unit_Owner__c = bizUnit.Id, StageName = 'Stage 5 - Submitted', CloseDate = date.today().addMonths(5), Probability = 30);
        insert currentOpp;
        
        //List<Pipeline_Snapshot__c> pipelineSnapShots = new List<Pipeline_Snapshot__c>();
        Pipeline_Snapshot__c snapShotForCurrentMonth = new Pipeline_Snapshot__c();
        snapShotForCurrentMonth.Opportunity__c = currentOpp.Id;
        snapShotForCurrentMonth.Opportunity_Amount_Minus_Expense_Income__c = 200;
        snapShotForCurrentMonth.Amount_Minus_Expense_Income__c = 200;
        snapShotForCurrentMonth.Probability__c = 30;
        snapShotForCurrentMonth.Opportunity_Amount__c = 200;
        snapShotForCurrentMonth.Amount__c = 2000;
        snapShotForCurrentMonth.Account__c = snapShotAccount.Id;
        snapShotForCurrentMonth.Country__c = 'Test Country';
        snapShotForCurrentMonth.Duration_months__c = 4;
        snapShotForCurrentMonth.Funder_Account__c = funderAccount.Id;
        snapShotForCurrentMonth.Month_Date__c = date.today();
        snapShotForCurrentMonth.Name = 'Test PS for date  ' + snapShotForCurrentMonth.Month_Date__c;
        
        Pipeline_Snapshot__c snapShotForPriorMonth = new Pipeline_Snapshot__c();
        snapShotForPriorMonth.Opportunity__c = currentOpp.Id;
        snapShotForPriorMonth.Opportunity_Amount_Minus_Expense_Income__c = 2000;
        snapShotForPriorMonth.Amount_Minus_Expense_Income__c = 2000;
        snapShotForPriorMonth.Probability__c = 90;
        snapShotForPriorMonth.Opportunity_Amount__c = 2000;
        snapShotForPriorMonth.Amount__c = 200;
        snapShotForPriorMonth.Account__c = snapShotAccount.Id;
        snapShotForPriorMonth.Country__c = 'Test Country';
        snapShotForPriorMonth.Duration_months__c = 4;
        snapShotForPriorMonth.Funder_Account__c = funderAccount.Id;
        snapShotForPriorMonth.Month_Date__c = date.today().addMonths(-1);
        snapShotForPriorMonth.Name = 'Test PS for date  ' + snapShotForPriorMonth.Month_Date__c;
        
        Pipeline_Snapshot__c snapShotForPriorToLastMonth = new Pipeline_Snapshot__c();
        snapShotForPriorToLastMonth.Opportunity__c = currentOpp.Id;
        snapShotForPriorToLastMonth.Opportunity_Amount_Minus_Expense_Income__c = 200;
        snapShotForPriorToLastMonth.Amount_Minus_Expense_Income__c = 200;
        snapShotForPriorToLastMonth.Probability__c = 30;
        snapShotForPriorToLastMonth.Opportunity_Amount__c = 2000;
        snapShotForPriorToLastMonth.Amount__c = 2000;
        snapShotForPriorToLastMonth.Account__c = snapShotAccount.Id;
        snapShotForPriorToLastMonth.Country__c = 'Test Country';
        snapShotForPriorToLastMonth.Duration_months__c = 4;
        snapShotForPriorToLastMonth.Funder_Account__c = funderAccount.Id;
        snapShotForPriorToLastMonth.Month_Date__c = date.today().addMonths(-2);
        snapShotForPriorToLastMonth.Name = 'Test PS for date  ' + snapShotForPriorToLastMonth.Month_Date__c;
        
        //pipelineSnapShots.add(snapShot);
        Test.startTest();
        insert snapShotForPriorMonth;
        insert snapShotForPriorToLastMonth;
        insert snapShotForCurrentMonth;
        ExecuteForCurrentMonth(date.today());
        Test.stopTest();
        
        //test case EV diffs count
        List<Pipeline_Snapshot_EV_DIff__c> snapShotsEVDiffAll = [select Delta_Type__c, DIFF_12_Month_Cash_Minus_Expense_Income__c, DIFF_18_Month_Cash_Minus_Expenses_Income__c, DIFF_24_Month_Cash_Minus_Expense_Income__c, DIFF_Amount_Minus_Expense_Income__c, DIFF_Expected_Value_Minus_Expense__c, Month_Date__c, Opportunity_Name__c from Pipeline_Snapshot_EV_DIff__c];
        System.assert(snapShotsEVDiffAll.size() == 1);
        
        //test case Decreased EV
        Pipeline_Snapshot_EV_DIff__c snapShotEVDiff = [select Delta_Type__c, DIFF_12_Month_Cash_Minus_Expense_Income__c, DIFF_18_Month_Cash_Minus_Expenses_Income__c, DIFF_24_Month_Cash_Minus_Expense_Income__c, DIFF_Amount_Minus_Expense_Income__c, DIFF_Expected_Value_Minus_Expense__c, Month_Date__c, Opportunity_Name__c from Pipeline_Snapshot_EV_DIff__c where Delta_Type__c = 'Decreased EV' limit 1];
        System.assert(snapShotEVDiff != null);
    }
    
    @isTest
    public static void TestWithSingleRecordForNoChange()
    {
        Account snapShotAccount = new Account(Name='Test Account');
        insert snapShotAccount;
        Account funderAccount = new Account(Name='Test Funder Account');
        insert funderAccount;
        
        Business_Unit__c bizUnit = new Business_Unit__c(Name='Test Business Unit 1');
        
        Opportunity currentOpp = new Opportunity(Name='Test Opportunity 1', Business_Unit_Owner__c = bizUnit.Id, StageName = 'Stage 5 - Submitted', CloseDate = date.today().addMonths(5), Probability = 30);
        insert currentOpp;
        
        //List<Pipeline_Snapshot__c> pipelineSnapShots = new List<Pipeline_Snapshot__c>();
        Pipeline_Snapshot__c snapShotForCurrentMonth = new Pipeline_Snapshot__c();
        snapShotForCurrentMonth.Opportunity__c = currentOpp.Id;
        snapShotForCurrentMonth.Opportunity_Amount_Minus_Expense_Income__c = 200;
        snapShotForCurrentMonth.Amount_Minus_Expense_Income__c = 200;
        snapShotForCurrentMonth.Probability__c = 30;
        snapShotForCurrentMonth.Opportunity_Amount__c = 200;
        snapShotForCurrentMonth.Amount__c = 2000;
        snapShotForCurrentMonth.Account__c = snapShotAccount.Id;
        snapShotForCurrentMonth.Country__c = 'Test Country';
        snapShotForCurrentMonth.Duration_months__c = 4;
        snapShotForCurrentMonth.Funder_Account__c = funderAccount.Id;
        snapShotForCurrentMonth.Month_Date__c = date.today();
        snapShotForCurrentMonth.Name = 'Test PS for date  ' + snapShotForCurrentMonth.Month_Date__c;
        
        Pipeline_Snapshot__c snapShotForPriorMonth = new Pipeline_Snapshot__c();
        snapShotForPriorMonth.Opportunity__c = currentOpp.Id;
        snapShotForPriorMonth.Opportunity_Amount_Minus_Expense_Income__c = 200;
        snapShotForPriorMonth.Amount_Minus_Expense_Income__c = 200;
        snapShotForPriorMonth.Probability__c = 30;
        snapShotForPriorMonth.Opportunity_Amount__c = 200;
        snapShotForPriorMonth.Amount__c = 200;
        snapShotForPriorMonth.Account__c = snapShotAccount.Id;
        snapShotForPriorMonth.Country__c = 'Test Country';
        snapShotForPriorMonth.Duration_months__c = 4;
        snapShotForPriorMonth.Funder_Account__c = funderAccount.Id;
        snapShotForPriorMonth.Month_Date__c = date.today().addMonths(-1);
        snapShotForPriorMonth.Name = 'Test PS for date  ' + snapShotForPriorMonth.Month_Date__c;
        
        Pipeline_Snapshot__c snapShotForPriorToLastMonth = new Pipeline_Snapshot__c();
        snapShotForPriorToLastMonth.Opportunity__c = currentOpp.Id;
        snapShotForPriorToLastMonth.Opportunity_Amount_Minus_Expense_Income__c = 200;
        snapShotForPriorToLastMonth.Amount_Minus_Expense_Income__c = 200;
        snapShotForPriorToLastMonth.Probability__c = 30;
        snapShotForPriorToLastMonth.Opportunity_Amount__c = 200;
        snapShotForPriorToLastMonth.Amount__c = 2000;
        snapShotForPriorToLastMonth.Account__c = snapShotAccount.Id;
        snapShotForPriorToLastMonth.Country__c = 'Test Country';
        snapShotForPriorToLastMonth.Duration_months__c = 4;
        snapShotForPriorToLastMonth.Funder_Account__c = funderAccount.Id;
        snapShotForPriorToLastMonth.Month_Date__c = date.today().addMonths(-2);
        snapShotForPriorToLastMonth.Name = 'Test PS for date  ' + snapShotForPriorToLastMonth.Month_Date__c;

        
        //pipelineSnapShots.add(snapShot);
        Test.startTest();
        insert snapShotForPriorMonth;
        insert snapShotForPriorToLastMonth;
        insert snapShotForCurrentMonth;
        ExecuteForCurrentMonth(date.today());
        Test.stopTest();
        
        //test case No Change
        Pipeline_Snapshot_EV_DIff__c snapShotEVDiff = [select Delta_Type__c, DIFF_12_Month_Cash_Minus_Expense_Income__c, DIFF_18_Month_Cash_Minus_Expenses_Income__c, DIFF_24_Month_Cash_Minus_Expense_Income__c, DIFF_Amount_Minus_Expense_Income__c, DIFF_Expected_Value_Minus_Expense__c, Month_Date__c, Opportunity_Name__c from Pipeline_Snapshot_EV_DIff__c where Delta_Type__c = 'No Change' limit 1];
        System.assert(snapShotEVDiff != null);
    }
    
    @isTest
    public static void TestWithSingleRecordForClosedOppLost()
    {        
        Account snapShotAccount = new Account(Name='Test Account');
        insert snapShotAccount;
        Account funderAccount = new Account(Name='Test Funder Account');
        insert funderAccount;        

        Business_Unit__c bizUnit = new Business_Unit__c(Name='Test Business Unit 1');
        
        Opportunity currentOpp = new Opportunity(Name='Test Opportunity 1', Business_Unit_Owner__c = bizUnit.Id, StageName = 'Closed - Lost', CloseDate = date.today().addMonths(5), Probability = 30);
        insert currentOpp;
        
        //List<Pipeline_Snapshot__c> pipelineSnapShots = new List<Pipeline_Snapshot__c>();

        Pipeline_Snapshot__c snapShotForCurrentMonth = new Pipeline_Snapshot__c();
        snapShotForCurrentMonth.Opportunity__c = currentOpp.Id;
        snapShotForCurrentMonth.Opportunity_Amount_Minus_Expense_Income__c = 200;
        snapShotForCurrentMonth.Amount_Minus_Expense_Income__c = 200;
        snapShotForCurrentMonth.Probability__c = 30;
        snapShotForCurrentMonth.Opportunity_Amount__c = 200;
        snapShotForCurrentMonth.Amount__c = 2000;
        snapShotForCurrentMonth.Account__c = snapShotAccount.Id;
        snapShotForCurrentMonth.Country__c = 'Test Country';
        snapShotForCurrentMonth.Duration_months__c = 4;
        snapShotForCurrentMonth.Funder_Account__c = funderAccount.Id;
        snapShotForCurrentMonth.Month_Date__c = date.today();
        snapShotForCurrentMonth.Name = 'Test PS for date  ' + snapShotForCurrentMonth.Month_Date__c;
                
        
        Pipeline_Snapshot__c snapShotForPriorToLastMonth = new Pipeline_Snapshot__c();
        snapShotForPriorToLastMonth.Opportunity__c = currentOpp.Id;
        snapShotForPriorToLastMonth.Opportunity_Amount_Minus_Expense_Income__c = 200;
        snapShotForPriorToLastMonth.Amount_Minus_Expense_Income__c = 200;
        snapShotForPriorToLastMonth.Probability__c = 30;
        snapShotForPriorToLastMonth.Opportunity_Amount__c = 200;
        snapShotForPriorToLastMonth.Amount__c = 2000;
        snapShotForPriorToLastMonth.Account__c = snapShotAccount.Id;
        snapShotForPriorToLastMonth.Country__c = 'Test Country';
        snapShotForPriorToLastMonth.Duration_months__c = 4;
        snapShotForPriorToLastMonth.Funder_Account__c = funderAccount.Id;
        snapShotForPriorToLastMonth.Month_Date__c = date.today().addMonths(-2);
        snapShotForPriorToLastMonth.Name = 'Test PS for date  ' + snapShotForPriorToLastMonth.Month_Date__c;
       
       
        //pipelineSnapShots.add(snapShot);
        Test.startTest();
        insert snapShotForPriorToLastMonth;
        insert snapShotForCurrentMonth;
        ExecuteForCurrentMonth(date.today());
        Test.stopTest();
        
        //test case EV diffs count
        List<Pipeline_Snapshot_EV_DIff__c> snapShotsEVDiffAll = [select Delta_Type__c, DIFF_12_Month_Cash_Minus_Expense_Income__c, DIFF_18_Month_Cash_Minus_Expenses_Income__c, DIFF_24_Month_Cash_Minus_Expense_Income__c, DIFF_Amount_Minus_Expense_Income__c, DIFF_Expected_Value_Minus_Expense__c, Month_Date__c, Opportunity_Name__c from Pipeline_Snapshot_EV_DIff__c];
        System.assert(snapShotsEVDiffAll.size() == 1);
        
        //test case Closed Opp - Lost / No Go
        Pipeline_Snapshot_EV_DIff__c snapShotEVDiff = [select Delta_Type__c, DIFF_12_Month_Cash_Minus_Expense_Income__c, DIFF_18_Month_Cash_Minus_Expenses_Income__c, DIFF_24_Month_Cash_Minus_Expense_Income__c, DIFF_Amount_Minus_Expense_Income__c, DIFF_Expected_Value_Minus_Expense__c, Month_Date__c, Opportunity_Name__c from Pipeline_Snapshot_EV_DIff__c where Delta_Type__c = 'Closed Opp - Lost / No Go' limit 1];
        System.assert(snapShotEVDiff != null); 
    }
    
    @isTest
    public static void TestWithSingleRecordForClosedOppWon()
    {        
        Account snapShotAccount = new Account(Name='Test Account');
        insert snapShotAccount;
        Account funderAccount = new Account(Name='Test Funder Account');
        insert funderAccount;        

        Business_Unit__c bizUnit = new Business_Unit__c(Name='Test Business Unit 1');
        
        Opportunity currentOpp = new Opportunity(Name='Test Opportunity 1', Business_Unit_Owner__c = bizUnit.Id, StageName = 'Closed - Won', CloseDate = date.today().addMonths(5), Probability = 30);
        insert currentOpp;
        
        //List<Pipeline_Snapshot__c> pipelineSnapShots = new List<Pipeline_Snapshot__c>();

        Pipeline_Snapshot__c snapShotForCurrentMonth = new Pipeline_Snapshot__c();
        snapShotForCurrentMonth.Opportunity__c = currentOpp.Id;
        snapShotForCurrentMonth.Opportunity_Amount_Minus_Expense_Income__c = 200;
        snapShotForCurrentMonth.Amount_Minus_Expense_Income__c = 200;
        snapShotForCurrentMonth.Probability__c = 30;
        snapShotForCurrentMonth.Opportunity_Amount__c = 200;
        snapShotForCurrentMonth.Amount__c = 2000;
        snapShotForCurrentMonth.Account__c = snapShotAccount.Id;
        snapShotForCurrentMonth.Country__c = 'Test Country';
        snapShotForCurrentMonth.Duration_months__c = 4;
        snapShotForCurrentMonth.Funder_Account__c = funderAccount.Id;
        snapShotForCurrentMonth.Month_Date__c = date.today();
        snapShotForCurrentMonth.Name = 'Test PS for date  ' + snapShotForCurrentMonth.Month_Date__c;
                
        
        Pipeline_Snapshot__c snapShotForPriorToLastMonth = new Pipeline_Snapshot__c();
        snapShotForPriorToLastMonth.Opportunity__c = currentOpp.Id;
        snapShotForPriorToLastMonth.Opportunity_Amount_Minus_Expense_Income__c = 200;
        snapShotForPriorToLastMonth.Amount_Minus_Expense_Income__c = 200;
        snapShotForPriorToLastMonth.Probability__c = 30;
        snapShotForPriorToLastMonth.Opportunity_Amount__c = 200;
        snapShotForPriorToLastMonth.Amount__c = 2000;
        snapShotForPriorToLastMonth.Account__c = snapShotAccount.Id;
        snapShotForPriorToLastMonth.Country__c = 'Test Country';
        snapShotForPriorToLastMonth.Duration_months__c = 4;
        snapShotForPriorToLastMonth.Funder_Account__c = funderAccount.Id;
        snapShotForPriorToLastMonth.Month_Date__c = date.today().addMonths(-2);
        snapShotForPriorToLastMonth.Name = 'Test PS for date  ' + snapShotForPriorToLastMonth.Month_Date__c;
        
       
        //pipelineSnapShots.add(snapShot);
        Test.startTest();
        insert snapShotForPriorToLastMonth;
        insert snapShotForCurrentMonth;
        ExecuteForCurrentMonth(date.today());
        Test.stopTest();
        
        //test case EV diffs count
        List<Pipeline_Snapshot_EV_DIff__c> snapShotsEVDiffAll = [select Delta_Type__c, DIFF_12_Month_Cash_Minus_Expense_Income__c, DIFF_18_Month_Cash_Minus_Expenses_Income__c, DIFF_24_Month_Cash_Minus_Expense_Income__c, DIFF_Amount_Minus_Expense_Income__c, DIFF_Expected_Value_Minus_Expense__c, Month_Date__c, Opportunity_Name__c from Pipeline_Snapshot_EV_DIff__c];
        System.assert(snapShotsEVDiffAll.size() == 1);
        
        //test case Closed Opp - Won
        Pipeline_Snapshot_EV_DIff__c snapShotEVDiff = [select Delta_Type__c, DIFF_12_Month_Cash_Minus_Expense_Income__c, DIFF_18_Month_Cash_Minus_Expenses_Income__c, DIFF_24_Month_Cash_Minus_Expense_Income__c, DIFF_Amount_Minus_Expense_Income__c, DIFF_Expected_Value_Minus_Expense__c, Month_Date__c, Opportunity_Name__c from Pipeline_Snapshot_EV_DIff__c where Delta_Type__c = 'Closed Opp - Won' limit 1];
        System.assert(snapShotEVDiff != null);
    }
    
    @isTest
    public static void TestWithMultipleRecordsForNewOpp()
    {
       
        Account snapShotAccount = new Account(Name='Test Account');
        insert snapShotAccount;
        Account funderAccount = new Account(Name='Test Funder Account');
        insert funderAccount;
        
        Business_Unit__c bizUnit = new Business_Unit__c(Name='Test Business Unit 1');
        
        Opportunity currentOpp = null;
        Pipeline_Snapshot__c snapShotForCurrentMonth = null;
        
        List<Pipeline_Snapshot__c> snapShotForCurrentMonthLst = new List<Pipeline_Snapshot__c>();
        List<Opportunity> currentOppLst = new List<Opportunity>();
        
        for(integer i = 0; i < 20; i++)
        {
            currentOpp = new Opportunity(Name='Test Opportunity ' + i + ' for date  ' + date.today(), Business_Unit_Owner__c = bizUnit.Id, StageName = 'Stage 5 - Submitted', CloseDate = date.today().addMonths(5).addDays(i), Probability = 30);
            currentOppLst.add(currentOpp);
        }
        
        insert currentOppLst;        
        
        for(integer i = 0; i < 20; i++)
        {
            snapShotForCurrentMonth = new Pipeline_Snapshot__c();
            snapShotForCurrentMonth.Opportunity__c = currentOppLst[i].Id;
            snapShotForCurrentMonth.Opportunity_Amount_Minus_Expense_Income__c = 2000 + i;
            snapShotForCurrentMonth.Amount_Minus_Expense_Income__c = 2000 + i;
            snapShotForCurrentMonth.Probability__c = 30 + i;
            snapShotForCurrentMonth.Opportunity_Amount__c = 2000 + i;
            snapShotForCurrentMonth.Amount__c = 2000 + i;
            snapShotForCurrentMonth.Account__c = snapShotAccount.Id;
            snapShotForCurrentMonth.Country__c = 'Test Country';
            snapShotForCurrentMonth.Duration_months__c = 4 + i;
            snapShotForCurrentMonth.Funder_Account__c = funderAccount.Id;
            snapShotForCurrentMonth.Month_Date__c = date.today();
            snapShotForCurrentMonth.Name = 'Test PS ' + i + ' for date  ' + snapShotForCurrentMonth.Month_Date__c;
            
            snapShotForCurrentMonthLst.add(snapShotForCurrentMonth);
        }
        
        List<Pipeline_Snapshot__c> snapShotForPriorMonthLst = new List<Pipeline_Snapshot__c>();
                
        Pipeline_Snapshot__c snapShotForPriorMonth = null;
        for(integer i = 0; i < 20; i++)
        {
            snapShotForPriorMonth = new Pipeline_Snapshot__c();
            snapShotForPriorMonth.Opportunity__c = currentOppLst[i].Id;
            snapShotForPriorMonth.Opportunity_Amount_Minus_Expense_Income__c = 200 + i;
            snapShotForPriorMonth.Amount_Minus_Expense_Income__c = 200 + i;
            snapShotForPriorMonth.Probability__c = 30 + i;
            snapShotForPriorMonth.Opportunity_Amount__c = 2000 + i;
            snapShotForPriorMonth.Amount__c = 2000 + i;
            snapShotForPriorMonth.Account__c = snapShotAccount.Id;
            snapShotForPriorMonth.Country__c = 'Test Country';
            snapShotForPriorMonth.Duration_months__c = 4;
            snapShotForPriorMonth.Funder_Account__c = funderAccount.Id;
            snapShotForPriorMonth.Month_Date__c = date.today().addMonths(-1);
            snapShotForPriorMonth.Name = 'Test PS ' + i + ' for date  ' + snapShotForPriorMonth.Month_Date__c;
            
            snapShotForPriorMonthLst.add(snapShotForPriorMonth);
        }
        
        Test.startTest();
        insert snapShotForPriorMonthLst;
        insert snapShotForCurrentMonthLst;
        ExecuteForCurrentMonth(date.today());
        Test.stopTest();
        
        //test case EV diffs count
        List<Pipeline_Snapshot_EV_DIff__c> snapShotsEVDiffAll = [select Delta_Type__c, DIFF_12_Month_Cash_Minus_Expense_Income__c, DIFF_18_Month_Cash_Minus_Expenses_Income__c, DIFF_24_Month_Cash_Minus_Expense_Income__c, DIFF_Amount_Minus_Expense_Income__c, DIFF_Expected_Value_Minus_Expense__c, Month_Date__c, Opportunity_Name__c from Pipeline_Snapshot_EV_DIff__c];
        System.assert(snapShotsEVDiffAll.size() == 20);
        
        //test case New Opp EV
        List<Pipeline_Snapshot_EV_DIff__c> snapShotsEVDiffNewOpp = [select Delta_Type__c, DIFF_12_Month_Cash_Minus_Expense_Income__c, DIFF_18_Month_Cash_Minus_Expenses_Income__c, DIFF_24_Month_Cash_Minus_Expense_Income__c, DIFF_Amount_Minus_Expense_Income__c, DIFF_Expected_Value_Minus_Expense__c, Month_Date__c, Opportunity_Name__c from Pipeline_Snapshot_EV_DIff__c where Delta_Type__c = 'New Opp EV'];
        System.assert(snapShotsEVDiffNewOpp.size() == 20);
     }
    
    @isTest
    public static void TestWithMultipleRecordsForIncreasedEV()
    {
       
        Account snapShotAccount = new Account(Name='Test Account');
        insert snapShotAccount;
        Account funderAccount = new Account(Name='Test Funder Account');
        insert funderAccount;
        
        Business_Unit__c bizUnit = new Business_Unit__c(Name='Test Business Unit 1');
        
        Opportunity currentOpp = null;
        Pipeline_Snapshot__c snapShotForCurrentMonth = null;
        
        List<Pipeline_Snapshot__c> snapShotForCurrentMonthLst = new List<Pipeline_Snapshot__c>();
        List<Opportunity> currentOppLst = new List<Opportunity>();
        
        for(integer i = 0; i < 20; i++)
        {
            currentOpp = new Opportunity(Name='Test Opportunity ' + i + ' for date  ' + date.today(), Business_Unit_Owner__c = bizUnit.Id, StageName = 'Stage 5 - Submitted', CloseDate = date.today().addMonths(5).addDays(i), Probability = 30);
            currentOppLst.add(currentOpp);
        }
        
        insert currentOppLst;        
        
        for(integer i = 0; i < 20; i++)
        {
            snapShotForCurrentMonth = new Pipeline_Snapshot__c();
            snapShotForCurrentMonth.Opportunity__c = currentOppLst[i].Id;
            snapShotForCurrentMonth.Opportunity_Amount_Minus_Expense_Income__c = 2000 + i;
            snapShotForCurrentMonth.Amount_Minus_Expense_Income__c = 2000 + i;
            snapShotForCurrentMonth.Probability__c = 30 + i;
            snapShotForCurrentMonth.Opportunity_Amount__c = 2000 + i;
            snapShotForCurrentMonth.Amount__c = 2000 + i;
            snapShotForCurrentMonth.Account__c = snapShotAccount.Id;
            snapShotForCurrentMonth.Country__c = 'Test Country';
            snapShotForCurrentMonth.Duration_months__c = 4 + i;
            snapShotForCurrentMonth.Funder_Account__c = funderAccount.Id;
            snapShotForCurrentMonth.Month_Date__c = date.today();
            snapShotForCurrentMonth.Name = 'Test PS ' + i + ' for date  ' + snapShotForCurrentMonth.Month_Date__c;
            
            snapShotForCurrentMonthLst.add(snapShotForCurrentMonth);
        }
        
        List<Pipeline_Snapshot__c> snapShotForPriorMonthLst = new List<Pipeline_Snapshot__c>();
                
        Pipeline_Snapshot__c snapShotForPriorMonth = null;
        for(integer i = 0; i < 20; i++)
        {
            snapShotForPriorMonth = new Pipeline_Snapshot__c();
            snapShotForPriorMonth.Opportunity__c = currentOppLst[i].Id;
            snapShotForPriorMonth.Opportunity_Amount_Minus_Expense_Income__c = 200 + i;
            snapShotForPriorMonth.Amount_Minus_Expense_Income__c = 200 + i;
            snapShotForPriorMonth.Probability__c = 30 + i;
            snapShotForPriorMonth.Opportunity_Amount__c = 2000 + i;
            snapShotForPriorMonth.Amount__c = 2000 + i;
            snapShotForPriorMonth.Account__c = snapShotAccount.Id;
            snapShotForPriorMonth.Country__c = 'Test Country';
            snapShotForPriorMonth.Duration_months__c = 4;
            snapShotForPriorMonth.Funder_Account__c = funderAccount.Id;
            snapShotForPriorMonth.Month_Date__c = date.today().addMonths(-1);
            snapShotForPriorMonth.Name = 'Test PS ' + i + ' for date  ' + snapShotForPriorMonth.Month_Date__c;
            
            snapShotForPriorMonthLst.add(snapShotForPriorMonth);
        }
        
        List<Pipeline_Snapshot__c> snapShotForPriorToLastMonthLst = new List<Pipeline_Snapshot__c>();
                
        Pipeline_Snapshot__c snapShotForPriorToLastMonth = null;
        
        for(integer i = 0; i < 20; i++)
        {
            snapShotForPriorToLastMonth = new Pipeline_Snapshot__c();
            snapShotForPriorToLastMonth.Opportunity__c = currentOppLst[i].Id;
            snapShotForPriorToLastMonth.Opportunity_Amount_Minus_Expense_Income__c = 200 + i;
            snapShotForPriorToLastMonth.Amount_Minus_Expense_Income__c = 200 + i;
            snapShotForPriorToLastMonth.Probability__c = 30 + i;
            snapShotForPriorToLastMonth.Opportunity_Amount__c = 2000 + i;
            snapShotForPriorToLastMonth.Amount__c = 2000 + i;
            snapShotForPriorToLastMonth.Account__c = snapShotAccount.Id;
            snapShotForPriorToLastMonth.Country__c = 'Test Country';
            snapShotForPriorToLastMonth.Duration_months__c = 4;
            snapShotForPriorToLastMonth.Funder_Account__c = funderAccount.Id;
            snapShotForPriorToLastMonth.Month_Date__c = date.today().addMonths(-2);
            snapShotForPriorToLastMonth.Name = 'Test PS ' + i + ' for date  ' + snapShotForPriorToLastMonth.Month_Date__c;
            
            snapShotForPriorToLastMonthLst.add(snapShotForPriorToLastMonth);
        }
        
        Test.startTest();
        insert snapShotForPriorMonthLst;
        insert snapShotForPriorToLastMonthLst;
        insert snapShotForCurrentMonthLst;
        ExecuteForCurrentMonth(date.today());
        Test.stopTest();
        
        //test case EV diffs count
        List<Pipeline_Snapshot_EV_DIff__c> snapShotsEVDiffAll = [select Delta_Type__c, DIFF_12_Month_Cash_Minus_Expense_Income__c, DIFF_18_Month_Cash_Minus_Expenses_Income__c, DIFF_24_Month_Cash_Minus_Expense_Income__c, DIFF_Amount_Minus_Expense_Income__c, DIFF_Expected_Value_Minus_Expense__c, Month_Date__c, Opportunity_Name__c from Pipeline_Snapshot_EV_DIff__c];
        System.assert(snapShotsEVDiffAll.size() == 20);
        
        //test case New Opp EV
        List<Pipeline_Snapshot_EV_DIff__c> snapShotsEVDiffIncreasedEV = [select Delta_Type__c, DIFF_12_Month_Cash_Minus_Expense_Income__c, DIFF_18_Month_Cash_Minus_Expenses_Income__c, DIFF_24_Month_Cash_Minus_Expense_Income__c, DIFF_Amount_Minus_Expense_Income__c, DIFF_Expected_Value_Minus_Expense__c, Month_Date__c, Opportunity_Name__c from Pipeline_Snapshot_EV_DIff__c where Delta_Type__c = 'Increased EV'];
        System.assert(snapShotsEVDiffIncreasedEV.size() == 20);
     }
    
    @isTest
    public static void TestWithMultipleRecordsForNoChange()
    {
       
        Account snapShotAccount = new Account(Name='Test Account');
        insert snapShotAccount;
        Account funderAccount = new Account(Name='Test Funder Account');
        insert funderAccount;
        
        Business_Unit__c bizUnit = new Business_Unit__c(Name='Test Business Unit 1');
        
        Opportunity currentOpp = null;
        Pipeline_Snapshot__c snapShotForCurrentMonth = null;
        
        List<Pipeline_Snapshot__c> snapShotForCurrentMonthLst = new List<Pipeline_Snapshot__c>();
        List<Opportunity> currentOppLst = new List<Opportunity>();
        
        for(integer i = 0; i < 20; i++)
        {
            currentOpp = new Opportunity(Name='Test Opportunity ' + i + ' for date  ' + date.today(), Business_Unit_Owner__c = bizUnit.Id, StageName = 'Stage 5 - Submitted', CloseDate = date.today().addMonths(5).addDays(i), Probability = 30);
            currentOppLst.add(currentOpp);
        }
        
        insert currentOppLst;        
        
        for(integer i = 0; i < 20; i++)
        {
            snapShotForCurrentMonth = new Pipeline_Snapshot__c();
            snapShotForCurrentMonth.Opportunity__c = currentOppLst[i].Id;
            snapShotForCurrentMonth.Opportunity_Amount_Minus_Expense_Income__c = 200 + i;
            snapShotForCurrentMonth.Amount_Minus_Expense_Income__c = 200 + i;
            snapShotForCurrentMonth.Probability__c = 30 + i;
            snapShotForCurrentMonth.Opportunity_Amount__c = 200 + i;
            snapShotForCurrentMonth.Amount__c = 200 + i;
            snapShotForCurrentMonth.Account__c = snapShotAccount.Id;
            snapShotForCurrentMonth.Country__c = 'Test Country';
            snapShotForCurrentMonth.Duration_months__c = 4 + i;
            snapShotForCurrentMonth.Funder_Account__c = funderAccount.Id;
            snapShotForCurrentMonth.Month_Date__c = date.today();
            snapShotForCurrentMonth.Name = 'Test PS ' + i + ' for date  ' + snapShotForCurrentMonth.Month_Date__c;
            
            snapShotForCurrentMonthLst.add(snapShotForCurrentMonth);
        }
        
        List<Pipeline_Snapshot__c> snapShotForPriorMonthLst = new List<Pipeline_Snapshot__c>();
                
        Pipeline_Snapshot__c snapShotForPriorMonth = null;
        for(integer i = 0; i < 20; i++)
        {
            snapShotForPriorMonth = new Pipeline_Snapshot__c();
            snapShotForPriorMonth.Opportunity__c = currentOppLst[i].Id;
            snapShotForPriorMonth.Opportunity_Amount_Minus_Expense_Income__c = 200 + i;
            snapShotForPriorMonth.Amount_Minus_Expense_Income__c = 200 + i;
            snapShotForPriorMonth.Probability__c = 30 + i;
            snapShotForPriorMonth.Opportunity_Amount__c = 200 + i;
            snapShotForPriorMonth.Amount__c = 200 + i;
            snapShotForPriorMonth.Account__c = snapShotAccount.Id;
            snapShotForPriorMonth.Country__c = 'Test Country';
            snapShotForPriorMonth.Duration_months__c = 4;
            snapShotForPriorMonth.Funder_Account__c = funderAccount.Id;
            snapShotForPriorMonth.Month_Date__c = date.today().addMonths(-1);
            snapShotForPriorMonth.Name = 'Test PS ' + i + ' for date  ' + snapShotForPriorMonth.Month_Date__c;
            
            snapShotForPriorMonthLst.add(snapShotForPriorMonth);
        }
        
        List<Pipeline_Snapshot__c> snapShotForPriorToLastMonthLst = new List<Pipeline_Snapshot__c>();
                
        Pipeline_Snapshot__c snapShotForPriorToLastMonth = null;
        
        for(integer i = 0; i < 20; i++)
        {
            snapShotForPriorToLastMonth = new Pipeline_Snapshot__c();
            snapShotForPriorToLastMonth.Opportunity__c = currentOppLst[i].Id;
            snapShotForPriorToLastMonth.Opportunity_Amount_Minus_Expense_Income__c = 200 + i;
            snapShotForPriorToLastMonth.Amount_Minus_Expense_Income__c = 200 + i;
            snapShotForPriorToLastMonth.Probability__c = 30 + i;
            snapShotForPriorToLastMonth.Opportunity_Amount__c = 200 + i;
            snapShotForPriorToLastMonth.Amount__c = 200 + i;
            snapShotForPriorToLastMonth.Account__c = snapShotAccount.Id;
            snapShotForPriorToLastMonth.Country__c = 'Test Country';
            snapShotForPriorToLastMonth.Duration_months__c = 4;
            snapShotForPriorToLastMonth.Funder_Account__c = funderAccount.Id;
            snapShotForPriorToLastMonth.Month_Date__c = date.today().addMonths(-2);
            snapShotForPriorToLastMonth.Name = 'Test PS ' + i + ' for date  ' + snapShotForPriorToLastMonth.Month_Date__c;
            
            snapShotForPriorToLastMonthLst.add(snapShotForPriorToLastMonth);
        }
        
        Test.startTest();
        insert snapShotForPriorMonthLst;
        insert snapShotForPriorToLastMonthLst;
        insert snapShotForCurrentMonthLst;
        ExecuteForCurrentMonth(date.today());
        Test.stopTest();
        
        //test case EV diffs count
        List<Pipeline_Snapshot_EV_DIff__c> snapShotsEVDiffAll = [select Delta_Type__c, DIFF_12_Month_Cash_Minus_Expense_Income__c, DIFF_18_Month_Cash_Minus_Expenses_Income__c, DIFF_24_Month_Cash_Minus_Expense_Income__c, DIFF_Amount_Minus_Expense_Income__c, DIFF_Expected_Value_Minus_Expense__c, Month_Date__c, Opportunity_Name__c from Pipeline_Snapshot_EV_DIff__c];
        System.assert(snapShotsEVDiffAll.size() == 20);
        
        //test case New Opp EV
        List<Pipeline_Snapshot_EV_DIff__c> snapShotsEVDiffNoChange = [select Delta_Type__c, DIFF_12_Month_Cash_Minus_Expense_Income__c, DIFF_18_Month_Cash_Minus_Expenses_Income__c, DIFF_24_Month_Cash_Minus_Expense_Income__c, DIFF_Amount_Minus_Expense_Income__c, DIFF_Expected_Value_Minus_Expense__c, Month_Date__c, Opportunity_Name__c from Pipeline_Snapshot_EV_DIff__c where Delta_Type__c = 'No Change'];
        System.assert(snapShotsEVDiffNoChange.size() == 20);
     }
    
    @isTest
    public static void TestWithMultipleRecordsForClosedLost()
    {
       
        Account snapShotAccount = new Account(Name='Test Account');
        insert snapShotAccount;
        Account funderAccount = new Account(Name='Test Funder Account');
        insert funderAccount;
        
        Business_Unit__c bizUnit = new Business_Unit__c(Name='Test Business Unit 1');
        
        Opportunity currentOpp = null;
        Pipeline_Snapshot__c snapShotForCurrentMonth = null;
        
        List<Pipeline_Snapshot__c> snapShotForCurrentMonthLst = new List<Pipeline_Snapshot__c>();
        List<Opportunity> currentOppLst = new List<Opportunity>();
        
        for(integer i = 0; i < 20; i++)
        {
            currentOpp = new Opportunity(Name='Test Opportunity ' + i + ' for date  ' + date.today(), Business_Unit_Owner__c = bizUnit.Id, StageName = 'Closed - Lost', CloseDate = date.today().addMonths(5).addDays(i), Probability = 30);
            currentOppLst.add(currentOpp);
        }
        
        insert currentOppLst;        
        
        for(integer i = 0; i < 20; i++)
        {
            snapShotForCurrentMonth = new Pipeline_Snapshot__c();
            snapShotForCurrentMonth.Opportunity__c = currentOppLst[i].Id;
            snapShotForCurrentMonth.Opportunity_Amount_Minus_Expense_Income__c = 200 + i;
            snapShotForCurrentMonth.Amount_Minus_Expense_Income__c = 200 + i;
            snapShotForCurrentMonth.Probability__c = 30 + i;
            snapShotForCurrentMonth.Opportunity_Amount__c = 200 + i;
            snapShotForCurrentMonth.Amount__c = 200 + i;
            snapShotForCurrentMonth.Account__c = snapShotAccount.Id;
            snapShotForCurrentMonth.Country__c = 'Test Country';
            snapShotForCurrentMonth.Duration_months__c = 4 + i;
            snapShotForCurrentMonth.Funder_Account__c = funderAccount.Id;
            snapShotForCurrentMonth.Month_Date__c = date.today();
            snapShotForCurrentMonth.Name = 'Test PS ' + i + ' for date  ' + snapShotForCurrentMonth.Month_Date__c;
            
            snapShotForCurrentMonthLst.add(snapShotForCurrentMonth);
        }
        
        List<Pipeline_Snapshot__c> snapShotForPriorToLastMonthLst = new List<Pipeline_Snapshot__c>();
                
        Pipeline_Snapshot__c snapShotForPriorToLastMonth = null;
        
        for(integer i = 0; i < 20; i++)
        {
            snapShotForPriorToLastMonth = new Pipeline_Snapshot__c();
            snapShotForPriorToLastMonth.Opportunity__c = currentOppLst[i].Id;
            snapShotForPriorToLastMonth.Opportunity_Amount_Minus_Expense_Income__c = 200 + i;
            snapShotForPriorToLastMonth.Amount_Minus_Expense_Income__c = 200 + i;
            snapShotForPriorToLastMonth.Probability__c = 30 + i;
            snapShotForPriorToLastMonth.Opportunity_Amount__c = 200 + i;
            snapShotForPriorToLastMonth.Amount__c = 200 + i;
            snapShotForPriorToLastMonth.Account__c = snapShotAccount.Id;
            snapShotForPriorToLastMonth.Country__c = 'Test Country';
            snapShotForPriorToLastMonth.Duration_months__c = 4;
            snapShotForPriorToLastMonth.Funder_Account__c = funderAccount.Id;
            snapShotForPriorToLastMonth.Month_Date__c = date.today().addMonths(-2);
            snapShotForPriorToLastMonth.Name = 'Test PS ' + i + ' for date  ' + snapShotForPriorToLastMonth.Month_Date__c;
            
            snapShotForPriorToLastMonthLst.add(snapShotForPriorToLastMonth);
        }
        
        Test.startTest();
        insert snapShotForPriorToLastMonthLst;
        insert snapShotForCurrentMonthLst;
        ExecuteForCurrentMonth(date.today());
        Test.stopTest();
        
        //test case EV diffs count
        List<Pipeline_Snapshot_EV_DIff__c> snapShotsEVDiffAll = [select Delta_Type__c, DIFF_12_Month_Cash_Minus_Expense_Income__c, DIFF_18_Month_Cash_Minus_Expenses_Income__c, DIFF_24_Month_Cash_Minus_Expense_Income__c, DIFF_Amount_Minus_Expense_Income__c, DIFF_Expected_Value_Minus_Expense__c, Month_Date__c, Opportunity_Name__c from Pipeline_Snapshot_EV_DIff__c];
        System.assert(snapShotsEVDiffAll.size() == 20);
        
        //test case New Opp EV
        List<Pipeline_Snapshot_EV_DIff__c> snapShotsEVDiffClosedLost = [select Delta_Type__c, DIFF_12_Month_Cash_Minus_Expense_Income__c, DIFF_18_Month_Cash_Minus_Expenses_Income__c, DIFF_24_Month_Cash_Minus_Expense_Income__c, DIFF_Amount_Minus_Expense_Income__c, DIFF_Expected_Value_Minus_Expense__c, Month_Date__c, Opportunity_Name__c from Pipeline_Snapshot_EV_DIff__c where Delta_Type__c = 'Closed Opp - Lost / No Go'];
        System.assert(snapShotsEVDiffClosedLost.size() == 20);
     }
    
    @isTest
    public static void TestWithMultipleRecordsForClosedWon()
    {
       
        Account snapShotAccount = new Account(Name='Test Account');
        insert snapShotAccount;
        Account funderAccount = new Account(Name='Test Funder Account');
        insert funderAccount;
        
        Business_Unit__c bizUnit = new Business_Unit__c(Name='Test Business Unit 1');
        
        Opportunity currentOpp = null;
        Pipeline_Snapshot__c snapShotForCurrentMonth = null;
        
        List<Pipeline_Snapshot__c> snapShotForCurrentMonthLst = new List<Pipeline_Snapshot__c>();
        List<Opportunity> currentOppLst = new List<Opportunity>();
        
        for(integer i = 0; i < 20; i++)
        {
            currentOpp = new Opportunity(Name='Test Opportunity ' + i + ' for date  ' + date.today(), Business_Unit_Owner__c = bizUnit.Id, StageName = 'Closed - Won', CloseDate = date.today().addMonths(5).addDays(i), Probability = 30);
            currentOppLst.add(currentOpp);
        }
        
        insert currentOppLst;        
        
        for(integer i = 0; i < 20; i++)
        {
            snapShotForCurrentMonth = new Pipeline_Snapshot__c();
            snapShotForCurrentMonth.Opportunity__c = currentOppLst[i].Id;
            snapShotForCurrentMonth.Opportunity_Amount_Minus_Expense_Income__c = 200 + i;
            snapShotForCurrentMonth.Amount_Minus_Expense_Income__c = 200 + i;
            snapShotForCurrentMonth.Probability__c = 30 + i;
            snapShotForCurrentMonth.Opportunity_Amount__c = 200 + i;
            snapShotForCurrentMonth.Amount__c = 200 + i;
            snapShotForCurrentMonth.Account__c = snapShotAccount.Id;
            snapShotForCurrentMonth.Country__c = 'Test Country';
            snapShotForCurrentMonth.Duration_months__c = 4 + i;
            snapShotForCurrentMonth.Funder_Account__c = funderAccount.Id;
            snapShotForCurrentMonth.Month_Date__c = date.today();
            snapShotForCurrentMonth.Name = 'Test PS ' + i + ' for date  ' + snapShotForCurrentMonth.Month_Date__c;
            
            snapShotForCurrentMonthLst.add(snapShotForCurrentMonth);
        }
        
        List<Pipeline_Snapshot__c> snapShotForPriorToLastMonthLst = new List<Pipeline_Snapshot__c>();
                
        Pipeline_Snapshot__c snapShotForPriorToLastMonth = null;
        
        for(integer i = 0; i < 20; i++)
        {
            snapShotForPriorToLastMonth = new Pipeline_Snapshot__c();
            snapShotForPriorToLastMonth.Opportunity__c = currentOppLst[i].Id;
            snapShotForPriorToLastMonth.Opportunity_Amount_Minus_Expense_Income__c = 200 + i;
            snapShotForPriorToLastMonth.Amount_Minus_Expense_Income__c = 200 + i;
            snapShotForPriorToLastMonth.Probability__c = 30 + i;
            snapShotForPriorToLastMonth.Opportunity_Amount__c = 200 + i;
            snapShotForPriorToLastMonth.Amount__c = 200 + i;
            snapShotForPriorToLastMonth.Account__c = snapShotAccount.Id;
            snapShotForPriorToLastMonth.Country__c = 'Test Country';
            snapShotForPriorToLastMonth.Duration_months__c = 4;
            snapShotForPriorToLastMonth.Funder_Account__c = funderAccount.Id;
            snapShotForPriorToLastMonth.Month_Date__c = date.today().addMonths(-2);
            snapShotForPriorToLastMonth.Name = 'Test PS ' + i + ' for date  ' + snapShotForPriorToLastMonth.Month_Date__c;
            
            snapShotForPriorToLastMonthLst.add(snapShotForPriorToLastMonth);
        }
        
        Test.startTest();
        insert snapShotForPriorToLastMonthLst;
        insert snapShotForCurrentMonthLst;
		ExecuteForCurrentMonth(date.today()); 
        Test.stopTest();
        
        //test case EV diffs count
        List<Pipeline_Snapshot_EV_DIff__c> snapShotsEVDiffAll = [select Delta_Type__c, DIFF_12_Month_Cash_Minus_Expense_Income__c, DIFF_18_Month_Cash_Minus_Expenses_Income__c, DIFF_24_Month_Cash_Minus_Expense_Income__c, DIFF_Amount_Minus_Expense_Income__c, DIFF_Expected_Value_Minus_Expense__c, Month_Date__c, Opportunity_Name__c from Pipeline_Snapshot_EV_DIff__c];
        System.assert(snapShotsEVDiffAll.size() == 20);
        
        //test case New Opp EV
        List<Pipeline_Snapshot_EV_DIff__c> snapShotsEVDiffClosedWon = [select Delta_Type__c, DIFF_12_Month_Cash_Minus_Expense_Income__c, DIFF_18_Month_Cash_Minus_Expenses_Income__c, DIFF_24_Month_Cash_Minus_Expense_Income__c, DIFF_Amount_Minus_Expense_Income__c, DIFF_Expected_Value_Minus_Expense__c, Month_Date__c, Opportunity_Name__c from Pipeline_Snapshot_EV_DIff__c where Delta_Type__c = 'Closed Opp - Won'];
        System.assert(snapShotsEVDiffClosedWon.size() == 20);
     }
    
    private static void ExecuteForCurrentMonth(Date dateVal)
    {
        DateTime firstDate = dateVal.toStartOfMonth() + 1;
        DateTime lastDate = firstDate.addDays(date.daysInMonth(dateVal.year() , dateVal.month())  - 1);
        String query = '';
        query += 'SELECT Name, Opportunity__c, Opportunity__r.StageName, Opportunity__r.Name, Month_Date__c, ' +
        'X12_Month_Cash_Minus_Expense_Income_EV__c , ' +
        'X18_Month_Cash_Minus_Expenses_Income_EV__c, ' +
        'X24_Month_Cash_Minus_Expense_Income_EV__c, ' +
        'Opportunity_Amount_Minus_Expense_Income__c, ' +
        'Expected_Value_Minus_Expense__c ' +
        'FROM Pipeline_Snapshot__c ' +
        'WHERE Month_Date__c >= ' + firstDate.format('yyyy-MM-dd') + ' AND Month_Date__c <= ' + lastDate.format('yyyy-MM-dd');
        BatchCalculateEVDiff obj = new BatchCalculateEVDiff(query);
        ID batchprocessid = Database.executeBatch(obj);

    }

}