src/objects/Accounting_Subscriber__c.object
<CustomObject>
    <label>Accounting_Subscriber</label>
    <nameField>
        <displayFormat>Subscriber-{00000}</displayFormat>
        <label>Subscriber#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accounting_Subscriber</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>domain_lookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>domain (lookup)</label>
        <referenceTo>Domain__c</referenceTo>
        <relationshipLabel>Accounting_Subscriber</relationshipLabel>
        <relationshipName>Accounting_Subscriber</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>domain__c</fullName>
        <label>domain</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Accounting_Subscription__c.object
<CustomObject>
    <fields>
        <fullName>Accounting_Subscriber__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Accounting_Subscriber</label>
        <referenceTo>Accounting_Subscriber__c</referenceTo>
        <relationshipLabel>Accounting Subscriptions</relationshipLabel>
        <relationshipName>Accounting_Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Accounting_subscriber_domain__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Domain</label>
        <referenceTo>Domain__c</referenceTo>
        <relationshipLabel>Accounting Subscriptions</relationshipLabel>
        <relationshipName>Accounting_Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Accounting Subscription</label>
    <nameField>
        <displayFormat>AS-{00000}</displayFormat>
        <label>Accounting Subscription Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accounting Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Domain__c.object
<CustomObject>
    <description>CommCare Integration</description>
    <label>Domain</label>
    <nameField>
        <label>Domain Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Domain</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/hqInt_BatchFetchObjectSubscription.cls
public class hqInt_BatchFetchObjectSubscription implements Database.Batchable<Integer>,Database.AllowsCallouts,Database.Stateful {

    public hqInt_BatchFetchObjectSubscription(integer pbatchNo) {

    }

    public Iterable<Integer> start(Database.BatchableContext BC) {

        return null;
    }

    public void execute(Database.BatchableContext info, List<Integer> offsetList) {
    }

    public void finish(Database.BatchableContext info) {

    }

    public void updateMissingRelations() {
        // this method updates relation to the domain object from subscriptions
        List<Accounting_Subscription__c> subscriptions = [SELECT Id, Name, Accounting_subscriber_domain__c, Accounting_Subscriber__r.domain__c FROM Accounting_Subscription__c WHERE Accounting_subscriber_domain__c = '' AND Accounting_Subscriber__r.domain__c != ''];
        System.debug('---subscriptions with blank domain relation---' + subscriptions);

        if (subscriptions.size() > 0) {
            Set<String> domainNames = new Set<String>();
            for (Accounting_Subscription__c subscription : subscriptions) {
                domainNames.add(subscription.Accounting_Subscriber__r.domain__c);
            }
            System.debug('---domainNames---' + domainNames);

            if (domainNames.size() == 0) {
                return;
            }

            Map <String, Id> mapDomainNameId = new Map<String, Id>();
            for(Domain__c domain : [SELECT Id, Name FROM Domain__c WHERE Name in: domainNames]) {
                mapDomainNameId.put(domain.Name, domain.Id);
            }

            for (Accounting_Subscription__c subscription : subscriptions) {
                Id domainId = mapDomainNameId.get(subscription.Accounting_Subscriber__r.domain__c);
                if (domainId != null) {
                    subscription.Accounting_subscriber_domain__c = domainId;
                }
            }
    
            update subscriptions;
        }
    }
}