src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Area__c</fullName>
        <inlineHelpText>What field is the account in.</inlineHelpText>
        <label>Sector</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Agriculture and Food Security</fullName>
                </value>
                <value>
                    <fullName>Economic Development</fullName>
                </value>
                <value>
                    <fullName>Education and Training</fullName>
                </value>
                <value>
                    <fullName>Emergency Response</fullName>
                </value>
                <value>
                    <fullName>Financial Services for the Poor</fullName>
                </value>
                <value>
                    <fullName>Gender Equality and Women&apos;s Empowerment</fullName>
                </value>
                <value>
                    <fullName>Governance and Accountability</fullName>
                </value>
                <value>
                    <fullName>Health</fullName>
                </value>
                <value>
                    <fullName>Logistics</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Water, Sanitation, &amp; Hygiene</fullName>
                </value>
                <value>
                    <fullName>Legal, Human Rights</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Area__c</fullName>
        <label>Sub Sector</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>*** Agriculture and Food Security ***</fullName>
                </value>
                <value>
                    <fullName>Agriculture</fullName>
                </value>
                <value>
                    <fullName>Food Security</fullName>
                </value>
                <value>
                    <fullName>*** Economic Development ***</fullName>
                </value>
                <value>
                    <fullName>Rural Development</fullName>
                </value>
                <value>
                    <fullName>Safety &amp; Security</fullName>
                </value>
                <value>
                    <fullName>Urban Development</fullName>
                </value>
                <value>
                    <fullName>*** Education and Training ***</fullName>
                </value>
                <value>
                    <fullName>Adult Training</fullName>
                </value>
                <value>
                    <fullName>Child Education</fullName>
                </value>
                <value>
                    <fullName>Early Childhood Development</fullName>
                </value>
                <value>
                    <fullName>*** Emergency Response ***</fullName>
                </value>
                <value>
                    <fullName>Emergency Response</fullName>
                </value>
                <value>
                    <fullName>*** Financial Services for the Poor ***</fullName>
                </value>
                <value>
                    <fullName>Conditional Cash Transfer</fullName>
                </value>
                <value>
                    <fullName>Financial Services to the Poor</fullName>
                </value>
                <value>
                    <fullName>Mobile Banking</fullName>
                </value>
                <value>
                    <fullName>*** Gender Equality and Women&apos;s Emp ***</fullName>
                </value>
                <value>
                    <fullName>Gender Services</fullName>
                </value>
                <value>
                    <fullName>Sex Workers</fullName>
                </value>
                <value>
                    <fullName>*** Governance and Accountability ***</fullName>
                </value>
                <value>
                    <fullName>Governance</fullName>
                </value>
                <value>
                    <fullName>Social Accountability</fullName>
                </value>
                <value>
                    <fullName>*** Health ***</fullName>
                </value>
                <value>
                    <fullName>Cardiac Diseases</fullName>
                </value>
                <value>
                    <fullName>Care coordination</fullName>
                </value>
                <value>
                    <fullName>Cervical Cancer</fullName>
                </value>
                <value>
                    <fullName>Diagnostics</fullName>
                </value>
                <value>
                    <fullName>Diarrhea</fullName>
                </value>
                <value>
                    <fullName>Family Planning</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Temporary field: Used to edit the account field once a contract has been activated.</inlineHelpText>
        <label>New Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Area__c</fullName>
        <label>Area</label>
        <picklist>
            <picklistValues>
                <fullName>Health</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Poverty and Economic Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Natural Resource Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training &amp; Education Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Logistics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Emergency Response</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Orphans and Vulnerable Children</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Implementing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Which organization is running the project on the ground?</inlineHelpText>
        <label>Implementing Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contracts (Implementing Account)</relationshipLabel>
        <relationshipName>Implementing_Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contract_Project__c.object
<CustomObject>
    <description>Joins many Contracts to many Projects.</description>
    <fields>
        <fullName>Contract__c</fullName>
        <label>Contract</label>
        <referenceTo>DContract__c</referenceTo>
        <relationshipLabel>Deployments</relationshipLabel>
        <relationshipName>Contract_Projects_Links</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Contract Deployment</label>
    <nameField>
        <displayFormat>CD-{00000}</displayFormat>
        <label>Contract Deployment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Deployments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/DContract__c.object
<CustomObject>
    <description>Tracks all of Dimagi&apos;s Contracts</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Which account is the contract signed with.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>DContracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Area__c</fullName>
        <inlineHelpText>What is the a field this Contract is in. Can select multiple.</inlineHelpText>
        <label>Area</label>
        <picklist>
            <picklistValues>
                <fullName>Agriculture and Food Security</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Economic Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Education and Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Emergency Response</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial Services for the Poor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gender Equality and Women&apos;s Empowerment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Governance and Accountability</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Logistics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Water, Sanitation, &amp; Hygiene</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Poverty and Economic Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Natural Resource Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training &amp; Education Services</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Implementing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Which organization is implementing the contract.</inlineHelpText>
        <label>Implementing Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Implement_Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <description>A Dimagi Project</description>
    <fields>
        <fullName>Area__c</fullName>
        <label>Area</label>
        <picklist>
            <picklistValues>
                <fullName>Health</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Poverty and Economic Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Natural Resource Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training &amp; Education Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Logistics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Implementing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The organization that is implementing the project.</inlineHelpText>
        <label>Implementing Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Deployment</label>
    <nameField>
        <label>Deployment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deployments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/classes/DeploymentRelationsControllerTest.cls
@isTest
public class DeploymentRelationsControllerTest {

    @testSetup
    public static void setUp() {
        Account account = new Account(Name = 'Test');
        insert account;

        DContract__c contract = new DContract__c(Name = 'Test', Account__c = account.Id, Implementing_Account__c = account.Id,
                                                 Area__c = 'Test Area', Sub_Area__c = 'Test Sub Area');
        insert contract;

        Product2 product = new Product2(Name = 'Test Product');
        insert product;

        Project__c deployment = new Project__c(Name = 'Test Deployment', Implementing_Account__c = account.Id);
        insert deployment;

        Country__c country = new Country__c(Name = 'Test Country');
        insert country; 

        Location__c location = new Location__c(Name = 'Test Location', Country__c = country.Id);
        insert location;
    }

    @isTest
    public static void testContractRelation() {
        DContract__c contract = [SELECT Id, Name FROM DContract__c WHERE Name = 'Test' LIMIT 1];
        Project__c deployment = [SELECT Id, Name FROM Project__c WHERE Name = 'Test Deployment' LIMIT 1];

        ApexPages.StandardController sc = new ApexPages.standardController(new Contract_Project__c());
        PageReference pageRef = Page.DeploymentContractPage;
        pageRef.getParameters().put('deploymentId', deployment.Id);
        Test.setCurrentPage(pageRef);

        System.assertEquals(0, [SELECT Id FROM Contract_Project__c].size());

        Test.startTest();
        DeploymentRelationsController ctrl = new DeploymentRelationsController(sc);
        PageReference backPage = ctrl.goBack();
        Contract_Project__c rec = (Contract_Project__c) ctrl.currentRecord;
        rec.Contract__c = contract.Id;
        PageReference savePage = ctrl.saveNewRelation();
        Test.stopTest();

        System.assertNotEquals(null, backPage);
        System.assertNotEquals(null, savePage);

        System.assertEquals(1, [SELECT Id FROM Contract_Project__c].size());
        Contract_Project__c testRecord = [SELECT Id, Contract__c, Project__c FROM Contract_Project__c LIMIT 1];
        System.assertEquals(deployment.Id, testRecord.Project__c);
        System.assertEquals(contract.Id, testRecord.Contract__c);
    }

    @isTest
    public static void testLocarionRelation() {
        Location__c location = [SELECT Id, Name FROM Location__c WHERE Name = 'Test Location' LIMIT 1];
        Project__c deployment = [SELECT Id, Name FROM Project__c WHERE Name = 'Test Deployment' LIMIT 1];

        ApexPages.StandardController sc = new ApexPages.standardController(new Project_Location__c());
        PageReference pageRef = Page.DeploymentLocationPage;
        pageRef.getParameters().put('deploymentId', deployment.Id);
        Test.setCurrentPage(pageRef);

        System.assertEquals(0, [SELECT Id FROM Project_Location__c].size());

        Test.startTest();
        DeploymentRelationsController ctrl = new DeploymentRelationsController(sc);
        PageReference backPage = ctrl.goBack();
        Project_Location__c rec = (Project_Location__c) ctrl.currentRecord;
        rec.Location__c = location.Id;
        PageReference savePage = ctrl.saveNewRelation();
        Test.stopTest();

        System.assertNotEquals(null, backPage);
        System.assertNotEquals(null, savePage);

        System.assertEquals(1, [SELECT Id FROM Project_Location__c].size());
        Project_Location__c testRecord = [SELECT Id, Location__c, Project__c FROM Project_Location__c LIMIT 1];
        System.assertEquals(deployment.Id, testRecord.Project__c);
        System.assertEquals(location.Id, testRecord.Location__c);
    }

    @isTest
    public static void testProductRelation() {
        Product2 product = [SELECT Id, Name FROM Product2 WHERE Name = 'Test Product' LIMIT 1];
        Project__c deployment = [SELECT Id, Name FROM Project__c WHERE Name = 'Test Deployment' LIMIT 1];

        ApexPages.StandardController sc = new ApexPages.standardController(new Project_Product__c());
        PageReference pageRef = Page.DeploymentProductPage;
        pageRef.getParameters().put('deploymentId', deployment.Id);
        Test.setCurrentPage(pageRef);

        System.assertEquals(0, [SELECT Id FROM Project_Product__c].size());

        Test.startTest();
        DeploymentRelationsController ctrl = new DeploymentRelationsController(sc);
        PageReference backPage = ctrl.goBack();
        Project_Product__c rec = (Project_Product__c) ctrl.currentRecord;
        rec.Product__c = product.Id;
        PageReference savePage = ctrl.saveNewRelation();
        Test.stopTest();

        System.assertNotEquals(null, backPage);
        System.assertNotEquals(null, savePage);

        System.assertEquals(1, [SELECT Id FROM Project_Product__c].size());
        Project_Product__c testRecord = [SELECT Id, Product__c, Project__c FROM Project_Product__c LIMIT 1];
        System.assertEquals(deployment.Id, testRecord.Project__c);
        System.assertEquals(product.Id, testRecord.Product__c);
    }
}