src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Area__c</fullName>
        <inlineHelpText>What field is the account in.</inlineHelpText>
        <label>Sector</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Agriculture and Food Security</fullName>
                </value>
                <value>
                    <fullName>Economic Development</fullName>
                </value>
                <value>
                    <fullName>Education and Training</fullName>
                </value>
                <value>
                    <fullName>Emergency Response</fullName>
                </value>
                <value>
                    <fullName>Financial Services for the Poor</fullName>
                </value>
                <value>
                    <fullName>Gender Equality and Women&apos;s Empowerment</fullName>
                </value>
                <value>
                    <fullName>Governance and Accountability</fullName>
                </value>
                <value>
                    <fullName>Health</fullName>
                </value>
                <value>
                    <fullName>Logistics</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Water, Sanitation, &amp; Hygiene</fullName>
                </value>
                <value>
                    <fullName>Legal, Human Rights</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sub_Area__c</fullName>
        <label>Sub Sector</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>*** Agriculture and Food Security ***</fullName>
                </value>
                <value>
                    <fullName>Agriculture</fullName>
                </value>
                <value>
                    <fullName>Food Security</fullName>
                </value>
                <value>
                    <fullName>*** Economic Development ***</fullName>
                </value>
                <value>
                    <fullName>Rural Development</fullName>
                </value>
                <value>
                    <fullName>Safety &amp; Security</fullName>
                </value>
                <value>
                    <fullName>Urban Development</fullName>
                </value>
                <value>
                    <fullName>*** Education and Training ***</fullName>
                </value>
                <value>
                    <fullName>Adult Training</fullName>
                </value>
                <value>
                    <fullName>Child Education</fullName>
                </value>
                <value>
                    <fullName>Early Childhood Development</fullName>
                </value>
                <value>
                    <fullName>*** Emergency Response ***</fullName>
                </value>
                <value>
                    <fullName>Emergency Response</fullName>
                </value>
                <value>
                    <fullName>*** Financial Services for the Poor ***</fullName>
                </value>
                <value>
                    <fullName>Conditional Cash Transfer</fullName>
                </value>
                <value>
                    <fullName>Financial Services to the Poor</fullName>
                </value>
                <value>
                    <fullName>Mobile Banking</fullName>
                </value>
                <value>
                    <fullName>*** Gender Equality and Women&apos;s Emp ***</fullName>
                </value>
                <value>
                    <fullName>Gender Services</fullName>
                </value>
                <value>
                    <fullName>Sex Workers</fullName>
                </value>
                <value>
                    <fullName>*** Governance and Accountability ***</fullName>
                </value>
                <value>
                    <fullName>Governance</fullName>
                </value>
                <value>
                    <fullName>Social Accountability</fullName>
                </value>
                <value>
                    <fullName>*** Health ***</fullName>
                </value>
                <value>
                    <fullName>Cardiac Diseases</fullName>
                </value>
                <value>
                    <fullName>Care coordination</fullName>
                </value>
                <value>
                    <fullName>Cervical Cancer</fullName>
                </value>
                <value>
                    <fullName>Diagnostics</fullName>
                </value>
                <value>
                    <fullName>Diarrhea</fullName>
                </value>
                <value>
                    <fullName>Family Planning</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Area__c.object
<CustomObject>
    <label>Area</label>
    <nameField>
        <label>Area</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Country__c.object
<CustomObject>
    <description>The different countries we work in</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <description>A Dimagi Project</description>
    <fields>
        <fullName>Area__c</fullName>
        <label>Area</label>
        <picklist>
            <picklistValues>
                <fullName>Health</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Poverty and Economic Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Natural Resource Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training &amp; Education Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Logistics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Implementing Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Implementing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The organization that is implementing the project.</inlineHelpText>
        <label>Implementing Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sub_Area__c</fullName>
        <label>Sub Area</label>
        <picklist>
            <picklistValues>
                <fullName>*** Health ***</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maternal, Newborn, &amp; Child Health</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family Planning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HIV/AIDS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Malaria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Respiratory Diseases</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tuberculosis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Polio</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vaccinations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Diarrhea</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Primary Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Communicable Diseases</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mental Health</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nutrition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>*** Poverty and Economic Development ***</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gender Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Water, Sanitation, &amp; Hygiene</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial Services to the Poor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Urban Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>*** Natural Resource Management ***</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agriculture</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Food Security</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Environment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>*** Training &amp; Education Services ***</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adult Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Child Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Early Childhood Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>*** Logistics ***</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Human Resources</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commodity Tracking/Procurement</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <label>Deployment</label>
    <nameField>
        <label>Deployment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deployments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ProjectCountry__c.object
<CustomObject>
    <description>Allows showing open and closed projects on the country page layout.</description>
    <fields>
        <fullName>Area__c</fullName>
        <formula>Project__r.Area_Text__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Area</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Deployments</relationshipLabel>
        <relationshipName>Project_Countries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Countries</relationshipLabel>
        <relationshipName>Project_Countries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sub_Area__c</fullName>
        <formula>Project__r.Sub_Area_Text__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sub Area</label>
        <type>Text</type>
    </fields>
    <label>Project Country</label>
    <nameField>
        <displayFormat>PC-{00000}</displayFormat>
        <label>Project Country Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SFDC_Employee__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Employees</relationshipLabel>
        <relationshipName>Country</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ProjectCountrySubSector.cls
public with sharing class ProjectCountrySubSector {

    public static void updateCountrySubSector(Country__c country) {
        Set<Id> deletedProjects = new Set<Id>();
        updateCountrySubSector(country, deletedProjects);
    }

    public static void updateCountrySubSector(Country__c country, Set<Id> deletedProjects) {
        String newSubSectorsString;
        String newSectorsString;
        Set<String> newSubSectorsSet = new Set<String>();
        Set<String> newSectorsSet = new Set<String>();
        Country__c currentCountry = country;
        Set<Id> deletedProjectIds = deletedProjects;

        // Loop through each deployment and add each deployments subsectors to the Set
        for (ProjectCountry__c pc : [SELECT Project__c, Project__r.Sub_Area__c, Project__r.Area__c
                                     FROM ProjectCountry__c
                                     WHERE Country__r.Id = :currentCountry.Id
                                     AND Project__r.Id NOT IN: deletedProjectIds
                                     AND Project__r.Id != null]) {
            // Add each deployment's sub sector to the full set of subsectors
            if (pc.Project__r.Sub_Area__c != null) {
                newSubSectorsSet.addAll(pc.Project__r.Sub_Area__c.split(';'));
            }
            if (pc.Project__r.Area__c != null) {
                newSectorsSet.addAll(pc.Project__r.Area__c.split(';'));
            }
        }

         // Turn the new Sets set into strings
         currentCountry.Sub_Area__c = toString(newSubSectorsSet);
         currentCountry.Area__c = toString(newSectorsSet);
         update currentCountry;
        }

    // Gets all country Ids of Countries attached to a Deployment
    public static Set<Country__c> getCountries(Set<Id> projectId) {
        Set<ID> pIds = projectId;
        Set<Country__c> countries = new Set<Country__c>([SELECT Id FROM Country__c WHERE Id IN
                                                            (SELECT Country__c FROM ProjectCountry__c WHERE Project__r.Id IN: pIds)]);
        return countries;
    }

    public static String toString(Set<String> inputSet) {
        String result = '';
        for (String s : inputSet) {
             result += s +'; ';
        }
        if(String.isEmpty(result)) {
            result = '';
        }
        return result.replace('null', '').removeEnd('; ');
    }

    public static testMethod void unitTest() {

        Account account = new Account(Name='test');
        insert account;
        Project__c project = new Project__c(Name = 'Testing', Implementing_Account__c = account.Id);
        insert project;
        Country__c country = new Country__c(Name = 'Testing Country');
        insert country;
        ProjectCountry__c pc = new ProjectCountry__c(Country__c = country.Id, Project__c = project.Id);
        insert pc;

        project.Sub_Area__c = 'Agriculture;Health';
        update project;
    }
}