src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Country__c.object
<CustomObject>
    <description>The different countries we work in</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <description>A Dimagi Project</description>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Implementing Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Implementing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The organization that is implementing the project.</inlineHelpText>
        <label>Implementing Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Deployment</label>
    <nameField>
        <label>Deployment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deployments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ProjectCountry__c.object
<CustomObject>
    <description>Allows showing open and closed projects on the country page layout.</description>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Deployments</relationshipLabel>
        <relationshipName>Project_Countries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Countries</relationshipLabel>
        <relationshipName>Project_Countries</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Country</label>
    <nameField>
        <displayFormat>PC-{00000}</displayFormat>
        <label>Project Country Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ProjectCountryTriggerTest.cls
/**
 * Tests the updates of the Country_Text__c field in Project with the names of the Project Countries
 *
 * @author  Virginia Fernández
 * @date    04/12/2013
 */
@isTest
private class ProjectCountryTriggerTest {

    static testMethod void newProjectCountryTest() {
    	Account account = new Account();
    	account.Name = 'Account';
    	insert account;
    	
        Project__c project = new Project__c();
        project.Name = 'Project';
        project.Implementing_Account__c = account.Id;
        insert project;
        
        Country__c country1 = new Country__c();
        country1.Name = 'Country1';
        insert country1;
        
        Country__c country2 = new Country__c();
        country2.Name = 'Country2';
        insert country2;
        
        Test.startTest();
        
        ProjectCountry__c projCountry1 = new ProjectCountry__c();
        projCountry1.Country__c = country1.Id;
        projCountry1.Project__c = project.Id;
        insert projCountry1;
        
        project = [select Id, Country_Text__c from Project__c where id =: project.Id];
        System.assertEquals(project.Country_Text__c, 'Country1');
        
        ProjectCountry__c projCountry2 = new ProjectCountry__c();
        projCountry2.Country__c = country2.Id;
        projCountry2.Project__c = project.Id;
        insert projCountry2;
        
        project = [select Id, Country_Text__c from Project__c where id =: project.Id];
        System.assertEquals(project.Country_Text__c, 'Country2; Country1');
        
        Test.stopTest();
        
    }
    
    static testMethod void deleteProjectCountryTest() {
        Account account = new Account();
        account.Name = 'Account';
        insert account;
        
        Project__c project = new Project__c();
        project.Name = 'Project';
        project.Implementing_Account__c = account.Id;
        insert project;
        
        Country__c country1 = new Country__c();
        country1.Name = 'Country1';
        insert country1;
        
        Country__c country2 = new Country__c();
        country2.Name = 'Country2';
        insert country2;
        
        ProjectCountry__c projCountry1 = new ProjectCountry__c();
        projCountry1.Country__c = country1.Id;
        projCountry1.Project__c = project.Id;
        insert projCountry1;
        
        ProjectCountry__c projCountry2 = new ProjectCountry__c();
        projCountry2.Country__c = country2.Id;
        projCountry2.Project__c = project.Id;
        insert projCountry2;
        
        Test.startTest();
        
        project = [select Id, Country_Text__c from Project__c where id =: project.Id];
        System.assertEquals(project.Country_Text__c, 'Country2; Country1');
        
        delete projCountry2;
        
        project = [select Id, Country_Text__c from Project__c where id =: project.Id];
        System.assertEquals(project.Country_Text__c, 'Country1');
        
        Test.stopTest();
        
    }
}