src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Validate = Need to contact; 
Connect = remind every 10 days; 
Active = an active opportunity; 
Passive = remind every 3 months.</inlineHelpText>
        <label>Status_old</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Validate</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Connect</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Passive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Accounting_BillingAccount__c.object
<CustomObject>
    <fields>
        <fullName>is_active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active Status</label>
        <type>Checkbox</type>
    </fields>
    <label>Accounting BillingAccount</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounting BillingAccount</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Accounting_Subscription__c.object
<CustomObject>
    <fields>
        <fullName>Accounting_subscriber_domain__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Domain</label>
        <referenceTo>Domain__c</referenceTo>
        <relationshipLabel>Accounting Subscriptions</relationshipLabel>
        <relationshipName>Accounting_Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lifetime_MRR__c</fullName>
        <description>The MRR of the subscription over its lifespan. Does not include non SMS or user fees. Assumes end date is today if there is no end date.</description>
        <formula>(BLANKVALUE(date_end__c,TODAY()) - date_start__c) / 30.1 *  accounting_software_monthly_fee__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The MRR of the subscription over its lifespan. Does not include non SMS or user fees. Assumes end date is today if there is no end date.</inlineHelpText>
        <label>Lifetime MRR</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Software_Plan_Edition__c</fullName>
        <formula>plan_version__r.Accounting_SoftwarePlan__r.edition__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Software Plan Edition</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>account</label>
        <referenceTo>Accounting_BillingAccount__c</referenceTo>
        <relationshipLabel>Accounting Subscriptions</relationshipLabel>
        <relationshipName>Accounting_Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>accounting_software_monthly_fee__c</fullName>
        <formula>plan_version__r.Software_Product_Rate__r.monthly_fee__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Monthly fee</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>date_end__c</fullName>
        <label>date_end</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>date_start__c</fullName>
        <label>date_start</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>is_active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>is_active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>service_type__c</fullName>
        <label>service_type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Accounting Subscription</label>
    <nameField>
        <displayFormat>AS-{00000}</displayFormat>
        <label>Accounting Subscription Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accounting Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Contact Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1- Working - Active Opp Development</fullName>
                </value>
                <value>
                    <fullName>2- Working - Talking</fullName>
                </value>
                <value>
                    <fullName>3- Working - Contacted</fullName>
                </value>
                <value>
                    <fullName>4- Strategic Partner</fullName>
                </value>
                <value>
                    <fullName>5- Active Project Team Member</fullName>
                </value>
                <value>
                    <fullName>6- Active Self Start</fullName>
                </value>
                <value>
                    <fullName>7- Passive &amp; Friendly</fullName>
                </value>
                <value>
                    <fullName>8- Passive &amp; Unfriendly</fullName>
                </value>
                <value>
                    <fullName>9-HOLD Not mine/move</fullName>
                </value>
                <value>
                    <fullName>10-Dimagi Staff</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Country__c.object
<CustomObject>
    <description>The different countries we work in</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DContract__c.object
<CustomObject>
    <description>Tracks all of Dimagi&apos;s Contracts</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Which account is the contract signed with.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>DContracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contract_End_Date__c</fullName>
        <inlineHelpText>When the project actually ends.</inlineHelpText>
        <label>Contract End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Contract_Start_Date__c</fullName>
        <inlineHelpText>When the contract actually starts.</inlineHelpText>
        <label>Contract Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Dimagi PM</inlineHelpText>
        <label>Project Manager</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Contracts_PM</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Short_Description__c</fullName>
        <label>Short Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Domain__c.object
<CustomObject>
    <description>CommCare Integration</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SF Account (Organization)</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Domain</relationshipLabel>
        <relationshipName>Domain</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>InternalProp_commcare_edition__c</fullName>
        <formula>Internal_Properties__r.commcare_edition__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>InternalProp_commcare_edition</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Inside_Sales__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check if went through the inside sales process</description>
        <inlineHelpText>Check if went through the inside sales process</inlineHelpText>
        <label>Is Inside Sales?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Lifetime_MRR__c</fullName>
        <label>Lifetime MRR</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Project_Length__c</fullName>
        <description>Project length in days (first to last form submission)</description>
        <formula>cpLastFormSubmissionDate__c -  cpFirstFormSubmissionDate__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Project length in days (first to last form submission)</inlineHelpText>
        <label>Project Length</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>is_active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Domain_is_active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>short_description__c</fullName>
        <label>Domain_short_description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Domain</label>
    <nameField>
        <label>Domain Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Domain</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>What country is this opportunity taking place.</inlineHelpText>
        <label>Implementing Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Short_Description__c</fullName>
        <label>Short Description</label>
        <type>TextArea</type>
    </fields>
</CustomObject>

src/objects/SFDC_Employee__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Employees</relationshipLabel>
        <relationshipName>Country</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CountryListAcc.cls
/**
 * Apex Controller for Global Accounts View
 */
public class CountryListAcc{

    public List<Account> lstAcc {get; set;}
    public List<Contact> lstCon {get; set;}
    public List<DContract__c> lstContr {get; set;}
    public List<DContract__c> lstContrclosed {get; set;}
    public List<Domain__c> lstDomains {get; set;}
    public List<Accounting_Subscription__c> lstSubscriptions {get; set;}
    public List<Opportunity> lstoppty {get; set;}
    public List<Opportunity> lstopptyClosed {get; set;}
    public String searchString {get; set;}
    public Boolean showPage {get; set;}
    public List<AccountWrapper> wrapperList {get; set;}
    public Map<Id, String> accountMap = new Map<Id, String>();

    //Account selected by radio button
    public String selectedAccountId { get; set; }
    public List<Account> childAccounts { get; set; }

    private Set<Id> setId = new Set<Id>();
    private List<Id> accIdList = new List<Id>();

    public CountryListAcc() {
        this.childAccounts = new List<Account>();
        this.lstCon = new List<Contact>();
        this.lstContr = new List<DContract__c>();
        this.lstContrclosed = new List<DContract__c>();
        this.lstDomains = new List<Domain__c>();
        this.lstSubscriptions = new List<Accounting_Subscription__c>();
        this.lstoppty = new List<Opportunity>();
        this.lstopptyClosed = new List<Opportunity>();
        this.showPage = false;
        this.wrapperList = new List<AccountWrapper>();
        this.accountMap.clear();

        String strX = ApexPages.currentPage().getParameters().get('q');
        String accountId = ApexPages.currentPage().getParameters().get('id');

        if(strX != null && strX != '' && strX != 'null') {
            this.searchString = strX;
            search();
            if(accountId != null && accountId != '' && accountId != 'null') {
                this.selectedAccountId = accountId;
                searchByAccount();
            }
        }
    }

    public void search() {
        clearData();

        //Select records from Account according to given search string
        String searchQuery = 'SELECT Name, Id, Country__r.Name, Status__c, Parent.Name FROM Account WHERE Name LIKE \'%'+SearchString+'%\'';
        this.lstAcc = Database.query(searchQuery);

        //Create collection of wrapper class
        if(this.lstAcc.size() > 0){
            for(Account ac : this.lstAcc){
                this.wrapperList.add(new AccountWrapper(ac,false));
                this.setId.add(ac.Id);
                this.accIdList.add(ac.Id);
                this.accountMap.put(ac.Id,ac.Name);
            }
        }

        for(Account acc: [SELECT Name, Id, Country__r.Name, Status__c, Parent.Name FROM Account WHERE ParentId IN : this.accIdList]) {
            if(!this.setId.contains(acc.Id)) {
                this.wrapperList.add(new AccountWrapper(acc, true));
                this.lstAcc.add(acc);
                this.setId.add(acc.Id);
            }
        }
        this.showPage = true;
    }

    public PageReference searchButtonAction() {
        PageReference page = new PageReference('/apex/CountryList?q=' + this.searchString);
        page.setRedirect(true);
        return page;
    }

    public PageReference searchByAccountButtonAction() {
        String selectedAccountName = this.accountMap.get(this.selectedAccountId);
        PageReference page = new PageReference('/apex/CountryList?q=' + selectedAccountName + '&id=' + this.selectedAccountId);
        page.setRedirect(true);
        return page;
    }

    //Action on radiobutton
    public void searchByAccount(){
        //Get child accounts
        this.childAccounts = [Select Name,Id,Country__r.Name,Status__c,Parent.Name from account where Parent.Id =: this.selectedAccountId];

        //Create set of child accounts IDs
        Set<Id> childAccountIDs = new Set<Id>();
        if(this.childAccounts.size() > 0) {
            for(Account ac: this.childAccounts) {
                childAccountIDs.add(ac.Id);
            }
        }

       //Get all children objects by account Id

       //Contacts
        this.lstCon = [SELECT Id, Account.Name, Email, Title, Name, Country__c
                        FROM Contact
                        WHERE AccountId =: this.selectedAccountId];

        //Contracts Open
        this.lstContr = [SELECT Id, Name, Account__c, DContract__c.Account__r.Name,
                                     Contract_Start_Date__c, Contract_End_Date__c, Project_Manager__c,
                                     Project_Manager__r.Name, Status__c, Short_Description__c
                          FROM DContract__c
                          WHERE Account__c =: this.selectedAccountId AND Status__c != 'Complete' ];

        //Contracts Closed
        this.lstContrclosed = [SELECT Id, Name, Account__c, DContract__c.Account__r.Name,
                                     Contract_Start_Date__c, Contract_End_Date__c, Project_Manager__c,
                                     Project_Manager__r.Name, Status__c, Short_Description__c
                                FROM DContract__c
                                WHERE Account__c =: this.selectedAccountId AND Status__c = 'Complete' ];

        //Domains
        this.lstDomains = [SELECT Id, Name, Account__c, Account__r.Name, Project_Length__c, InternalProp_commcare_edition__c, Lifetime_MRR__c,
                                    is_active__c, Is_Inside_Sales__c
                            FROM Domain__c WHERE Account__c =: this.selectedAccountId];

        //Opportunities Open
        this.lstoppty = [SELECT Id, Name,Account.Name, Description, Country__c,Country__r.Name, StageName
                            FROM Opportunity
                            WHERE AccountId =: this.selectedAccountId AND
                                (StageName = 'Stage 1 - Connect' OR StageName = 'Stage 2 - Talking' OR StageName = 'Stage 3 - Prospect' OR
                                StageName = 'Stage 4 - Proposal Development' OR StageName = 'Stage 5 - Submitted' OR StageName = 'Stage 6 - In Negotiations' OR
                                StageName = 'On Hold')];

        //Opportunities Closed
        this.lstopptyClosed = [SELECT Id, Name, Account.Name, Description, Country__c, Country__r.Name, StageName
                                FROM Opportunity
                                WHERE AccountId =: this.selectedAccountId AND (StageName = 'Closed - Lost' OR StageName = 'Closed - Won')];

        //Get all child objects by child accounts IDs

        //Contacts
        List<Contact> lstConChild = [SELECT Id, Account.Name, Email, Title, Name, Country__c
                                        FROM Contact
                                        WHERE AccountId IN: childAccountIDs];
        this.lstCon.addAll(lstConChild);

        //Contracts Open    
        List<DContract__c> lstContrChild =   [SELECT Id, Name, Account__c, DContract__c.Account__r.Name,
                                                         Contract_Start_Date__c, Contract_End_Date__c, Project_Manager__c,
                                                         Project_Manager__r.Name, Status__c, Short_Description__c
                                                FROM DContract__c
                                                WHERE Account__c IN: childAccountIDs AND Status__c != 'Complete'];
        this.lstContr.addAll(lstContrChild);

       //Contracts Closed
        List<DContract__c> lstContrclosedChild = [SELECT Id, Name,Account__c, DContract__c.Account__r.Name,
                                                             Contract_Start_Date__c, Contract_End_Date__c, Project_Manager__c,
                                                             Project_Manager__r.Name, Status__c, Short_Description__c
                                                    FROM DContract__c
                                                    WHERE Account__c IN: childAccountIDs AND Status__c = 'Complete'];
        this.lstContrclosed.addAll(lstContrclosedChild);

        //Domains
        List<Domain__c> lstDomainChilds = [SELECT Id, Name, Account__c, Account__r.Name, Project_Length__c, InternalProp_commcare_edition__c, Lifetime_MRR__c,
                                                    is_active__c, Is_Inside_Sales__c
                                            FROM Domain__c WHERE Account__c IN: childAccountIDs];
        this.lstDomains.addAll(lstDomainChilds);

        // Subscriptions
        this.lstSubscriptions = [SELECT Id, Name, Accounting_subscriber_domain__c, Accounting_subscriber_domain__r.Name,
                                        date_start__c, date_end__c, Software_Plan_Edition__c, accounting_software_monthly_fee__c,
                                        service_type__c
                                    FROM Accounting_Subscription__c WHERE Accounting_subscriber_domain__c IN: this.lstDomains AND is_active__c = true];

        //Opportunities Open
        List<Opportunity> lstopptyChild = [SELECT Id, Name, Account.Name, Description, Country__c,Country__r.Name, StageName
                                      FROM Opportunity
                                      WHERE AccountId IN: childAccountIDs AND
                                             (StageName = 'Stage 1 - Connect' OR StageName = 'Stage 2 - Talking' OR StageName = 'Stage 3 - Prospect' OR
                                              StageName = 'Stage 4 - Proposal Development' OR StageName = 'Stage 5 - Submitted' OR StageName = 'Stage 6 - In Negotiations' OR
                                              StageName = 'On Hold')];
        this.lstoppty.addAll(lstopptyChild);

        //Opportunities Closed
        List<Opportunity> lstopptyClosedChild = [SELECT Id, Name, Account.Name, Description, Country__c, Country__r.Name, StageName
                                                    FROM Opportunity
                                                    WHERE AccountId IN: childAccountIDs AND
                                                    (StageName = 'Closed - Lost' OR StageName = 'Closed - Won')];
        this.lstopptyClosed.addAll(lstopptyClosedChild);
    }

    private void clearData() {
        this.wrapperList.clear();
        this.childAccounts.clear();
        this.lstCon.clear();
        this.lstContrclosed.clear();
        this.lstDomains.clear();
        this.lstSubscriptions.clear();
        this.lstoppty.clear();
        this.lstopptyClosed.clear();
    }

    public class AccountWrapper {

        public Account acc {get; set;}
        public Boolean child {get; set;}

        public AccountWrapper(Account c,Boolean ch) {
            this.acc = c;
            this.child = ch;
        }
    }
}