src/objects/Accounting_Subscription__c.object
<CustomObject>
    <fields>
        <fullName>Accounting_subscriber_domain__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Domain</label>
        <referenceTo>Domain__c</referenceTo>
        <relationshipLabel>Accounting Subscriptions</relationshipLabel>
        <relationshipName>Accounting_Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lifetime_MRR__c</fullName>
        <description>The MRR of the subscription over its lifespan. Does not include non SMS or user fees. Assumes end date is today if there is no end date.</description>
        <formula>(BLANKVALUE(date_end__c,TODAY()) - date_start__c) / 30.1 *  accounting_software_monthly_fee__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The MRR of the subscription over its lifespan. Does not include non SMS or user fees. Assumes end date is today if there is no end date.</inlineHelpText>
        <label>Lifetime MRR</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Accounting Subscription</label>
    <nameField>
        <displayFormat>AS-{00000}</displayFormat>
        <label>Accounting Subscription Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accounting Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Domain__c.object
<CustomObject>
    <description>CommCare Integration</description>
    <fields>
        <fullName>Lifetime_MRR__c</fullName>
        <label>Lifetime MRR</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Domain</label>
    <nameField>
        <label>Domain Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Domain</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CalculateDomainsLifeTimeMRRBatch.cls
/**
 * Updates Life Time MRR in the Domain custom objects, data taken from Subscriptions formula field.
 */
public class CalculateDomainsLifeTimeMRRBatch implements Database.Batchable<SObject> {

    public Database.QueryLocator start(Database.BatchableContext context) {
       return Database.getQueryLocator('SELECT Id, Lifetime_MRR__c FROM Domain__c');
    }

    public void execute(Database.BatchableContext context, List<SObject> domains) {
        Map<Id, Decimal> domainsLifetimeMRRs = new Map<Id, Decimal>();

        // Calculation Lifetime MRR for domain
        for (Accounting_Subscription__c subscription : [SELECT Lifetime_MRR__c, Accounting_subscriber_domain__c FROM Accounting_Subscription__c WHERE Accounting_subscriber_domain__c IN: domains]) {
            if (subscription.Lifetime_MRR__c != null) {
                if (domainsLifetimeMRRs.containsKey(subscription.Accounting_subscriber_domain__c)) {
                    Decimal lifetimeMRR = domainsLifetimeMRRs.get(subscription.Accounting_subscriber_domain__c);
                    lifetimeMRR += subscription.Lifetime_MRR__c;
                    domainsLifetimeMRRs.put(subscription.Accounting_subscriber_domain__c, lifetimeMRR);
                } else {
                    domainsLifetimeMRRs.put(subscription.Accounting_subscriber_domain__c, subscription.Lifetime_MRR__c);
                }
            }
        }

        // Set Lifetime MRR for domain
        List<Domain__c> toUpdate = new LIst<Domain__c>();
        for (SObject sObjDomain : domains) {
            Domain__c d = (Domain__c) sObjDomain;
            Decimal lifetimeMRR = domainsLifetimeMRRs.get(d.Id);
            if (lifetimeMRR == null) {
                lifetimeMRR = 0;
            }
            d.Lifetime_MRR__c = lifetimeMRR;
            toUpdate.add(d);
        }

        update toUpdate;
    }

    public void finish(Database.BatchableContext context) {
        Database.executeBatch(new DeactivateDuplicatedSubscriptionsBatch(), 4);
    }
}