src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Follow_up_Date__c</fullName>
        <inlineHelpText>Use this field to mark a date you wish to be reminded to follow up with an account. Delete the field to turn off the reminder.</inlineHelpText>
        <label>Follow-up Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Follow_up_Date__c</fullName>
        <inlineHelpText>Use this to set a specific date you&apos;d like the follow-up report to remind you to reach back out.</inlineHelpText>
        <label>Follow-up Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Hubspot_Next_Activity_Date__c</fullName>
        <description>Next activity date from Hubspot. Oddly this is a text field from Hubspot, not a date.</description>
        <inlineHelpText>Next activity date from Hubspot. Oddly this is a text field from Hubspot, not a date.</inlineHelpText>
        <label>Hubspot - Next Activity Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Channel_Response__c</fullName>
        <description>What Channel is the Opportunity (Sales, B2B, Pre-Bid, Other Competitive Bid, etc.)? 
See https://confluence.dimagi.com/display/BD/BD+Channels</description>
        <inlineHelpText>What Channel is the Opportunity (Sales, B2B, Pre-Bid, Other Competitive Bid, etc.)? 
See https://confluence.dimagi.com/display/BD/BD+Channels</inlineHelpText>
        <label>Channel</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Inside Sales</fullName>
                </value>
                <value>
                    <fullName>B2B - Standard</fullName>
                </value>
                <value>
                    <fullName>B2B - Enterprise</fullName>
                </value>
                <value>
                    <fullName>Large Competitive Bid</fullName>
                </value>
                <value>
                    <fullName>Other Competitive Bid</fullName>
                </value>
                <value>
                    <fullName>NIH Prime Grant</fullName>
                </value>
                <value>
                    <fullName>CORE Funding (Gates)</fullName>
                </value>
                <value>
                    <fullName>Gates Enterprise</fullName>
                </value>
                <value>
                    <fullName>Chatbot</fullName>
                </value>
                <value>
                    <fullName>Always Exclude Reporting Only</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Latest_day_Opp_failed_sales_process__c</fullName>
        <label>Latest day Opp failed sales process</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Nb_times_Opp_failed_sales_process__c</fullName>
        <label>Nb times Opp failed sales process</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunity_Owner_Division__c</fullName>
        <description>This fields describes which division is driving the BD efforts related to this opportunity.</description>
        <inlineHelpText>This fields describes which division is driving the BD efforts related to this opportunity.</inlineHelpText>
        <label>Opportunity Owner (Division)</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Solutions</fullName>
                </value>
                <value>
                    <fullName>SaaS</fullName>
                </value>
                <value>
                    <fullName>GSO</fullName>
                </value>
                <value>
                    <fullName>GTD</fullName>
                </value>
                <value>
                    <fullName>India Division</fullName>
                </value>
                <value>
                    <fullName>USH</fullName>
                </value>
                <value>
                    <fullName>ICDS-CAS</fullName>
                    <isActive>false</isActive>
                    <label>ICDS-CAS</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity_Owner_Sub_Division__c</fullName>
        <description>This fields describes which sub-division or Practice is driving the BD efforts related to this opportunity.</description>
        <inlineHelpText>This fields describes which sub-division or Practice is driving the BD efforts related to this opportunity.</inlineHelpText>
        <label>Opportunity Owner (Sub-Division)</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>GSO - BizOps</fullName>
                </value>
                <value>
                    <fullName>GSO - BizStrat</fullName>
                </value>
                <value>
                    <fullName>GSO - CC Connect</fullName>
                </value>
                <value>
                    <fullName>GSO - Dgtl Adherence</fullName>
                </value>
                <value>
                    <fullName>GSO - Leadership</fullName>
                </value>
                <value>
                    <fullName>GSO - Marketing</fullName>
                </value>
                <value>
                    <fullName>GSO - OoCEO</fullName>
                </value>
                <value>
                    <fullName>GSO - POps</fullName>
                </value>
                <value>
                    <fullName>GSO - RAD</fullName>
                </value>
                <value>
                    <fullName>GTD - Eng Management</fullName>
                </value>
                <value>
                    <fullName>GTD - Leadership</fullName>
                </value>
                <value>
                    <fullName>GTD - QA</fullName>
                </value>
                <value>
                    <fullName>GTD - Team</fullName>
                </value>
                <value>
                    <fullName>Inbound Sales</fullName>
                </value>
                <value>
                    <fullName>India - Delivery</fullName>
                </value>
                <value>
                    <fullName>India - Leadership</fullName>
                </value>
                <value>
                    <fullName>India - Partnerships</fullName>
                </value>
                <value>
                    <fullName>India - Tech</fullName>
                </value>
                <value>
                    <fullName>SaaS - CS</fullName>
                </value>
                <value>
                    <fullName>SaaS - Management</fullName>
                </value>
                <value>
                    <fullName>SaaS - Marketing</fullName>
                </value>
                <value>
                    <fullName>SaaS - Operations</fullName>
                </value>
                <value>
                    <fullName>SaaS - Platform</fullName>
                </value>
                <value>
                    <fullName>SaaS - Product</fullName>
                </value>
                <value>
                    <fullName>SaaS - Sales</fullName>
                </value>
                <value>
                    <fullName>SaaS - Support</fullName>
                </value>
                <value>
                    <fullName>Sol - Delivery</fullName>
                </value>
                <value>
                    <fullName>Sol - Leadership</fullName>
                </value>
                <value>
                    <fullName>Sol - Partnerships</fullName>
                </value>
                <value>
                    <fullName>Sol - Tech</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/classes/OpportunityFailingSalesProcessTest.cls
@isTest
public class OpportunityFailingSalesProcessTest {

    @testSetup
    public static void setUpData() {
        insert new Opportunity(Name = 'Test Opportunity 1', StageName = 'Stage 5 - Submitted', Channel_Response__c = 'Inside Sales',
                                                 CloseDate = date.today().addMonths(5), Probability = 30,
                                                 Opportunity_Owner_Division__c = 'Solutions', Opportunity_Owner_Sub_Division__c = 'Inbound Sales');
        insert new Opportunity(Name = 'Test Opportunity 2', StageName = 'Stage 5 - Submitted', Channel_Response__c = 'Inside Sales',
                                                 CloseDate = date.today().addMonths(5), Probability = 30,
                                                 Opportunity_Owner_Division__c = 'Solutions', Opportunity_Owner_Sub_Division__c = 'Inbound Sales');
        insert new Opportunity(Name = 'Test Opportunity 3', StageName = 'Stage 5 - Submitted', Channel_Response__c = 'Inside Sales',
                                                 CloseDate = date.today().addMonths(5), Probability = 30, Latest_day_Opp_failed_sales_process__c = Date.today().addDays(-15),
                                                 Nb_times_Opp_failed_sales_process__c = 15,
                                                 Opportunity_Owner_Division__c = 'Solutions', Opportunity_Owner_Sub_Division__c = 'Inbound Sales');
    }

    @isTest
    public static void shouldSetDateAndIncrementCounter() {
        Opportunity opp1 = [SELECT Id FROM Opportunity WHERE Name = 'Test Opportunity 1' LIMIT 1];
        Opportunity opp2 = [SELECT Id FROM Opportunity WHERE Name = 'Test Opportunity 2' LIMIT 1];
        Opportunity opp3 = [SELECT Id FROM Opportunity WHERE Name = 'Test Opportunity 3' LIMIT 1];

        Account theAccount = new Account(Name = 'Test Account');
        insert theAccount;

        Contact contact1 = new Contact(LastName = 'Test Contact 1', AccountId = theAccount.Id, Follow_up_Date__c = null, Hubspot_Next_Activity_Date__c = null); // true
        insert contact1;
        Contact contact2 = new Contact(LastName = 'Test Contact 2', AccountId = theAccount.Id, Follow_up_Date__c = Date.today().addDays(-2), Hubspot_Next_Activity_Date__c = null); // true
        insert contact2;
        Contact contact3 = new Contact(LastName = 'Test Contact 3', AccountId = theAccount.Id, Follow_up_Date__c = null, Hubspot_Next_Activity_Date__c = Date.today().addDays(-1)); // true
        insert contact3;
        Contact contact4 = new Contact(LastName = 'Test Contact 4', AccountId = theAccount.Id, Follow_up_Date__c = Date.today().addDays(-15), Hubspot_Next_Activity_Date__c = Date.today().addDays(-31)); // true
        insert contact4;
        Contact contact5 = new Contact(LastName = 'Test Contact 5', AccountId = theAccount.Id, Follow_up_Date__c = Date.today(), Hubspot_Next_Activity_Date__c = null); // false
        insert contact5;
        Contact contact6 = new Contact(LastName = 'Test Contact 6', AccountId = theAccount.Id, Follow_up_Date__c = null, Hubspot_Next_Activity_Date__c = Date.today().addDays(1)); // false
        insert contact6;

        insert new OpportunityContactRole(OpportunityId = opp1.Id, ContactId = contact1.Id);
        insert new OpportunityContactRole(OpportunityId = opp2.Id, ContactId = contact2.Id);
        insert new OpportunityContactRole(OpportunityId = opp2.Id, ContactId = contact6.Id);
        insert new OpportunityContactRole(OpportunityId = opp3.Id, ContactId = contact2.Id);
        insert new OpportunityContactRole(OpportunityId = opp3.Id, ContactId = contact3.Id);
        insert new OpportunityContactRole(OpportunityId = opp3.Id, ContactId = contact4.Id);
        insert new OpportunityContactRole(OpportunityId = opp3.Id, ContactId = contact2.Id); // duplicated for test
        insert new OpportunityContactRole(OpportunityId = opp3.Id, ContactId = contact2.Id); // duplicated for test

        Test.startTest();
        Database.executeBatch(new OpportunityFailingSalesProcessBatch());
        Test.stopTest();

        Opportunity oppFromDB = [SELECT Id, Latest_day_Opp_failed_sales_process__c, Nb_times_Opp_failed_sales_process__c FROM Opportunity WHERE Name = 'Test Opportunity 1' LIMIT 1];
        System.assertEquals(Date.today(), oppFromDB.Latest_day_Opp_failed_sales_process__c);
        System.assertEquals(1, oppFromDB.Nb_times_Opp_failed_sales_process__c);
        oppFromDB = [SELECT Id, Latest_day_Opp_failed_sales_process__c, Nb_times_Opp_failed_sales_process__c FROM Opportunity WHERE Name = 'Test Opportunity 2' LIMIT 1];
        System.assertEquals(null, oppFromDB.Latest_day_Opp_failed_sales_process__c);
        System.assertEquals(null, oppFromDB.Nb_times_Opp_failed_sales_process__c);
        oppFromDB = [SELECT Id, Latest_day_Opp_failed_sales_process__c, Nb_times_Opp_failed_sales_process__c FROM Opportunity WHERE Name = 'Test Opportunity 3' LIMIT 1];
        System.assertEquals(Date.today(), oppFromDB.Latest_day_Opp_failed_sales_process__c);
        System.assertEquals(16, oppFromDB.Nb_times_Opp_failed_sales_process__c);
    }

    @isTest
    public static void shouldntUpdateFields() {
        Opportunity opp1 = [SELECT Id FROM Opportunity WHERE Name = 'Test Opportunity 1' LIMIT 1];
        Opportunity opp2 = [SELECT Id FROM Opportunity WHERE Name = 'Test Opportunity 2' LIMIT 1];
        Opportunity opp3 = [SELECT Id FROM Opportunity WHERE Name = 'Test Opportunity 3' LIMIT 1];

        Account theAccount = new Account(Name = 'Test Account');
        insert theAccount;

        Contact contact1 = new Contact(LastName = 'Test Contact 1', AccountId = theAccount.Id, Follow_up_Date__c = null, Hubspot_Next_Activity_Date__c = null); // true
        insert contact1;
        Contact contact2 = new Contact(LastName = 'Test Contact 2', AccountId = theAccount.Id, Follow_up_Date__c = Date.today().addDays(-1), Hubspot_Next_Activity_Date__c = null); // true
        insert contact2;
        Contact contact3 = new Contact(LastName = 'Test Contact 3', AccountId = theAccount.Id, Follow_up_Date__c = null, Hubspot_Next_Activity_Date__c = Date.today().addDays(-1)); // true
        insert contact3;
        Contact contact4 = new Contact(LastName = 'Test Contact 4', AccountId = theAccount.Id, Follow_up_Date__c = Date.today().addDays(-15), Hubspot_Next_Activity_Date__c = Date.today().addDays(-31)); // true
        insert contact4;
        Contact contact5 = new Contact(LastName = 'Test Contact 5', AccountId = theAccount.Id, Follow_up_Date__c = Date.today(), Hubspot_Next_Activity_Date__c = null); // false
        insert contact5;
        Contact contact6 = new Contact(LastName = 'Test Contact 6', AccountId = theAccount.Id, Follow_up_Date__c = null, Hubspot_Next_Activity_Date__c = Date.today().addDays(1)); // false
        insert contact6;

        insert new OpportunityContactRole(OpportunityId = opp1.Id, ContactId = contact5.Id);
        insert new OpportunityContactRole(OpportunityId = opp1.Id, ContactId = contact6.Id);
        insert new OpportunityContactRole(OpportunityId = opp2.Id, ContactId = contact2.Id);
        insert new OpportunityContactRole(OpportunityId = opp2.Id, ContactId = contact6.Id);

        Test.startTest();
        Database.executeBatch(new OpportunityFailingSalesProcessBatch());
        Test.stopTest();

        Opportunity oppFromDB = [SELECT Id, Latest_day_Opp_failed_sales_process__c, Nb_times_Opp_failed_sales_process__c FROM Opportunity WHERE Name = 'Test Opportunity 1' LIMIT 1];
        System.assertEquals(null, oppFromDB.Latest_day_Opp_failed_sales_process__c);
        System.assertEquals(null, oppFromDB.Nb_times_Opp_failed_sales_process__c);
        oppFromDB = [SELECT Id, Latest_day_Opp_failed_sales_process__c, Nb_times_Opp_failed_sales_process__c FROM Opportunity WHERE Name = 'Test Opportunity 2' LIMIT 1];
        System.assertEquals(null, oppFromDB.Latest_day_Opp_failed_sales_process__c);
        System.assertEquals(null, oppFromDB.Nb_times_Opp_failed_sales_process__c);
        oppFromDB = [SELECT Id, Latest_day_Opp_failed_sales_process__c, Nb_times_Opp_failed_sales_process__c FROM Opportunity WHERE Name = 'Test Opportunity 3' LIMIT 1];
        System.assertEquals(Date.today().addDays(-15), oppFromDB.Latest_day_Opp_failed_sales_process__c);
        System.assertEquals(15, oppFromDB.Nb_times_Opp_failed_sales_process__c);
    }
}