src/objects/Accounting_BillingAccount__c.object
<CustomObject>
    <label>Accounting BillingAccount</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounting BillingAccount</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Accounting_BillingAccountAdmin__c.object
<CustomObject>
    <label>Accounting_BillingAccountAdmin</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accounting_BillingAccountAdmin</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Accounting_BillingContactInfo__c.object
<CustomObject>
    <label>Accounting_BillingContactInfo</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Contact #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accounting_BillingContactInfo</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Accounting_CreditAdjustment__c.object
<CustomObject>
    <label>Accounting_CreditAdjustment</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Accounting_CreditAdjustment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accounting_CreditAdjustment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Accounting_CreditLine__c.object
<CustomObject>
    <label>Accounting_CreditLine</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Credit Line#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accounting_CreditLine</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/accounting_feature__c.object
<CustomObject>
    <label>Accounting_Feature</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounting_feature</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Accounting_Featurerate__c.object
<CustomObject>
    <label>Accounting_FeatureRate</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Accounting_Featurerate #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accounting_FeatureRate</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Accounting_Invoice__c.object
<CustomObject>
    <description>For Commcare Integration</description>
    <label>Accounting</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Accounting #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accounting</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Accounting_Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Accounting Subscription</label>
        <referenceTo>Accounting_Subscription__c</referenceTo>
        <relationshipName>Accounting_Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Accounting_LineItems__c.object
<CustomObject>
    <fields>
        <fullName>Accounting_FeatureRate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Accounting_FeatureRate</label>
        <referenceTo>Accounting_Featurerate__c</referenceTo>
        <relationshipLabel>Accounting_LineItems</relationshipLabel>
        <relationshipName>Accounting_LineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Accounting_LineItems</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Line Item #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accounting_LineItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Accounting_PaymentMethod__c.object
<CustomObject>
    <label>Accounting_PaymentMethod</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accounting_PaymentMethod</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Accounting_Paymentrecord__c.object
<CustomObject>
    <label>Accounting_Paymentrecord</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accounting_Paymentrecord</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Accounting_Softwareplan__c.object
<CustomObject>
    <label>Accounting_Softwareplan</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounting_Softwareplans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Accounting_SoftwarePlanVersion__c.object
<CustomObject>
    <fields>
        <fullName>Accounting_SoftwarePlan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Accounting_SoftwarePlan</label>
        <referenceTo>Accounting_Softwareplan__c</referenceTo>
        <relationshipLabel>Accounting_SoftwarePlanVersion</relationshipLabel>
        <relationshipName>Accounting_SoftwarePlanVersion</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Accounting_SoftwarePlanVersion</label>
    <nameField>
        <displayFormat>SoftPlanVersion-{00000}</displayFormat>
        <label>accounting_softwareplanversion Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accounting_SoftwarePlanVersion</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Accounting_SoftwareProductRate__c.object
<CustomObject>
    <label>Accounting_SoftwareProductRate</label>
    <nameField>
        <displayFormat>SoftwareProductRate-{00000}</displayFormat>
        <label>accounting_softwareproductrate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accounting_SoftwareProductRate</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Accounting_Subscriber__c.object
<CustomObject>
    <label>Accounting_Subscriber</label>
    <nameField>
        <displayFormat>Subscriber-{00000}</displayFormat>
        <label>Subscriber#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accounting_Subscriber</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Accounting_Subscription__c.object
<CustomObject>
    <fields>
        <fullName>Accounting_Subscriber__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Accounting_Subscriber</label>
        <referenceTo>Accounting_Subscriber__c</referenceTo>
        <relationshipLabel>Accounting Subscriptions</relationshipLabel>
        <relationshipName>Accounting_Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Accounting Subscription</label>
    <nameField>
        <displayFormat>AS-{00000}</displayFormat>
        <label>Accounting Subscription Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accounting Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Accounting_SubscriptionAdjustment__c.object
<CustomObject>
    <label>Accounting_SubscriptionAdjustment</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accounting_SubscriptionAdjustment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Commcare_Job_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Is_Domain_Job_Running__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Domain Job Running</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Job_Running__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Job Running</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Job_Helper_Field__c</fullName>
        <label>Job Helper Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Job_Start_Date__c</fullName>
        <label>Job Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Server_Code__c</fullName>
        <label>Server Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CommcareSyncJobSettings</label>
</CustomObject>

src/classes/HQSyncController.cls
public class HQSyncController {

    public String phaseOneServer { get; set;}
    public String phaseTwoServer { get; set;}
    public List<SelectOption> serverCodes { get; set;}
    public Boolean domainIsRunning { get; set;}
    public Boolean accountingRunning { get; set;}

    public String batchSubmittedDate { get; set;}
    public AsyncApexJob batchClassJob { get; set;}
    public List<JobWrapper> phase2Jobs { get; set;}

    public HQSyncController() {
        List<String> values = HQSyncUtils.getCommcareServers(true);
        this.serverCodes = new List<SelectOption>();
        for (String val : values) {
            this.serverCodes.add(new SelectOption(val, val));
        }

        this.phaseOneServer = values[0];
        this.phaseTwoServer = values[0];

        fetchDomainInstances();
        fetchAccountingInstances();
    }

    /**
     * Domains synchronization.
     */
    public void fetchDomainInstances() {
        this.domainIsRunning = false;
        ApexClass batchClass;
        Commcare_Job_Settings__c settings = Commcare_Job_Settings__c.getOrgDefaults();
        if (settings.Is_Domain_Job_Running__c == true) {
            this.domainIsRunning = true;
            this.phaseOneServer = settings.Server_Code__c;
        }

        try {
            batchClass = [SELECT Id FROM ApexClass WHERE Name='HQSyncDomainBatch' LIMIT 1];
        } catch(exception e) {
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR, 'Class not found'));
        }

        batchClassJob = null;
        AsyncApexJob[] batchClassJobList = [SELECT Id, JobItemsProcessed, TotalJobItems, createdDate FROM AsyncApexJob WHERE ApexClassID = :batchClass.Id
                                                AND Status IN ('Holding', 'Queued', 'Preparing', 'Processing') ORDER BY createdDate DESC LIMIT 1];

        if(batchClassJobList != null && batchClassJobList.size() > 0) {
            this.domainIsRunning = true;
            this.batchClassJob = batchClassJobList[0];
            this.batchSubmittedDate = batchClassJobList[0].createdDate.format();
        }
    }

    public PageReference runDomainsSynchronizationJob() {
        fetchDomainInstances();
        if(!this.domainIsRunning) {
            Commcare_Job_Settings__c settings = Commcare_Job_Settings__c.getOrgDefaults();
            settings.Is_Domain_Job_Running__c = true;
            update settings;
            Database.executeBatch(new HQSyncDomainBatch(this.phaseOneServer, null, new List<String>()), 1);
        }

        fetchDomainInstances();
        return null;
    }

    /**
     * Accounting synchronization.
     */
    public void fetchAccountingInstances() {
        List <String> objectNames = new List <String>();
        objectNames.add(accounting_feature__c.SObjectType.getDescribe().getLabel());
        objectNames.add(Accounting_BillingAccountAdmin__c.SObjectType.getDescribe().getLabel());
        objectNames.add(Accounting_Softwareplan__c.SObjectType.getDescribe().getLabel());
        objectNames.add(Accounting_Subscriber__c.SObjectType.getDescribe().getLabel());
        objectNames.add(Accounting_Featurerate__c.SObjectType.getDescribe().getLabel());
        objectNames.add(Accounting_SoftwareProductRate__c.SObjectType.getDescribe().getLabel());
        objectNames.add(Accounting_SoftwarePlanVersion__c.SObjectType.getDescribe().getLabel());
        objectNames.add(Accounting_PaymentMethod__c.SObjectType.getDescribe().getLabel());
        objectNames.add(Accounting_BillingContactInfo__c.SObjectType.getDescribe().getLabel());
        objectNames.add(Accounting_Paymentrecord__c.SObjectType.getDescribe().getLabel());
        objectNames.add(Accounting_Billingaccount__c.SObjectType.getDescribe().getLabel());
        objectNames.add(Accounting_Subscription__c.SObjectType.getDescribe().getLabel());
        objectNames.add(Accounting_Invoice__c.SObjectType.getDescribe().getLabel());
        objectNames.add(Accounting_LineItems__c.SObjectType.getDescribe().getLabel());
        objectNames.add(Accounting_SubscriptionAdjustment__c.SObjectType.getDescribe().getLabel());
        objectNames.add(Accounting_CreditLine__c.SObjectType.getDescribe().getLabel());
        objectNames.add(Accounting_CreditAdjustment__c.SObjectType.getDescribe().getLabel());

        this.accountingRunning = false;
        Commcare_Job_Settings__c settings = Commcare_Job_Settings__c.getOrgDefaults();
        this.accountingRunning = settings.Is_Job_Running__c;
        String customObject = settings.Job_Helper_Field__c;
        this.phaseTwoServer = this.accountingRunning == true ? settings.Server_Code__c : this.phaseTwoServer;

        this.batchClassJob = null;
        AsyncApexJob[] batchClassJobList = [SELECT Id, JobItemsProcessed, TotalJobItems, createdDate, ApexClass.Id, ApexClass.Name, Status, CompletedDate
                                            FROM AsyncApexJob
                                            WHERE ApexClass.Name = 'HQSyncAccountingBatch' AND Status IN ('Holding', 'Queued', 'Preparing', 'Processing')
                                            ORDER BY createdDate DESC LIMIT 1];

        if(batchClassJobList != null && batchClassJobList.size() > 0) {
            this.accountingRunning = true;
            this.batchClassJob = batchClassJobList[0];
        }

        phase2Jobs = new List<JobWrapper>();

        for (String jobName : objectNames) {
            JobWrapper jobWrapper = new jobWrapper();
            jobWrapper.jobName = jobName;
            phase2Jobs.add(jobWrapper);
        }

        JobWrapper jobWrapper;
        for (JobWrapper job : phase2Jobs) {
            if (job.jobName == customObject) {
                jobWrapper = job;
                break;
            }
        }

        if (jobWrapper != null && batchClassJob != null) {
            jobWrapper.jobItemsProcessed = batchClassJob.JobItemsProcessed;
            jobWrapper.totalJobItems = batchClassJob.TotalJobItems;
            jobWrapper.isRunning = true;
        }
    }

    public PageReference runAccountingJob() {
        fetchAccountingInstances();

        if (this.accountingRunning == false) {
            Commcare_Job_Settings__c settings = Commcare_Job_Settings__c.getOrgDefaults();
            settings.Job_Start_Date__c = Date.today();
            settings.Is_Job_Running__c = true;
            update settings;

            HQSyncUtils.runAccountingBatchJob(1, this.phaseTwoServer, new List<String>());
        }

        fetchAccountingInstances();
        return null;
    }
}