src/objects/Admin_Reports_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Admin Reports Settings</label>
    <fields>
        <fullName>DM_Map_Id__c</fullName>
        <label>DM Map Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DM_Map_Token__c</fullName>
        <label>DM Map Token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Area__c.object
<CustomObject>
    <label>Area</label>
    <nameField>
        <label>Area</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Domain__c.object
<CustomObject>
    <description>CommCare Integration</description>
    <fields>
        <fullName>Countries_Picklist__c</fullName>
        <label>Countries Picklist</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>NIGER</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Countries_Wrapper__c</fullName>
        <description>Countires wrapper field, we want use aggregate queries on country list but it is A big text area (Deployment_Countries__c).</description>
        <label>Countries Wrapper</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Internal_Properties__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Internal Properties</label>
        <referenceTo>Internal_Properties__c</referenceTo>
        <relationshipLabel>Domain</relationshipLabel>
        <relationshipName>Domain</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Server_Name__c</fullName>
        <label>Server Name</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CommCareHQ</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>CommCareHQ India</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>cpActiveMobileUsers__c</fullName>
        <label>Domain_cp_active_mobile_users</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>cpIsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Domain_cp_is_active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>is_test__c</fullName>
        <label>Domain_is_test</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>organization__c</fullName>
        <label>Domain_organization</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Domain</label>
    <nameField>
        <label>Domain Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Domain</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Internal_Properties__c.object
<CustomObject>
    <label>Internal Properties</label>
    <nameField>
        <displayFormat>InternalProp={000000}</displayFormat>
        <label>Internal Properties Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Internal Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>area__c</fullName>
        <label>area</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>notes__c</fullName>
        <label>notes</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Server_Name__c</fullName>
        <label>Server Name</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CommCareHQ</fullName>
                    <default>true</default>
                    <label>CommCareHQ</label>
                </value>
                <value>
                    <fullName>CommCareHQ India</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>sub_area__c</fullName>
        <label>sub_area</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/classes/HQAdminReportsProjectMapController.cls
public class HQAdminReportsProjectMapController {

    public String mapAccessToken { get; set; }
    public String mapId { get; set; }
    public List<String> supportedReportsList { get; set; } // we want keep order
    public Map<String, String> supportedReports { get; set; }
    public String reportName { get; set; }

    public HQAdminReportsProjectMapController() {
        this.supportedReportsList = HQAdminReportFactory.getSupportedReportsParamters();
        this.supportedReports = HQAdminReportFactory.getSupportedReportsMap();
        this.reportName = 'projectReportMap';
        this.mapAccessToken = Admin_Reports_Settings__c.getOrgDefaults().DM_Map_Token__c;
        this.mapId = Admin_Reports_Settings__c.getOrgDefaults().DM_Map_Id__c;
    }

    @RemoteAction
    public static List<FacetController.FacetGroup> loadReportMapFacets(String jsonFilters) {
        FacetController facetCtrl = FacetController.buildMapFacetController(jsonFilters);
        facetCtrl.addCurrentFilter('cpIsActive__c', 'true');
        facetCtrl.addCurrentFilter('is_test__c', 'false');
        facetCtrl.loadFacetValues();
        return facetCtrl.getFacets();
    }

    @RemoteAction
    public static HQAdminMapData loadMapData(String currentFilters) {
        FacetController facetCtrl = FacetController.buildMapFacetController(currentFilters);
        return loadCountryData(facetCtrl);
    }

    @RemoteAction
    public static List<HQAdminProjectData> loadTopFiveProjects(String country) {
        List<HQAdminProjectData> countryProjects = new List<HQAdminProjectData>();
        if (String.isNotBlank(country)) {
            List<Domain__c> domains = [SELECT Id, Name, organization__c, Internal_Properties__r.notes__c, Internal_Properties__r.area__c,
                                              Internal_Properties__r.sub_area__c, cpActiveMobileUsers__c, Countries_Picklist__c, Server_Name__c
                                       FROM Domain__c
                                       WHERE is_test__c = 'false' AND cpIsActive__c = true AND Countries_Picklist__c includes (:country) ORDER BY cpActiveMobileUsers__c DESC LIMIT 5];
            for (Domain__c domain : domains) {
                countryProjects.add(new HQAdminProjectData(domain.Id, domain.Name, domain.organization__c, domain.Internal_Properties__r.notes__c,
                                                           domain.Internal_Properties__r.area__c, domain.Internal_Properties__r.sub_area__c,
                                                           domain.Countries_Picklist__c, domain.cpActiveMobileUsers__c, domain.Server_Name__c));
            }
        }
        return countryProjects;
    }

    private static HQAdminMapData loadCountryData(FacetController facetCtrl) {
        Map<String, Integer> countryMap = new Map<String, Integer>();
        Map<String, Integer> userMap = new Map<String, Integer>();

        facetCtrl.addCurrentFilter('cpIsActive__c', 'true');
        facetCtrl.addCurrentFilter('is_test__c', 'false');
        QueryBuilder qb = facetCtrl.getQueryBuilder();
        qb.addColumn('Countries_Wrapper__c').addColumn('Count(Id)').addColumn('Sum(cpActiveMobileUsers__c)').groupBy('Countries_Wrapper__c');
        for (AggregateResult agRes : Database.query(qb.buildQuery())) {
            List<String> nameValues;
            String name = (String) agRes.get('Countries_Wrapper__c');
            if (!String.isBlank(name) && name.contains(',')) {
                name = name.replaceAll(', ', ';');
                nameValues = name.split(',');
            } else {
                nameValues = new List<String> { name };
            }

            for (String val : nameValues) {
                val = val != null ? val.replaceAll(';', ', ') : val;
                Integer oldValue = countryMap.containsKey(val) ? countryMap.get(val) : 0;
                Integer countVal = ((Decimal) (agRes.get('expr0'))).intValue();
                countryMap.put(val, oldValue + countVal);

                oldValue = userMap.containsKey(val) ? userMap.get(val) : 0;
                countVal = ((Decimal) (agRes.get('expr1'))).intValue();
                userMap.put(val, oldValue + countVal);
            }
        }
        qb = facetCtrl.getQueryBuilder().addColumn('Count()');
        Integer activeCount = (Integer) Database.countQuery(qb.buildQuery());
        return new HQAdminMapData(countryMap, userMap, activeCount, qb.buildQuery());
    }

    public class HQAdminProjectData {

        public String sfId { get; set; }
        public String projectName { get; set; }
        public String organization { get; set; }
        public String description { get; set; }
        public String sector { get; set; }
        public String subSector { get; set; }
        public String countries { get; set; }
        public Integer users { get; set; }
        public String serverName { get; set; }

        public HQAdminProjectData(String sfId, String projectName, String organization, String description, String sector, String subSector, String countries, Decimal users, String serverName) {
            this.sfId = sfId;
            this.projectName = projectName;
            this.organization = organization;
            this.description = description;
            this.sector = sector;
            this.subSector = subSector;
            this.countries = countries;
            this.users = Integer.valueOf(users);
            this.serverName = serverName;
        }
    }

    public class HQAdminMapData {

        public Map<String, Integer> countryMap { get; set; }
        public Map<String, Integer> userMap { get; set; }
        public Integer totalActiveProjects { get; set; }
        public String testResponse { get; set; }

        public HQAdminMapData(Map<String, Integer> countryMap, Map<String, Integer> userMap, Integer totalActiveProjects, String testResponse) {
            this.countryMap = countryMap;
            this.userMap = userMap;
            this.totalActiveProjects = totalActiveProjects;
            this.testResponse = testResponse;
        }
    }
}