src/objects/Aggregate_Execution_Efficiency_Snapshot__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Total_Aggregate_Execution_Efficiency__c</fullName>
        <label>Total Aggregate Execution Efficiency</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Aggregate Execution Efficiency Snapshot</label>
    <nameField>
        <label>Aggregate Execution Efficiency Snapshot Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Aggregate Execution Efficiency Snapshots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Corporate_Dashboard_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Corporate Dashboard Settings</label>
</CustomObject>

src/objects/DContract__c.object
<CustomObject>
    <description>Tracks all of Dimagi&apos;s Contracts</description>
    <fields>
        <fullName>Intracompany_Sub_contract__c</fullName>
        <inlineHelpText>For internal accounting. Is this an internal subcontract between Dimagi business units?</inlineHelpText>
        <label>Intracompany Sub-contract</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Total_Amount_of_Contract__c</fullName>
        <label>Total Amount of Contract</label>
        <precision>16</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Global_Metric_Graph__c.object
<CustomObject>
    <label>Global Metric Graphs</label>
    <nameField>
        <label>Graph Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Global Metric Graph</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AggregateExecutionEfficiencySnpJob.cls
public class AggregateExecutionEfficiencySnpJob {

    @future
    public static void createAggregateExecutionEfficiencySnapshot() {
        Corporate_Dashboard_Settings__c corporateDashboardSettings = Corporate_Dashboard_Settings__c.getOrgDefaults();
        List<Global_Metric_Graph__c> aggregateEff = new List<Global_Metric_Graph__c>();
        AggregateResult[] resultContr = [SELECT Efficiency_Owner_BU__r.Name, SUM(Services_Budget__c), SUM(Weighted_Efficiency__c) FROM DContract__c
                                         WHERE (NOT Name LIKE '%internal%') AND Total_Amount_of_Contract__c > 0
                                         AND (NOT Name LIKE '%MOTECH suite%') AND Implementation_Type__c != 'Self Service'
                                         AND Implementation_Type__c != '' AND Efficiency_Owner_BU__c != null
                                         AND Intracompany_Sub_contract__c = 'No' AND Percent_through_SOW_deliverables__c != 100
                                         AND Status__c != 'Complete'
                                         GROUP BY Efficiency_Owner_BU__r.Name ORDER BY Efficiency_Owner_BU__r.Name];

        Decimal totalSumServices = 0;
        Decimal totalSumEff = 0;

        Aggregate_Execution_Efficiency_Snapshot__c snapshot = new Aggregate_Execution_Efficiency_Snapshot__c(Date__c = Date.today());
        SObject sObjSnapshot = (SObject) snapshot;

        if (resultContr.size() > 0) {
            for (AggregateResult ar : resultContr) {
                String currName = (String) ar.get('Name');

                Decimal sumServices = ar.get('expr0') != null ? (Decimal) ar.get('expr0') : 0;
                Decimal sumEff = ar.get('expr0') != null ? (Decimal) ar.get('expr1') : 0;

                totalSumServices += sumServices;
                totalSumEff += sumEff;
                Decimal valuetoSet = 1;

                if (sumServices > 0 && totalSumEff != 0) {
                    valuetoSet = (sumServices / sumEff) * 100.00;
                } else if (sumEff == 0) {
                    valuetoSet = 0;
                }

                String fieldName = (currName + '__c').toLowerCase();
                if (hasSObjectField(fieldName, sObjSnapshot)) {
                    sObjSnapshot.put(fieldName, valuetoSet);
                }
            }
        }

        Decimal totalValue = 1;
        if (totalSumServices > 0 && totalSumEff != 0) {
            totalValue = (totalSumServices / totalSumEff) * 100.00;
        } else if (totalSumEff == 0) {
            totalValue = 0;
        }

        snapshot = (Aggregate_Execution_Efficiency_Snapshot__c) sObjSnapshot;
        snapshot.Total_Aggregate_Execution_Efficiency__c = totalValue;
        insert snapshot;
    }

    private static Boolean hasSObjectField(String fieldName, SObject so) {
        return so.getSobjectType().getDescribe().fields.getMap().keySet().contains(fieldName);
    }
}