src/objects/Area__c.object
<CustomObject>
    <label>Area</label>
    <nameField>
        <label>Area</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Clockify_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Clockify api url and api key.</description>
    <label>Clockify Settings</label>
    <fields>
        <fullName>URL__c</fullName>
        <label>URL</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>XApikey__c</fullName>
        <label>XApikey</label>
        <length>250</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Area__c</fullName>
        <label>Area</label>
        <picklist>
            <picklistValues>
                <fullName>Health</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Poverty and Economic Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Natural Resource Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training &amp; Education Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Logistics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Emergency Response</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Orphans and Vulnerable Children</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DContract__c.object
<CustomObject>
    <description>Tracks all of Dimagi&apos;s Contracts</description>
    <fields>
        <fullName>Area__c</fullName>
        <inlineHelpText>What is the a field this Contract is in. Can select multiple.</inlineHelpText>
        <label>Area</label>
        <picklist>
            <picklistValues>
                <fullName>Agriculture and Food Security</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Economic Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Education and Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Emergency Response</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial Services for the Poor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gender Equality and Women&apos;s Empowerment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Governance and Accountability</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Logistics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Water, Sanitation, &amp; Hygiene</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Poverty and Economic Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Natural Resource Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training &amp; Education Services</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <description>A Dimagi Project</description>
    <fields>
        <fullName>Area__c</fullName>
        <label>Area</label>
        <picklist>
            <picklistValues>
                <fullName>Health</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Poverty and Economic Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Natural Resource Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training &amp; Education Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Logistics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <label>Deployment</label>
    <nameField>
        <label>Deployment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deployments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SFDC_Employee__c.object
<CustomObject>
    <fields>
        <fullName>Email_Address__c</fullName>
        <label>Dimagi Email Address</label>
        <type>Email</type>
    </fields>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Time_Card__c.object
<CustomObject>
    <fields>
        <fullName>Area__c</fullName>
        <label>Area</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <length>180</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client</label>
        <referenceTo>DContract__c</referenceTo>
        <relationshipLabel>Time Cards</relationshipLabel>
        <relationshipName>Time_Cards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Employee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Employee</label>
        <referenceTo>SFDC_Employee__c</referenceTo>
        <relationshipLabel>Time Cards</relationshipLabel>
        <relationshipName>Time_Cards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FTE_hours__c</fullName>
        <label>FTE hours</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total__c</fullName>
        <inlineHelpText>Total Hours</inlineHelpText>
        <label>Total Hours</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Time Card</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Time Card Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ClockifyAPI.cls
public class ClockifyAPI {  
    public String url;
    public Integer totalCount;
    public String XApikey;
    public String startRange{set; get;} 
    public String endRange{set; get;}
    public Clockify_Settings__c clockifySettings ;
    
    public ClockifyAPI(){
        clockifySettings = Clockify_Settings__c.getInstance();
        this.url = clockifySettings.URL__c;
        this.XApikey = clockifySettings.XApikey__c;
        this.totalCount = null;
        this.startRange = null;
        this.endRange = null;       
    }
    public Integer getTotalCount(){
        Boolean success = false;
        Integer requests = 0;
        HTTPResponse response = null;
        while (!success && requests < 3) {
            try {
                response = getCallOutResponseContents(1,1);
                success = true;
            }
            catch(Exception e){                
                requests++;
                System.debug('--requests' + requests);
            }
        }
        try{
            String responseBody = response.getBody().replace('"end":', '"end_Z":');
            ClockifyModel ClockifyData = ClockifyModel.parse(responseBody);
        
            this.totalCount =  ClockifyData.totals[0].entriesCount;
            System.debug('Total Entries Count : ' +this.totalCount);
            return this.totalCount;
        }
        catch(Exception ex){
            StatusLoggerUtils.logError(StatusLoggerUtils.CLOCKIFY_LOGGER, 'Clockify Sync Script', 0, 'Cannot fetch total count. Line: ' + ex.getLineNumber() + ' Message: ' + ex.getMessage());
            return 0;
        }
    }
    public list<Time_Card__c> getTimeEntries(HTTPResponse response){
        list<Time_Card__c> timeCardList = new list<Time_Card__c>();
        try{  
            System.debug('response###' +response);            
            
            String responseBody = response.getBody().replace('"end":', '"end_Z":');
            
            ClockifyModel ClockifyData = ClockifyModel.parse(responseBody);
            System.debug('ClockifyData.timeentries.size()'+ClockifyData.timeentries.size());
        
            Map<String,Id> EmployeeEmailIdMap = getEmployeeEmailIdMap(ClockifyData.timeentries);
            Map<String,Id> ClientNameIdMap = getClientNameIdMap(ClockifyData.timeentries);
            Decimal secondsDuration = 0;
            
            for(Integer i = 0 ; i<ClockifyData.timeentries.size(); i++){
                Time_Card__c tcard = new Time_Card__c();
                if(ClockifyData.timeentries[i].tags.size()>0){
                    if(ClientNameIdMap.containsKey(ClockifyData.timeentries[i].tags[0].name)){
                        tcard.Client__c = ClientNameIdMap.get(ClockifyData.timeentries[i].tags[0].name);
                    }
                }
                if(EmployeeEmailIdMap.containsKey(ClockifyData.timeentries[i].userEmail)){
                    tcard.Employee__c = EmployeeEmailIdMap.get(ClockifyData.timeentries[i].userEmail);
                }else{
                    StatusLoggerUtils.logError(StatusLoggerUtils.CLOCKIFY_LOGGER, clockifyData.timeentries[i].userName, i+1, 'User does not exist'+'-'+clockifyData.timeentries[i].userName);
                }
                tcard.Time_Entry_ID__c = ClockifyData.timeentries[i].x_id;
                tcard.Area__c = ClockifyData.timeentries[i].taskName;
                String timeEntryDesc = ClockifyData.timeentries[i].description;
                tcard.Case__c = String.isNotBlank(timeEntryDesc) ? (timeEntryDesc.length() > 255 ? timeEntryDesc.subString(0, 255) : timeEntryDesc.subString(0, timeEntryDesc.length())) : '';
                tcard.Date__c = Date.valueOf(ClockifyData.timeentries[i].timeInterval.end_Z);
                secondsDuration = ClockifyData.timeentries[i].timeInterval.duration;
                tcard.FTE_hours__c = ClockifyData.timeentries[i].timeInterval.duration != null ? secondsDuration.divide(3600, 2): 0; //seconds to hours
                tcard.Project__c = ClockifyData.timeentries[i].projectName;
                tcard.Task_ID__c = String.valueOf(ClockifyData.timeentries[i].taskId);
                tcard.Total__c = ClockifyData.timeentries[i].timeInterval.duration != null ? secondsDuration.divide(3600, 2): 0; //seconds to hours
                if(tcard.Employee__c != null){
                    timeCardList.add(tcard);
                }else{
                    continue;
                }
            }   
        }catch(Exception e){           
            System.debug('ex--' + e.getStackTraceString());
            System.debug('ex--' + e.getMessage());
            StatusLoggerUtils.logError(StatusLoggerUtils.CLOCKIFY_LOGGER, 'Clockify Sync Script - time entry failed', 0, e.getMessage() + ' ' + e.getStackTraceString());
        }
        return timeCardList;        
    }
    public HTTPResponse getCallOutResponseContents(Integer page, Integer pageSize){
        System.debug('Page , pageSize :' +page+','+pageSize);
        String totalsParam = pageSize == 1 ? 'CALCULATE' : 'EXCLUDE' ;
        Http httpObject = new Http(); 
        HttpRequest request = new HttpRequest();
        HTTPResponse response;

        request.setEndpoint(this.url);        
        request.setHeader('X-Api-Key', this.XApikey);
        request.setHeader('Content-Type', 'application/json');
        request.setHeader('Accept', '*/*');
        request.setHeader('Accept-Encoding', 'gzip, deflate, br');
        request.setHeader('Connection', 'keep-alive');
        request.setMethod('POST');
        request.setBody('{"dateRangeStart": \"'+ startRange +'\", ' +
                        ' "dateRangeEnd": \"'+ endRange +'\", ' +
                        ' "detailedFilter":  '+
                        '        { ' +
                        '            "page":'+page +',' +
                        '            "pageSize":'+pageSize+',' +
                        '            "auditFilter": {'+
                        '                   "withoutProject":'+ false+','+
                        '                   "withoutTask": '+false+','+
                        '                   "durationShorter":' +true+
                        '                            },'+
                        '                       "options": {' + 
                        '                      "totals":  \"'+ totalsParam +'\" ' + 
                        '                                }'+
                        '         }'+
                        '    }');
        request.setTimeout(120000);
       
        try{
            response = httpObject.send(request);
        }catch(Exception e){           
            System.debug('ex--' + e.getStackTraceString());
            System.debug('ex--' + e.getMessage());
            StatusLoggerUtils.logError(StatusLoggerUtils.CLOCKIFY_LOGGER, 'Clockify Sync Script-Send Request', 0, e.getMessage() + ' ' + e.getStackTraceString());
        }
      
        System.debug(response.getBody());
       
        return response;
    }
    private Map<String,Id> getEmployeeEmailIdMap(List<ClockifyModel.timeentries> timeentries){
        Map<String,Id> EmployeeEmailIdMap = new Map<String,Id>();
        List<String> timeEntryEmails = new List<String>();
        for(Integer i = 0; i<timeentries.size(); i++){
            timeEntryEmails.add(timeentries[i].userEmail);
        }
        for(SFDC_Employee__c employee : [SELECT Id , Name, Email_Address__c  FROM SFDC_Employee__c WHERE Email_Address__c IN:timeEntryEmails]){
            EmployeeEmailIdMap.put(employee.Email_Address__c, employee.Id);
        }        
        return EmployeeEmailIdMap;
    }
    private Map<String,Id> getClientNameIdMap(List<ClockifyModel.timeentries> timeentries){
        Map<String,Id> ClientNameIdMap = new Map<String,Id>();
        List<String> tagNames = new List<String>();
        for(Integer i = 0; i<timeentries.size(); i++){
            for(Integer t = 0; t<timeentries[i].tags.size(); t++){
                tagNames.add(timeentries[i].tags[t].name);
            }
        }
        for(DContract__c contract : [SELECT Id , Name FROM DContract__c WHERE Name IN:tagNames]){
            ClientNameIdMap.put(contract.Name, contract.Id);
        }  
        return ClientNameIdMap;
    }
}