src/objects/Area__c.object
<CustomObject>
    <label>Area</label>
    <nameField>
        <label>Area</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BatchDefaultSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Batch Default Settings</label>
    <fields>
        <fullName>Error_Emails__c</fullName>
        <label>Error Emails</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fogbugz_Cases_Fetch_Last_Date__c</fullName>
        <label>Fogbugz Cases Fetch Last Date</label>
        <type>DateTime</type>
    </fields>
</CustomObject>

src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Area__c</fullName>
        <label>Area</label>
        <picklist>
            <picklistValues>
                <fullName>Health</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Poverty and Economic Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Natural Resource Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training &amp; Education Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Logistics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Emergency Response</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Orphans and Vulnerable Children</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DContract__c.object
<CustomObject>
    <description>Tracks all of Dimagi&apos;s Contracts</description>
    <fields>
        <fullName>Area__c</fullName>
        <inlineHelpText>What is the a field this Contract is in. Can select multiple.</inlineHelpText>
        <label>Area</label>
        <picklist>
            <picklistValues>
                <fullName>Agriculture and Food Security</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Economic Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Education and Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Emergency Response</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial Services for the Poor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gender Equality and Women&apos;s Empowerment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Governance and Accountability</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Logistics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Water, Sanitation, &amp; Hygiene</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Poverty and Economic Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Natural Resource Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training &amp; Education Services</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <description>A Dimagi Project</description>
    <fields>
        <fullName>Area__c</fullName>
        <label>Area</label>
        <picklist>
            <picklistValues>
                <fullName>Health</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Poverty and Economic Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Natural Resource Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training &amp; Education Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Logistics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <label>Deployment</label>
    <nameField>
        <label>Deployment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deployments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Time_Card__c.object
<CustomObject>
    <fields>
        <fullName>Area__c</fullName>
        <label>Area</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Number__c</fullName>
        <formula>LEFT(Case__c, FIND(&quot;:&quot;, Case__c) - 1)</formula>
        <label>Case Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <length>180</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client</label>
        <referenceTo>DContract__c</referenceTo>
        <relationshipLabel>Time Cards</relationshipLabel>
        <relationshipName>Time_Cards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FTE_only__c</fullName>
        <defaultValue>false</defaultValue>
        <label>FTE only</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Time Card</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Time Card Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TimeCardCaseUpdateBatch.cls
/**
 * Time card sync batch job chain. TimeCardCaseUpdateBatch (Fetch updated cases from FB and update fields in time cards, like area, project , title or client).
 */
public class TimeCardCaseUpdateBatch implements Database.Batchable<FogBugzCase>, Database.AllowsCallouts, Database.Stateful {

    private DateTime startDateTime;

    public List<FogBugzCase> start(Database.BatchableContext context) {
        FogBugzAPI fogbugzApi = new FogBugzAPI();
        BatchDefaultSettings__c batchSettings = BatchDefaultSettings__c.getOrgDefaults();
        this.startDateTime = DateTime.now();

        DateTime syncDateTime = batchSettings.Fogbugz_Cases_Fetch_Last_Date__c != null ? batchSettings.Fogbugz_Cases_Fetch_Last_Date__c : DateTime.now().addDays(-1);
        List<FogBugzCase> cases = fogbugzApi.getLastUpdatedCases(syncDateTime);

        if (cases != null) {
            batchSettings.Fogbugz_Cases_Fetch_Last_Date__c = this.startDateTime;
            update batchSettings;
            return cases;
        }

        if (!Test.isRunningTest()) {
            EmailHelper.sendEmail(BatchDefaultSettings__c.getOrgDefaults().Error_Emails__c.split(','),
                        'Cannot load updated cases from Fogbugz', 'Cannot fetch updated cases, sync date will not be updated');
        }

        return new List<FogBugzCase>();
    }

    public void execute(Database.BatchableContext context, List<FogBugzCase> scope) {
        List<Time_Card__c> tcList = new List<Time_Card__c>();
        for (FogBugzCase fbCase : scope) {
            if (fbCase.client == null || fbCase.client == '') {
                continue; // we must skip empty clients in cases - less processing, we don't have time cards for such cases
            }

            String dbCaseTitle = fbCase.caseId + ': ' + fbCase.title;
            Integer clientFBId = Integer.valueOf(fbCase.client);
            List<Time_Card__c> timeCardsToUpdate = [SELECT Id, Area__c, Case__c, Project__c, Client__c FROM Time_Card__c WHERE Case_Number__c =: fbCase.caseId AND FTE_only__c = false
                                                        AND (Area__c !=: fbCase.area OR Case__c !=: dbCaseTitle OR Project__c !=: fbCase.project
                                                            OR Client__r.FB_Id__c !=: clientFBId)];


            List<DContract__c> contracts = [SELECT Id, Name FROM DContract__c WHERE FB_Id__c =: clientFBId];
            DContract__c newContract = null;
            if (contracts.size() > 0) {
                newContract = contracts.get(0);
            }

            for (Time_Card__c tc : timeCardsToUpdate) {
                tc.Area__c = fbCase.area;
                tc.Case__c = dbCaseTitle;
                tc.Project__c = fbCase.project;
                if (newContract != null) {
                    tc.Client__c = newContract.Id;
                }
            }

            if (timeCardsToUpdate.size() > 0) {
                tcList.addAll(timeCardsToUpdate);
            }

            if (timeCardsToUpdate.size() > 0 && newContract == null && !Test.isRunningTest()) {
                EmailHelper.sendEmail(BatchDefaultSettings__c.getOrgDefaults().Error_Emails__c.split(','),
                        'Contract Fogbugz Id Mismatch', 'Case Id : ' + fbCase.caseId + ', Cannot find contract with Fogbugz Id : ' + fbCase.client);
            }
        }

        if (tcList.size() > 0) {
            update tcList;
        }
    }

    public void finish(Database.BatchableContext context) {
        if (!Test.isRunningTest()) {
            Database.executeBatch(new TimeCardCalculator());
        }
    }
}