src/objects/BatchDefaultSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Batch Default Settings</label>
    <fields>
        <fullName>Error_Emails__c</fullName>
        <label>Error Emails</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Pipeline_Snapshot__c.object
<CustomObject>
    <description>Used to store historic pipeline information for pipeline reporting. Automatically populated each month.</description>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>DContract__c</referenceTo>
        <relationshipLabel>Pipeline Snapshots</relationshipLabel>
        <relationshipName>Pipeline_Snapshots</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Expense_Travel_Spend__c</fullName>
        <label>Expense &amp; Travel Spend</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Expense_Travel_Spend_for_Period__c</fullName>
        <label>Expense &amp; Travel Spend for Period</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>GS_Net_Income_for_Period__c</fullName>
        <label>GS Net Income for Period</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>GS_Net_Income_for_Period_by_Handover__c</fullName>
        <label>GS Net Income for Period by Handover</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>GS_Net_Income_to_Date_Handover__c</fullName>
        <label>GS Net Income to Date @ Handover</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>GS_Net_Income_to_Date__c</fullName>
        <label>GS Net Income to Date</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>GS_Services_Completed_Handover__c</fullName>
        <label>GS Services Completed @ Handover</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>GS_Services_Completed__c</fullName>
        <label>GS Services Completed</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>GS_Services_Completed_for_Period__c</fullName>
        <label>GS Services Completed for Period</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>GS_Services_Handover_Completed_for_Per__c</fullName>
        <label>GS Services (Handover) Completed for Per</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Month_Date__c</fullName>
        <inlineHelpText>The month of this snapshot.</inlineHelpText>
        <label>Month</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Product_Spend__c</fullName>
        <label>Product Spend</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product_Spend_for_Period__c</fullName>
        <label>Product Spend for Period</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Services_Spend__c</fullName>
        <label>Services Spend</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Services_Spend_for_Period__c</fullName>
        <label>Services Spend for Period</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Source_Type__c</fullName>
        <inlineHelpText>Did this come from a contract or an opportunity?</inlineHelpText>
        <label>Source Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Contract</fullName>
                </value>
                <value>
                    <fullName>Opportunity</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Stage 1 - Connect</fullName>
                    <color>#0B6FCE</color>
                </value>
                <value>
                    <fullName>Stage 2 - Talking</fullName>
                    <color>#78C953</color>
                </value>
                <value>
                    <fullName>Stage 3 - Prospect</fullName>
                    <color>#E27001</color>
                </value>
                <value>
                    <fullName>Stage 4 - Proposal Development</fullName>
                    <color>#DDDDDD</color>
                </value>
                <value>
                    <fullName>Stage 5 - Submitted</fullName>
                    <color>#BBBBBB</color>
                </value>
                <value>
                    <fullName>Stage 6 - In Negotiations</fullName>
                    <color>#999999</color>
                </value>
                <value>
                    <fullName>Closed</fullName>
                    <color>#A845DC</color>
                </value>
                <value>
                    <fullName>Outstanding Contracted</fullName>
                    <color>#F3D904</color>
                </value>
                <value>
                    <fullName>Total</fullName>
                    <color>#A53711</color>
                </value>
                <value>
                    <fullName>Cash on Hand</fullName>
                    <color>#009900</color>
                </value>
                <value>
                    <fullName>Predicted pipeline</fullName>
                    <color>#0B6FCE</color>
                </value>
                <value>
                    <fullName>Core run rate</fullName>
                    <color>#FF0000</color>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Calculated_Costs__c</fullName>
        <label>Total Calculated Costs</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Calculated_Costs_for_Period__c</fullName>
        <label>Total Calculated Costs for Period</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Work_Completed__c</fullName>
        <label>% of Work Completed</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Work_Completed_for_Period__c</fullName>
        <label>% of Work Completed for Period</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <label>Pipeline Snapshot</label>
    <nameField>
        <label>Pipeline Snapshot Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pipeline Snapshots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ForPeriodCalcSnapshotBatch.cls
/**
 * Calculates for period fields in Pipeline Snapshot custom object.
 */
public class ForPeriodCalcSnapshotBatch implements Database.Batchable<Pipeline_Snapshot__c>, Database.Stateful {

    private Boolean forTotal;
    private Date customDate;

    public ForPeriodCalcSnapshotBatch(Boolean forTotal){
        this.forTotal = forTotal;
        this.customDate = null;
    }

    public List<Pipeline_Snapshot__c> start(Database.BatchableContext context) {
        List<Pipeline_Snapshot__c> snaps = new List<Pipeline_Snapshot__c>();
        return getContractPS();
    }

    public void execute(Database.BatchableContext context, List<Pipeline_Snapshot__c> snapshots) {
        calculateContractForPeriod(snapshots);
    }

    public void finish(Database.BatchableContext context) {
        if (this.forTotal == false) {
            Database.executeBatch(new ForPeriodCalcSnapshotBatch(true), 50);
        }
    }

    public void setCustomDate(Date customDate) {
        this.customDate = customDate;
    }

    private void calculateContractForPeriod(List<Pipeline_Snapshot__c> snapshots) {
        System.debug('snapshots: ' + snapshots.size());
        List<Pipeline_Snapshot__c> toUpdate = new List<Pipeline_Snapshot__c>();
        try {
            Map<Id, Pipeline_Snapshot__c> oldSnapshots = SnapshotHelper.getOldSnapshots(snapshots, forTotal);
            for (Pipeline_Snapshot__c sn : snapshots) {
                Pipeline_Snapshot__c oldSn = new Pipeline_Snapshot__c();
                if (sn.Contract__c != null && oldSnapshots.containsKey(sn.Contract__c)) {
                    oldSn = oldSnapshots.get(sn.Contract__c);
                }
                sn = SnapshotHelper.calculateForPeriod(sn, oldSn);
                toUpdate.add(sn);
            }
            update toUpdate;
        } catch(Exception ex) {
            System.debug('ERROR:' + ex);
            if (!Test.isRunningTest()) {
                BatchDefaultSettings__c settings = BatchDefaultSettings__c.getOrgDefaults();
                EmailHelper.sendEmailFromException(settings.Error_Emails__c.split(','), 'For Period calculation error', 'Period calculation error', ex);
            }
        }
    }

    private List<Pipeline_Snapshot__c> getContractPS() {
        if (this.forTotal == false) {
            return [SELECT Id, Contract__c, Work_Completed__c, Services_Spend__c, Expense_Travel_Spend__c, Product_Spend__c, Total_Calculated_Costs__c, GS_Services_Completed__c,
                    GS_Services_Completed_Handover__c, GS_Net_Income_to_Date__c, GS_Net_Income_to_Date_Handover__c,
                    Work_Completed_for_Period__c, Expense_Travel_Spend_for_Period__c, GS_Net_Income_for_Period__c, GS_Net_Income_for_Period_by_Handover__c,
                    GS_Services_Handover_Completed_for_Per__c, GS_Services_Completed_for_Period__c, Product_Spend_for_Period__c, Services_Spend_for_Period__c,
                    Total_Calculated_Costs_for_Period__c, Month_Date__c
                    FROM Pipeline_Snapshot__c WHERE CreatedDate >= YESTERDAY AND Stage__c != 'Total' AND Source_Type__c = 'Contract'];
        }
        return [SELECT Id, Contract__c, Work_Completed__c, Services_Spend__c, Expense_Travel_Spend__c, Product_Spend__c, Total_Calculated_Costs__c, GS_Services_Completed__c,
                    GS_Services_Completed_Handover__c, GS_Net_Income_to_Date__c, GS_Net_Income_to_Date_Handover__c,
                    Work_Completed_for_Period__c, Expense_Travel_Spend_for_Period__c, GS_Net_Income_for_Period__c, GS_Net_Income_for_Period_by_Handover__c,
                    GS_Services_Handover_Completed_for_Per__c, GS_Services_Completed_for_Period__c, Product_Spend_for_Period__c, Services_Spend_for_Period__c,
                    Total_Calculated_Costs_for_Period__c, Month_Date__c
                    FROM Pipeline_Snapshot__c WHERE CreatedDate >= YESTERDAY AND Stage__c = 'Total' AND Source_Type__c = 'Contract'];
    }
}