src/objects/BatchDefaultSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Batch Default Settings</label>
    <fields>
        <fullName>Error_Emails__c</fullName>
        <label>Error Emails</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Temporary field: Used to edit the account field once a contract has been activated.</inlineHelpText>
        <label>New Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contract_End_Date__c</fullName>
        <inlineHelpText>The date the project actually ends</inlineHelpText>
        <label>Contract End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Contract_Start_Date__c</fullName>
        <inlineHelpText>The date the contract actually starts.</inlineHelpText>
        <label>Contract Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Funder_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Who is actually supplying the funding for this (ex. USAID)</inlineHelpText>
        <label>Funder Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Funding Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Intracompany_Sub_contract__c</fullName>
        <inlineHelpText>For internal accounting. Is this an internal subcontract between Dimagi business units (Y/N)</inlineHelpText>
        <label>Intracompany Sub-contract?</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Total_Amount_REMAINING__c</fullName>
        <formula>IF( Total_Amount_of_Contract__c -  Services_Income__c &lt; 0, 0, Total_Amount_of_Contract__c -  Services_Income__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Amount REMAINING</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Amount_of_Contract__c</fullName>
        <label>Total Amount of Contract</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Direct_Costs_Expenses__c</fullName>
        <label>Total Direct Costs Expense SPEND</label>
        <precision>16</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DContract__c.object
<CustomObject>
    <description>Tracks all of Dimagi&apos;s Contracts</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Which account is the contract signed with.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>DContracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contract_End_Date__c</fullName>
        <inlineHelpText>When the project actually ends.</inlineHelpText>
        <label>Contract End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Contract_Start_Date__c</fullName>
        <inlineHelpText>When the contract actually starts.</inlineHelpText>
        <label>Contract Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Contracting_Business_Unit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Business Unit that signed the contract with the customer (DSA, DSI, Inc).</inlineHelpText>
        <label>Contracting Business Unit</label>
        <referenceTo>Business_Unit__c</referenceTo>
        <relationshipName>Implementing_Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_of_Contract_Execution__c</fullName>
        <label>Date of Contract Execution</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Funder_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Which organization is providing the funding</inlineHelpText>
        <label>Funding Source</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>FundingContracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Intracompany_Sub_contract__c</fullName>
        <inlineHelpText>For internal accounting. Is this an internal subcontract between Dimagi business units?</inlineHelpText>
        <label>Intracompany Sub-contract</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Total_Amount_REMAINING__c</fullName>
        <label>Total Amount REMAINING</label>
        <precision>16</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Amount_of_Contract__c</fullName>
        <label>Total Amount of Contract</label>
        <precision>16</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Direct_Costs_Expenses__c</fullName>
        <label>Total Direct Costs Expenses</label>
        <precision>16</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Pipeline_Snapshot__c.object
<CustomObject>
    <description>Used to store historic pipeline information for pipeline reporting. Automatically populated each month.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Opportunity_Snapshots</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Amount_Minus_Expense_Income__c</fullName>
        <label>Amount Minus Expense Income</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <inlineHelpText>Amount at the time of the snapshot.

For Opportuity:  Amount = Opp Amount
For Closed Contract: Amount = Total Amount of Contract
For Outstanding Contract: Total Amount Remaining</inlineHelpText>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Billing_Deficit__c</fullName>
        <label>Billing Deficit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Billing_efficiency__c</fullName>
        <label>Billing efficiency %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Contract_End_Date__c</fullName>
        <label>Contract End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Contract_Execution_Date__c</fullName>
        <label>Contract Execution Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Contract_Expense_Income__c</fullName>
        <label>Contract Expense Income</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Contract_Start_Date__c</fullName>
        <label>Contract Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Contract_Total_Non_Expense_Income_BUDGET__c</fullName>
        <label>Contract Total Non Expense Income BUDGET</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Contract_Total_Non_Expense_Income_Rmg__c</fullName>
        <label>Contract Total Non Expense Income Rmg</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>DContract__c</referenceTo>
        <relationshipLabel>Pipeline Snapshots</relationshipLabel>
        <relationshipName>Pipeline_Snapshots</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Duration_months__c</fullName>
        <inlineHelpText>The Duration at the time the snapshot was taken.

Opps: entered on opportunity manually
Contracts: End Date - Start Date</inlineHelpText>
        <label>Duration (months)</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Expected_Buffer__c</fullName>
        <label>Expected % Buffer</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Funder_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Funding Source</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Opportunity_Snapshots1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GS_Execution_Budget__c</fullName>
        <label>GS Project Services Budget</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>GS_Net_Income_to_Date_Handover__c</fullName>
        <label>GS Net Income to Date @ Handover</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>GS_Net_Income_to_Date__c</fullName>
        <label>GS Net Income to Date</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>GS_Project_Services_Budget_Handoff__c</fullName>
        <formula>Contract__r.GS_Project_Services_Budget_Handoff__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>GS Project Services Budget @ Handoff</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>GS_Services_Completed_Handover__c</fullName>
        <label>GS Services Completed @ Handover</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>GS_Services_Completed__c</fullName>
        <label>GS Services Completed</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Intracompany_Sub_contract__c</fullName>
        <label>Intracompany Sub-contract</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Invoiced__c</fullName>
        <label>% Invoiced</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Month_Date__c</fullName>
        <inlineHelpText>The month of this snapshot.</inlineHelpText>
        <label>Month</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Product_Spend__c</fullName>
        <label>Product Spend</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Services_Spend__c</fullName>
        <label>Services Spend</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Source_Type__c</fullName>
        <inlineHelpText>Did this come from a contract or an opportunity?</inlineHelpText>
        <label>Source Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Contract</fullName>
                </value>
                <value>
                    <fullName>Opportunity</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Amount_REMAINING__c</fullName>
        <inlineHelpText>Maps to Total Amount REMAINING on the contract object.</inlineHelpText>
        <label>Contract Amount REMAINING</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Work_Completed__c</fullName>
        <label>% of Work Completed</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <label>Pipeline Snapshot</label>
    <nameField>
        <label>Pipeline Snapshot Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pipeline Snapshots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ContractPipelineSnapshotBatch.cls
public class ContractPipelineSnapshotBatch implements Database.Batchable<DContract__c>, Database.Stateful {

    private Date runDate;
    private Date monthStart;

    public ContractPipelineSnapshotBatch() {
        this(Date.today());
    }

    public ContractPipelineSnapshotBatch(Date runDate) {
        this.runDate = runDate;
        this.monthStart = this.runDate.toStartOfMonth();
    }

    public List<DContract__c> start(Database.BatchableContext BC) {
        List<Pipeline_Snapshot__c> psTORemove = [SELECT Id FROM Pipeline_Snapshot__c WHERE Month_Date__c =: this.runDate AND Source_Type__c = 'Contract'];
        if (psTORemove.size() > 0) {
            delete psTORemove;
        }

        return [SELECT Id, Name, Invoiced__c, Percent_through_SOW_deliverables__c, Account_ID__c, Total_Amount_REMAINING__c,Services_Spend__c, Funder_Account__c,
                Billing_Deficit__c, Billing_efficiency__c, Contract_End_Date__c, Date_of_Contract_Execution__c, Contract_Start_Date__c, GS_Services_Completed__c,
                Total_Non_Expense_Income_Remaining__c, Country_Text__c, Duration_months__c, Expected_Buffer__c, Direct_Costs_Total_Expenses__c,
                GS_Net_Income_to_Date__c, GS_Net_Income_to_Date_Handover__c, GS_Execution_Budget__c, GS_Project_Services_Budget_Handoff__c,
                GS_Services_Completed_Handover__c, Intracompany_Sub_contract__c, Contracting_Business_Unit__c, Product_Text__c, Product_Spend__c,
                Total_Costs__c, Total_Direct_Costs_Expenses__c, Total_Non_Expense_Income_BUDGET__c, OwnerId, Status__c, Total_Amount_of_Contract__c
                FROM DContract__c
                WHERE Status__c = 'Active' OR (Date_of_Contract_Execution__c >=: this.monthStart AND Date_of_Contract_Execution__c <=: this.runDate)];
    }

    public void execute(Database.BatchableContext BC, List<DContract__c> scope) {
        List<Pipeline_Snapshot__c> newSnapshots = new List<Pipeline_Snapshot__c>();
        for (DContract__c dContract : scope) {
            String nameSuffix = ' - ' + this.runDate.month() + '/' + this.runDate.year();
            String nameSuffixTotal = nameSuffix + ' - Total';
            String namePrefix = dContract.Name;
            String namePrefixTotal = dContract.Name;

            if (namePrefix != null && namePrefix.length() + nameSuffix.length() > 80) {
                Integer charsToCut = namePrefix.length() - (namePrefix.length() + nameSuffix.length() - 80);
                namePrefix = namePrefix.subString(0, charsToCut);
            }

            if (namePrefixTotal != null && namePrefixTotal.length() + nameSuffixTotal.length() > 80) {
                Integer charsToCut = namePrefixTotal.length() - (namePrefixTotal.length() + nameSuffixTotal.length() - 80);
                namePrefixTotal = namePrefix.subString(0, charsToCut);
            }

            if (dContract.Status__c == 'Active') {
                Pipeline_Snapshot__c newPs = buildSnapshot(dContract, namePrefix + nameSuffix, this.runDate, 'Outstanding Contracted');
                Pipeline_Snapshot__c newPsTotal = buildSnapshot(dContract, namePrefixTotal + nameSuffixTotal, this.runDate, 'Total');

                // set custom outstanding fields
                newPs.Invoiced__c = dContract.Invoiced__c;
                newPs.Billing_efficiency__c = dContract.Billing_efficiency__c;
                newPs.Amount__c = dContract.Total_Amount_REMAINING__c;
                newPs.Amount_Minus_Expense_Income__c = dContract.Total_Non_Expense_Income_Remaining__c;
                // set custom total fields
                newPsTotal.Invoiced__c = dContract.Invoiced__c;
                newPsTotal.Billing_efficiency__c = dContract.Billing_efficiency__c;
                newPsTotal.Contract_Expense_Income__c = dContract.Total_Direct_Costs_Expenses__c;
                newPsTotal.Amount__c = dContract.Total_Amount_REMAINING__c;
                newPsTotal.Amount_Minus_Expense_Income__c = dContract.Total_Non_Expense_Income_Remaining__c;


                newPs.recalculateFormulas();
                newPsTotal.recalculateFormulas();
                newPs = SnapshotHelper.calculateForPeriod(newPs, SnapshotHelper.getOldSnapshots(newPs, false));
                newPsTotal = SnapshotHelper.calculateForPeriod(newPsTotal, SnapshotHelper.getOldSnapshots(newPsTotal, true));
                newSnapshots.add(newPs);
                newSnapshots.add(newPsTotal);
            }

            if (dContract.Date_of_Contract_Execution__c >= this.monthStart && dContract.Date_of_Contract_Execution__c <= this.runDate) {
                Pipeline_Snapshot__c newPs = buildSnapshot(dContract, namePrefix + nameSuffix, this.runDate, 'Closed');

                // set custom closed fields
                newPs.Amount__c = dContract.Total_Amount_of_Contract__c;
                newPs.Amount_Minus_Expense_Income__c = dContract.Total_Non_Expense_Income_BUDGET__c;
                newPs.Contract_Expense_Income__c = dContract.Total_Direct_Costs_Expenses__c;
                newPs.Contract_Total_Non_Expense_Income_BUDGET__c = dContract.Total_Non_Expense_Income_BUDGET__c;
                newPs.OwnerId = dContract.OwnerId;

                newPs.recalculateFormulas();
                newPs = SnapshotHelper.calculateForPeriod(newPs, SnapshotHelper.getOldSnapshots(newPs, false));
                newSnapshots.add(newPs);
            }
        }

        if (newSnapshots.size() > 0) {
            insert newSnapshots;
        }
    }

    public void finish(Database.BatchableContext BC) {
        if (!Test.isRunningTest()) {
            // TODO : email notification to users wit emails from settings !!!
            EmailHelper.sendEmail(BatchDefaultSettings__c.getOrgDefaults().Error_Emails__c.split(','), 'Contract Pipeline Snapshots', 'Job finished : ' + Date.today() + ' created for : ' + this.runDate);
        }
    }

    private Pipeline_Snapshot__c buildSnapshot(DContract__c dContract, String name, Date monthDate, String stageName) {
        return new Pipeline_Snapshot__c (
                        Work_Completed__c = dContract.Percent_through_SOW_deliverables__c,
                        Account__c = dContract.Account_ID__c,
                        Billing_Deficit__c = dContract.Billing_Deficit__c,
                        Contract__c = dContract.Id,
                        Total_Amount_REMAINING__c = dContract.Total_Amount_REMAINING__c,
                        Contract_End_Date__c = dContract.Contract_End_Date__c,
                        Contract_Execution_Date__c = dContract.Date_of_Contract_Execution__c,
                        Contract_Start_Date__c = dContract.Contract_Start_Date__c,
                        Contract_Total_Non_Expense_Income_Rmg__c = dContract.Total_Non_Expense_Income_Remaining__c,
                        Country__c = dContract.Country_Text__c,
                        Duration_months__c = dContract.Duration_months__c,
                        Expected_Buffer__c = dContract.Expected_Buffer__c,
                        Expense_Travel_Spend__c = dContract.Direct_Costs_Total_Expenses__c,
                        Funder_Account__c = dContract.Funder_Account__c,
                        GS_Net_Income_to_Date__c = dContract.GS_Net_Income_to_Date__c,
                        GS_Net_Income_to_Date_Handover__c = dContract.GS_Net_Income_to_Date_Handover__c,
                        GS_Execution_Budget__c = dContract.GS_Execution_Budget__c,
                        GS_Project_Services_Budget_Handoff_Cp__c = dContract.GS_Project_Services_Budget_Handoff__c,
                        GS_Services_Completed__c = dContract.GS_Services_Completed__c,
                        GS_Services_Completed_Handover__c = dContract.GS_Services_Completed_Handover__c,
                        Intracompany_Sub_contract__c = dContract.Intracompany_Sub_contract__c,
                        Owning_Entity__c = dContract.Contracting_Business_Unit__c,
                        Products__c = dContract.Product_Text__c,
                        Product_Spend__c = dContract.Product_Spend__c,
                        Services_Spend__c = dContract.Services_Spend__c,
                        Total_Calculated_Costs__c = dContract.Total_Costs__c,
                        Month_Date__c = monthDate,
                        Probability__c = 100,
                        Source_Type__c = 'Contract',
                        Stage__c = stageName,
                        Name = name
                    );
    }
}