src/objects/BatchDefaultSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Batch Default Settings</label>
    <fields>
        <fullName>Error_Emails__c</fullName>
        <label>Error Emails</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Dimagi_Zendesk_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Plan_List__c</fullName>
        <label>Plan List</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Dimagi Zendesk Settings</label>
</CustomObject>

src/objects/Zendesk_Tickets_Statistics__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Number_of_Tickets_Created__c</fullName>
        <label>Number of Tickets Created</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Plan__c</fullName>
        <label>Plan</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Zendesk Tickets Statistic</label>
    <nameField>
        <label>Zendesk Tickets Statistics Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zendesk Tickets Statistics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ZendeskSynchronizer.cls
/**
 * Zendesk synchronizer class used for fetch and add custom data from zendesk API.
 */
public class ZendeskSynchronizer {

    /**
     * Fetch and add records with # of tickets created in given motnh data from zendesk API. Created data used in Global Metrics graphs.
     */
    public static void fetchZendeskTicketCount(Integer year, Integer month) {
        Dimagi_Zendesk_Settings__c settings = Dimagi_Zendesk_Settings__c.getOrgDefaults();
        ZendeskAPI zendeskAPI = new ZendeskAPI(settings);
        List<String> softwarePlans = settings.Plan_List__c != null ? settings.Plan_List__c.split(',') : new List<String>();

        Date monthDate = Date.newInstance(year, month, Date.daysInMonth(year, month));
        Date startDate = Date.newInstance(year, month, 1).addDays(-1);
        Date endDate = Date.newInstance(year, month, Date.daysInMonth(year, month)).addDays(1);

        String queryString = 'type:ticket%20' +
                             'created>' + startDate.year() + '-' + startDate.month() + '-' + startDate.day() + '%20' +
                             'created<' + endDate.year() + '-' + endDate.month() + '-' + endDate.day() + '%20';

        List<Zendesk_Tickets_Statistics__c> newData = new List<Zendesk_Tickets_Statistics__c>();

        try {
            for (String plan : softwarePlans) {
                HttpResponse response = zendeskAPI.httpGet(queryString + 'plan:' + plan);
                JSONParser parser = JSON.createParser(SFUtils.replaceCountWords(response.getBody()));
                ZendeskModels.ZendeskSearchModel planData = (ZendeskModels.ZendeskSearchModel) parser.readValueAs(ZendeskModels.ZendeskSearchModel.class);
                newData.add(new Zendesk_Tickets_Statistics__c(Plan__c = plan, Number_of_Tickets_Created__c = planData.x_count, Date__c = monthDate));
            }

            if (newData.size() > 0) {
                insert newData;
                StatusLoggerUtils.logInfo(StatusLoggerUtils.ZENDESK_LOGGER, 'Zendesk # of ticekts created', newData.size(), 'Finished Zendesk Sync');
            }
        } catch (Exception e) {
            System.debug('Zendesk Error : ' + e.getMessage());
            StatusLoggerUtils.logError(StatusLoggerUtils.ZENDESK_LOGGER, 'Cannot fetch Zendesk # of tickets created', 0, e.getMessage());
        }

        if (!Test.isRunningTest()) {
            StatusLoggerUtils.sendLog(StatusLoggerUtils.ZENDESK_LOGGER,  BatchDefaultSettings__c.getOrgDefaults().Error_Emails__c.split(','));
        }
    }

    /**
     * @future method for fetchZendeskTicketCount.
     */
    @future(callout=true)
    public static void fetchZendeskTicketCountFuture(Integer year, Integer month) {
        fetchZendeskTicketCount(year, month);
    }
}