src/objects/BatchDefaultSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Batch Default Settings</label>
    <fields>
        <fullName>Error_Emails__c</fullName>
        <label>Error Emails</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/DContract__c.object
<CustomObject>
    <description>Tracks all of Dimagi&apos;s Contracts</description>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FTE_Data_Record__c.object
<CustomObject>
    <label>FTE Data Record</label>
    <nameField>
        <displayFormat>FTE_Data-{0000000000}</displayFormat>
        <label>FTE_Data_Upload Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FTE Data Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>DContract__c</referenceTo>
        <relationshipLabel>FTE Data Records</relationshipLabel>
        <relationshipName>FTE_Data_Records</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Employee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Employee</label>
        <referenceTo>SFDC_Employee__c</referenceTo>
        <relationshipLabel>FTE Data Records</relationshipLabel>
        <relationshipName>FTE_Data_Records</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Month_10__c</fullName>
        <label>October</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Month_11__c</fullName>
        <label>November</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Month_12__c</fullName>
        <label>December</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Month_1__c</fullName>
        <label>January</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Month_2__c</fullName>
        <label>February</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Month_3__c</fullName>
        <label>March</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Month_4__c</fullName>
        <label>April</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Month_5__c</fullName>
        <label>May</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Month_6__c</fullName>
        <label>June</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Month_7__c</fullName>
        <label>July</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Month_8__c</fullName>
        <label>August</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Month_9__c</fullName>
        <label>September</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

src/objects/FTE_Work_Card__c.object
<CustomObject>
    <fields>
        <fullName>Employee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Employee</label>
        <referenceTo>SFDC_Employee__c</referenceTo>
        <relationshipLabel>FTE Work Cards</relationshipLabel>
        <relationshipName>FTE_Work_Cards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Month_10__c</fullName>
        <label>Month 10</label>
        <precision>16</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Month_11__c</fullName>
        <label>Month 11</label>
        <precision>16</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Month_12__c</fullName>
        <label>Month 12</label>
        <precision>16</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Month_1__c</fullName>
        <label>Month 1</label>
        <precision>16</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Month_2__c</fullName>
        <label>Month 2</label>
        <precision>16</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Month_3__c</fullName>
        <label>Month 3</label>
        <precision>16</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Month_4__c</fullName>
        <label>Month 4</label>
        <precision>16</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Month_5__c</fullName>
        <label>Month 5</label>
        <precision>16</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Month_6__c</fullName>
        <label>Month 6</label>
        <precision>16</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Month_7__c</fullName>
        <label>Month 7</label>
        <precision>16</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Month_8__c</fullName>
        <label>Month 8</label>
        <precision>16</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Month_9__c</fullName>
        <label>Month 9</label>
        <precision>16</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Hours__c</fullName>
        <label>Total Hours</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total__c</fullName>
        <label>Total</label>
        <precision>16</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>FTE Work Card</label>
    <nameField>
        <displayFormat>Work-Card-{00000}</displayFormat>
        <label>FTE Work Card Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FTE Work Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SFDC_Employee__c.object
<CustomObject>
    <fields>
        <fullName>Employee_Status__c</fullName>
        <label>Employee Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LOA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Terminated</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Employee_Type__c</fullName>
        <label>Employee Type</label>
        <picklist>
            <picklistValues>
                <fullName>Employee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contractor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>External Contractor</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Hire_Date__c</fullName>
        <label>Hire Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Termination_Date__c</fullName>
        <label>Termination Date</label>
        <type>Date</type>
    </fields>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FTEGenerateEmployeesWorkCardBatch.cls
/**
 * Batch job for createing FTE Work Cards for FTE Employee List View.
 */
public without sharing class FTEGenerateEmployeesWorkCardBatch implements Database.Batchable<FTEEmployeeWrapper>, Database.Stateful {

    private Map<Integer, List<FTE_Work_Card__c>> workCardsMap;
    private Set<Id> dataSet;

    public FTEGenerateEmployeesWorkCardBatch() {
        this(null);
    }

    public FTEGenerateEmployeesWorkCardBatch(Set<Id> dataSet) {
        this.dataSet = dataSet;
    }

    public List<FTEEmployeeWrapper> start(Database.BatchableContext BC) {
        List<FTEEmployeeWrapper> result = new List<FTEEmployeeWrapper>();

        try {
            if (this.dataSet == null || this.dataSet.size() == 0) {
                result = generateWrapperList([SELECT Id, Name, Hire_Date__c, Termination_Date__c, Employee_Type__c, Employee_Status__c
                                              FROM SFDC_Employee__c ORDER BY Name]);
                List<FTE_Work_Card__c> oldCards = [SELECT Id FROM FTE_Work_Card__c];
                if (oldCards.size() > 0) {
                    delete oldCards;
                }
            } else if (this.dataSet != null && this.dataSet.size() > 0) {
                for (FTE_Work_Card__c emplWorkCard : [SELECT Employee__c, Year__c FROM FTE_Work_Card__c WHERE Id IN: this.dataSet]) {
                    result.add(new FTEEmployeeWrapper(emplWorkCard.Employee__c, Integer.valueOf(emplWorkCard.Year__c)));
                }
            }

        } catch (Exception ex) {
            if (!Test.isRunningTest()) {
                EmailHelper.sendEmailFromException(BatchDefaultSettings__c.getOrgDefaults().Error_Emails__c.split(','), 'Cannot calculate Employee FTE Work Card', 'Error : ', ex);
            }
        }

        return result;
    }

    public void execute(Database.BatchableContext BC, List<FTEEmployeeWrapper> scope) {
        for (FTEEmployeeWrapper employee : scope) {
            List<FTE_Work_Card__c> employeeWorkCards = [SELECT Id FROM FTE_Work_Card__c WHERE Employee__c =: employee.employeeId AND Year__c =: employee.year];
            FTE_Work_Card__c employeeWorkCard = new FTE_Work_Card__c(Employee__c = employee.employeeId, Year__c = employee.year, Month_1__c = 0,
                                                        Month_2__c = 0, Month_3__c = 0, Month_4__c = 0, Month_5__c = 0, Month_6__c = 0,
                                                        Month_7__c = 0, Month_8__c = 0, Month_9__c = 0, Month_10__c = 0, Month_11__c = 0,
                                                        Month_12__c = 0, Total__c = 0, Total_Hours__c = 0);
            if (employeeWorkCards.size() > 0) {
                employeeWorkCard.Id = employeeWorkCards.get(0).Id;
            }
            SObject sObj = (SObject) employeeWorkCard;

            Map<Id, FTE_Data_Record__c> contractAllocationMapping = new Map<Id, FTE_Data_Record__c>();
            for (FTE_Data_Record__c futureTemplate : [SELECT Contract__c, Employee__c, Month_1__c, Month_2__c, Month_3__c, Month_4__c, Month_5__c, Month_6__c,
                                                       Month_7__c, Month_8__c, Month_9__c, Month_10__c, Month_11__c, Month_12__c
                                                       FROM FTE_Data_Record__c
                                                       WHERE Employee__c =: employee.employeeId AND Year__c =: employee.year AND Contract__r.FTE_Tracker__c = 'Yes']) {
                contractAllocationMapping.put(futureTemplate.Contract__c, futureTemplate);
            }

            FTEDataManager dataManager = new FTEDataManager(employee.year, employee.employeeId, true);
            dataManager.loadEmployeeTime();
            dataManager.loadTemplateTime();

            Decimal totalValue = 0;
            Decimal[] timeArray = new Decimal [] {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
            for (Id contractId : dataManager.assignedMap.keySet()) {
                FTEEmployeeTime emplTime = dataManager.assignedMap.get(contractId);
                for (Integer month = 1; month <= 12; month++) {
                    Decimal templateTime = (emplTime.templateArray[month - 1] != -1 ? emplTime.templateArray[month - 1] * 8 : -1);
                    Decimal loggedTime = emplTime.hoursArray[month - 1];
                    Decimal finalResult = 0;

                    if (templateTime != -1 && templateTime > loggedTime) {
                        finalResult = templateTime;
                        sObj.put(FTETrackerHelper.getFieldTemplateFutureName(month), true); // UI metadata, increase performance
                    } else if (templateTime != -1 && templateTime == loggedTime) {
                        finalResult = loggedTime;
                        sObj.put(FTETrackerHelper.getFieldTemplateBlockedName(month), true); // UI metadata increase performance
                    } else {
                        finalResult = loggedTime;
                    }
                    timeArray[month - 1] += finalResult;
                    totalValue += finalResult;
                }
            }
            employeeWorkCard.Total_Hours__c = totalValue;
            employeeWorkCard.Total__c = FTETrackerHelper.roundtoDays(totalValue);
            // Merge temlate data and real data
            for (Integer month = 1; month <= 12; month++) {
                sObj.put(FTETrackerHelper.getFieldName(month), FTETrackerHelper.roundtoDays(timeArray[month - 1]));
            }
            upsert employeeWorkCard;
        }
    }

    public void finish(Database.BatchableContext BC) {
    }

    private List<FTEEmployeeWrapper> generateWrapperList(List<SFDC_Employee__c> employees) {
        List<FTEEmployeeWrapper> result = new List<FTEEmployeeWrapper>();
        Integer currentYear = Date.today().year();
        Integer twoYearsAhead = currentYear + 2;
        Integer nextYear = currentYear + 1;
        Integer oneYearAgo = currentYear - 1;

        for (SFDC_Employee__c emplRec : employees) {
            if (emplRec.Employee_Status__c == 'Active' && (emplRec.Hire_Date__c != null && emplRec.Hire_Date__c.year() <= twoYearsAhead)
                    && emplRec.Termination_Date__c == null) {
                result.add(new FTEEmployeeWrapper(emplRec.Id, twoYearsAhead));
            }

            if (emplRec.Employee_Status__c == 'Active' && (emplRec.Hire_Date__c != null && emplRec.Hire_Date__c.year() <= nextYear)
                    && emplRec.Termination_Date__c == null) {
                result.add(new FTEEmployeeWrapper(emplRec.Id, nextYear));
            }

            if ((emplRec.Employee_Status__c == 'Active' && (emplRec.Hire_Date__c != null && emplRec.Hire_Date__c.year() <= currentYear))
                || (emplRec.Termination_Date__c != null && emplRec.Termination_Date__c.year() == currentYear)) {
                result.add(new FTEEmployeeWrapper(emplRec.Id, currentYear));
            }

            if ((emplRec.Hire_Date__c != null && emplRec.Hire_Date__c.year() <= oneYearAgo)
                || (emplRec.Termination_Date__c != null && emplRec.Termination_Date__c.year() == oneYearAgo)) {
                result.add(new FTEEmployeeWrapper(emplRec.Id, oneYearAgo));
            }
        }

        return result;
    }
}