src/objects/BatchDefaultSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Batch Default Settings</label>
    <fields>
        <fullName>Error_Emails__c</fullName>
        <label>Error Emails</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Days_w_o_Activity__c</fullName>
        <description>Returns the # of days since last activity on Contact</description>
        <formula>TODAY() - LastActivityDate</formula>
        <label>Days w/o Activity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Follow_up_Date__c</fullName>
        <inlineHelpText>Use this to set a specific date you&apos;d like the follow-up report to remind you to reach back out.</inlineHelpText>
        <label>Follow-up Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Hubspot_Next_Activity_Date__c</fullName>
        <description>Next activity date from Hubspot. Oddly this is a text field from Hubspot, not a date.</description>
        <inlineHelpText>Next activity date from Hubspot. Oddly this is a text field from Hubspot, not a date.</inlineHelpText>
        <label>Hubspot - Next Activity Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Channel_Response__c</fullName>
        <description>What Channel is the Opportunity (Sales, B2B, Pre-Bid, Other Competitive Bid, etc.)? 
See https://confluence.dimagi.com/display/BD/BD+Channels</description>
        <inlineHelpText>What Channel is the Opportunity (Sales, B2B, Pre-Bid, Other Competitive Bid, etc.)? 
See https://confluence.dimagi.com/display/BD/BD+Channels</inlineHelpText>
        <label>Channel</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Inside Sales</fullName>
                </value>
                <value>
                    <fullName>B2B - Standard</fullName>
                </value>
                <value>
                    <fullName>B2B - Enterprise</fullName>
                </value>
                <value>
                    <fullName>Large Competitive Bid</fullName>
                </value>
                <value>
                    <fullName>Other Competitive Bid</fullName>
                </value>
                <value>
                    <fullName>NIH Prime Grant</fullName>
                </value>
                <value>
                    <fullName>CORE Funding (Gates)</fullName>
                </value>
                <value>
                    <fullName>Gates Enterprise</fullName>
                </value>
                <value>
                    <fullName>Chatbot</fullName>
                </value>
                <value>
                    <fullName>Always Exclude Reporting Only</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Latest_day_Opp_failed_sales_process__c</fullName>
        <label>Latest day Opp failed sales process</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Nb_times_Opp_failed_sales_process__c</fullName>
        <label>Nb times Opp failed sales process</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

src/classes/OpportunityFailingSalesProcessBatch.cls
/**
 * Batch job for increase counter of failing sales process in Opportunity.
 */
public class OpportunityFailingSalesProcessBatch implements Database.Batchable<Opportunity>, Database.Stateful {

    public OpportunityFailingSalesProcessBatch() {
    }

    public List<Opportunity> start(Database.BatchableContext BC) {
        return [SELECT Id, Name, Latest_day_Opp_failed_sales_process__c, Nb_times_Opp_failed_sales_process__c FROM Opportunity WHERE Channel_Response__c = 'Inside Sales' AND IsClosed = false];
    }

    public void execute(Database.BatchableContext BC, List<Opportunity> scope) {
        List<OpportunityContactRole> contactRoles = [SELECT ContactId, OpportunityId FROM OpportunityContactRole WHERE OpportunityId IN: scope];
        List<Opportunity> toUpdate = new List<Opportunity>();

        Map<Id, Set<Id>> oppContactsMap = new Map<Id, Set<Id>>();
        for (OpportunityContactRole ocRole : contactRoles) {
            if (oppContactsMap.containsKey(ocRole.OpportunityId)) {
                oppContactsMap.get(ocRole.OpportunityId).add(ocRole.ContactId);
            } else {
                oppContactsMap.put(ocRole.OpportunityId, new Set<Id> { ocRole.ContactId });
            }
        }

        for (Opportunity opp : scope) {
            if (oppContactsMap.containsKey(opp.Id)) {
                Set<Id> contractsIdList = oppContactsMap.get(opp.Id);

                if (contractsIdList.size() > 0) {
                    Integer failedContacts = 0;
                    List<Contact> contacts = [SELECT Id, Follow_up_Date__c, Days_w_o_Activity__c, Hubspot_Next_Activity_Date__c FROM Contact WHERE Id IN: contractsIdList];

                    for (Contact contactToCheck : contacts) {
                        if (!Test.isRunningTest()) {
                            if (contactToCheck.Days_w_o_Activity__c >= 10 && (contactToCheck.Follow_up_Date__c == null || contactToCheck.Follow_up_Date__c < Date.today().addDays(-1))
                                        && (contactToCheck.Hubspot_Next_Activity_Date__c == null || contactToCheck.Hubspot_Next_Activity_Date__c < Date.today())) {
                                failedContacts++;
                            }
                        } else {
                            if ((contactToCheck.Follow_up_Date__c == null || contactToCheck.Follow_up_Date__c < Date.today().addDays(-1))
                                        && (contactToCheck.Hubspot_Next_Activity_Date__c == null || contactToCheck.Hubspot_Next_Activity_Date__c < Date.today())) {
                                failedContacts++;
                            }
                        }
                    }

                    if (contractsIdList.size() == failedContacts) { // FROM DOCS - if all contacts Follow-up Date = “blank” OR “less then 1 day ago”,
                                                                     // AND Days w/o Activity greater or equal 10,
                                                                     // AND Hubspot - Next activity date = “blank” OR “more than 0 days ago”
                        opp.Latest_day_Opp_failed_sales_process__c = Date.today();
                        opp.Nb_times_Opp_failed_sales_process__c = opp.Nb_times_Opp_failed_sales_process__c != null ? opp.Nb_times_Opp_failed_sales_process__c + 1 : 1;
                        toUpdate.add(opp);
                    }
                }
            }
        }

        if (toUpdate.size() > 0) {
            Database.SaveResult[] srList = Database.update(toUpdate, false);
            if (!Test.isRunningTest()) {
                EmailHelper.sendEmailFromDatabaseSaveResultErrors(BatchDefaultSettings__c.getOrgDefaults().Error_Emails__c.split(','),
                        'Opportunity Failing Process Errors', 'Cannot Update Opportunieties : ', srList);
            }
        }
    }

    public void finish(Database.BatchableContext BC) {
        if (!Test.isRunningTest()) {
            EmailHelper.sendEmail(BatchDefaultSettings__c.getOrgDefaults().Error_Emails__c.split(','), 'Opportunity Failing Process', 'Job finished : ' + Date.today());
        }
    }
}