src/objects/Business_Unit__c.object
<CustomObject>
    <description>The various Dimagi contracting entities.</description>
    <label>Business Unit</label>
    <nameField>
        <label>Business Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Country__c.object
<CustomObject>
    <description>The different countries we work in</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Country_Text__c</fullName>
        <inlineHelpText>Text field to display attached Countries for reporting. Populated automatically when you add a location.</inlineHelpText>
        <label>Country</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>What country is this opportunity taking place.</inlineHelpText>
        <label>Implementing Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Implementing_Business_Unit__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>The Dimagi BU that will manage the execution of the project.</inlineHelpText>
        <label>Execution Owner (BU)</label>
        <referenceTo>Business_Unit__c</referenceTo>
        <relationshipLabel>Opportunities (Execution)</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <description>Used by snapshots to prepopulate fields.</description>
        <inlineHelpText>Used by snapshots to prepopulate fields.</inlineHelpText>
        <label>Snapshot Source Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Opportunity</fullName>
                    <default>true</default>
                    <label>Opportunity</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/objects/OpportunityCountry__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Opportunity Countries (Country)</relationshipLabel>
        <relationshipName>OpportunityCountries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Countries</relationshipLabel>
        <relationshipName>OpportunityCountries</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Opportunity Country</label>
    <nameField>
        <displayFormat>OC-{000000}</displayFormat>
        <label>OpportunityCountry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/OpportunityCountryTriggerTest.cls
/**
 * Tests the updates of the Country_Text__c field in Opportunity with the names of the Opportunity Countries
 *
 * @author  Virginia Fernández
 * @date    04/12/2013
 */
@isTest
private class OpportunityCountryTriggerTest {

    static testMethod void newOpportunityCountryTest() {
        Business_Unit__c bunit = new Business_Unit__c();
        bunit.Name = 'Test';
        insert bunit; 
        
        Opportunity opp = new Opportunity();
        opp.Name = 'Test';
        opp.StageName = 'Stage 1 - Connect';
        opp.CloseDate = Date.newInstance(2013, 4, 9);
        opp.Implementing_Business_Unit__c = bunit.Id;
        insert opp;
        
        Country__c country1 = new Country__c();
        country1.Name = 'Country1';
        insert country1;
        
        Country__c country2 = new Country__c();
        country2.Name = 'Country2';
        insert country2;
        
        Test.startTest();
        
        OpportunityCountry__c oppCountry1 = new OpportunityCountry__c();
        oppCountry1.Country__c = country1.Id;
        oppCountry1.Opportunity__c = opp.Id;
        insert oppCountry1;
        
        opp = [select Id, Country_Text__c from Opportunity where id =: opp.Id];
        System.assertEquals(opp.Country_Text__c, 'Country1');
        
        OpportunityCountry__c oppCountry2 = new OpportunityCountry__c();
        oppCountry2.Country__c = country2.Id;
        oppCountry2.Opportunity__c = opp.Id;
        insert oppCountry2;
        
        opp = [select Id, Country_Text__c from Opportunity where id =: opp.Id];
        System.assertEquals(opp.Country_Text__c, 'Country2; Country1');
        
        Test.stopTest();
        
    }
    
    static testMethod void deleteOpportunityCountryTest() {
        Business_Unit__c bunit = new Business_Unit__c();
        bunit.Name = 'Test';
        insert bunit; 
        
        Opportunity opp = new Opportunity();
        opp.Name = 'Test';
        opp.StageName = 'Stage 1 - Connect';
        opp.CloseDate = Date.newInstance(2013, 4, 9);
        opp.Implementing_Business_Unit__c = bunit.Id;
        insert opp;
        
        Country__c country1 = new Country__c();
        country1.Name = 'Country1';
        insert country1;
        
        Country__c country2 = new Country__c();
        country2.Name = 'Country2';
        insert country2;
        
        OpportunityCountry__c oppCountry1 = new OpportunityCountry__c();
        oppCountry1.Country__c = country1.Id;
        oppCountry1.Opportunity__c = opp.Id;
        insert oppCountry1;
        
        OpportunityCountry__c oppCountry2 = new OpportunityCountry__c();
        oppCountry2.Country__c = country2.Id;
        oppCountry2.Opportunity__c = opp.Id;
        insert oppCountry2;
        
        Test.startTest();
        
        opp = [select Id, Country_Text__c from Opportunity where id =: opp.Id];
        System.assertEquals(opp.Country_Text__c, 'Country2; Country1');
        
        delete oppCountry2;
        
        opp = [select Id, Country_Text__c from Opportunity where id =: opp.Id];
        System.assertEquals(opp.Country_Text__c, 'Country1');
        
        Test.stopTest();
        
    }
    
    static testMethod void updateOpportunityCountryTest() {
        Business_Unit__c bunit = new Business_Unit__c();
        bunit.Name = 'Test';
        insert bunit; 
        
        Opportunity opp = new Opportunity();
        opp.Name = 'Test';
        opp.StageName = 'Stage 1 - Connect';
        opp.CloseDate = Date.newInstance(2013, 4, 9);
        opp.Implementing_Business_Unit__c = bunit.Id;
        insert opp;
        
        Country__c country1 = new Country__c();
        country1.Name = 'Country1';
        insert country1;
        
        Country__c country2 = new Country__c();
        country2.Name = 'Country2';
        insert country2;
        
        OpportunityCountry__c oppCountry1 = new OpportunityCountry__c();
        oppCountry1.Country__c = country1.Id;
        oppCountry1.Opportunity__c = opp.Id;
        insert oppCountry1;
        
        Test.startTest();
        
        opp = [select Id, Country_Text__c from Opportunity where id =: opp.Id];
        System.assertEquals(opp.Country_Text__c, 'Country1');
        
        oppCountry1.Country__c = country2.Id;
        TriggerContext.runTrigger = true;
        update oppCountry1;
        
        opp = [select Id, Country_Text__c from Opportunity where id =: opp.Id];
        System.assertEquals(opp.Country_Text__c, 'Country2');
        
        Test.stopTest();
        
    }
}