src/objects/Business_Unit__c.object
<CustomObject>
    <description>The various Dimagi contracting entities.</description>
    <label>Business Unit</label>
    <nameField>
        <label>Business Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Contact Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1- Working - Active Opp Development</fullName>
                </value>
                <value>
                    <fullName>2- Working - Talking</fullName>
                </value>
                <value>
                    <fullName>3- Working - Contacted</fullName>
                </value>
                <value>
                    <fullName>4- Strategic Partner</fullName>
                </value>
                <value>
                    <fullName>5- Active Project Team Member</fullName>
                </value>
                <value>
                    <fullName>6- Active Self Start</fullName>
                </value>
                <value>
                    <fullName>7- Passive &amp; Friendly</fullName>
                </value>
                <value>
                    <fullName>8- Passive &amp; Unfriendly</fullName>
                </value>
                <value>
                    <fullName>9-HOLD Not mine/move</fullName>
                </value>
                <value>
                    <fullName>10-Dimagi Staff</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DContract__c.object
<CustomObject>
    <description>Tracks all of Dimagi&apos;s Contracts</description>
    <fields>
        <fullName>Contract_End_Date__c</fullName>
        <inlineHelpText>When the project actually ends.</inlineHelpText>
        <label>Contract End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Prime_Contracting_Business_Unit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Which business unit is actually doing the work on the project?</inlineHelpText>
        <label>Prime Contracting Business Unit</label>
        <referenceTo>Business_Unit__c</referenceTo>
        <relationshipLabel>Contracts (Prime Contracting Business Unit)</relationshipLabel>
        <relationshipName>Prime_Contract</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PRO_OAuth_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>PRO OAuth Settings</label>
    <fields>
        <fullName>Contact_Directory_Callback_URL__c</fullName>
        <label>Contact Directory Callback URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Domain_Name__c</fullName>
        <label>Domain Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/SFDC_Employee__c.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business Unit</label>
        <referenceTo>Business_Unit__c</referenceTo>
        <relationshipLabel>Employees</relationshipLabel>
        <relationshipName>Employees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Direct_Manager_Lookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Direct Manager</label>
        <referenceTo>SFDC_Employee__c</referenceTo>
        <relationshipLabel>Employees</relationshipLabel>
        <relationshipName>Employees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Direct_Manager__c</fullName>
        <label>Direct Manager SF ID</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email_Address__c</fullName>
        <label>Dimagi Email Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Employee_Status__c</fullName>
        <label>Employee Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LOA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Terminated</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Entity__c</fullName>
        <label>Entity</label>
        <picklist>
            <picklistValues>
                <fullName>Dimagi, INC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dimagi Software Innovations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dimagi South Africa</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Language_1_Proficiency__c</fullName>
        <label>Language 1 Proficiency</label>
        <picklist>
            <picklistValues>
                <fullName>Fluent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Proficient</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beginner</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Language_2_Proficiency__c</fullName>
        <label>Language 2 Proficiency</label>
        <picklist>
            <picklistValues>
                <fullName>Fluent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Proficient</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beginner</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Language_3_Proficiency__c</fullName>
        <label>Language 3 Proficiency</label>
        <picklist>
            <picklistValues>
                <fullName>Fluent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Proficient</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beginner</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Language_4_Proficiency__c</fullName>
        <label>Language 4 Proficiency</label>
        <picklist>
            <picklistValues>
                <fullName>Fluent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Proficient</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beginner</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Language_5_Proficiency__c</fullName>
        <label>Language 5 Proficiency</label>
        <picklist>
            <picklistValues>
                <fullName>Fluent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Proficient</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beginner</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Language_6_Proficiency__c</fullName>
        <label>Language 6 Proficiency</label>
        <picklist>
            <picklistValues>
                <fullName>Fluent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Proficient</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beginner</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Language_Spoken_2__c</fullName>
        <label>Language Spoken 2</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Language_Spoken_3__c</fullName>
        <label>Language Spoken 3</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Language_Spoken_4__c</fullName>
        <label>Language Spoken 4</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Language_Spoken_5__c</fullName>
        <label>Language Spoken 5</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Language_Spoken_6__c</fullName>
        <label>Language Spoken 6</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Languages_Spoken__c</fullName>
        <label>Language Spoken 1</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Personal_Phone_Number__c</fullName>
        <label>Personal Phone (with Country Code)</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Skype_ID__c</fullName>
        <label>Skype ID</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Unit__c</fullName>
        <label>Department</label>
        <picklist>
            <picklistValues>
                <fullName>Global Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mgmt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tech</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ops</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing &amp; Communications</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Development</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>70</length>
        <type>Text</type>
    </fields>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ContactDirectoryController.cls
public class ContactDirectoryController {

    private String token;
    private String currentLoginEmail;
    private String callback;
    private Boolean tokenIsValid;

    public String empSearchName { get; set; }
    public String showMessage { get; set; }
    public String contractSearchName { get; set; }

    public List<DContract__c> contractList { get; set; }
    public List<SFDC_Employee__c> empList { get; set; }

    public ContactDirectoryController() {
        this.tokenIsValid = false;
        PRO_OAuth_Settings__c settings = getSettings();
        this.callback = settings != null ? settings.Contact_Directory_Callback_URL__c : '';
    }

    public PageReference initAction() {
        Cookie googleResponse = ApexPages.currentPage().getCookies().get('googleResponseCD');
        String code = ApexPages.currentPage().getParameters().get('code');

        if (code != null) {
            List<Cookie> cookies = new List<Cookie>();
            ApexPages.currentPage().setCookies(new Cookie[] { new Cookie('googleResponseCD', code, null, 60, true) });
            PageReference cdPage = Page.ContactDirectory;
            cdPage.setRedirect(true);
            return cdPage;
        } else {
            if (googleResponse != null) {
                code = googleResponse.getValue();
                googleResponse = new Cookie('googleResponseCD', null, null, 0, true);
                ApexPages.currentPage().setCookies(new Cookie[] { googleResponse });
                this.token = SFAuthUtils.getFromJSON(SFAuthUtils.getAuthorizedReqToken(getSettings(), this.callback, code), 'access_token'); // here is exceptoipn bad request 400
                this.currentLoginEmail = SFAuthUtils.callForUserInfo(this.token);
                isTokenValid();
                loadPageData();
            }
        }
        return null;
    }

    public void loadPageData() {
        if (isTokenValid()) {
            this.empList = [SELECT Id, Name, Email_Address__c, Skype_ID__c, Direct_Manager_Lookup__c, Direct_Manager_Lookup__r.Name,
                            Business_Unit__c, Sub_Unit__c, Entity__c, Personal_Phone_Number__c, Title__c,
                            Languages_Spoken__c, Language_1_Proficiency__c, Language_Spoken_2__c, Language_2_Proficiency__c,
                            Language_Spoken_3__c, Language_3_Proficiency__c, Language_Spoken_4__c, Language_4_Proficiency__c,
                            Language_Spoken_5__c, Language_5_Proficiency__c, Language_Spoken_6__c, Language_6_Proficiency__c
                            FROM SFDC_Employee__c WHERE Employee_Status__c = 'Active'];

            this.contractList = [SELECT Id, Prime_Contracting_Business_Unit__c, Name, Prime_Contracting_Business_Unit__r.Name,
                                 Safety_Contact__c, Contract_End_Date__c
                                 FROM DContract__c WHERE Status__c IN ('Draft', 'Active')];
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Info,' If any information is incorrect please contact people-ops@dimagi.com'));
        }
    }

    public void searchEmp() {
        if (isTokenValid()) {
            String searchString = '%' + this.empSearchName + '%';
            this.empList = [SELECT Id, Name, Email_Address__c, Skype_ID__c, Direct_Manager__c, Direct_Manager_Lookup__c, Direct_Manager_Lookup__r.Name,
                            Business_Unit__c, Sub_Unit__c, Entity__c, Personal_Phone_Number__c, Title__c,
                            Languages_Spoken__c, Language_1_Proficiency__c, Language_Spoken_2__c, Language_2_Proficiency__c,
                            Language_Spoken_3__c, Language_3_Proficiency__c, Language_Spoken_4__c, Language_4_Proficiency__c,
                            Language_Spoken_5__c, Language_5_Proficiency__c, Language_Spoken_6__c, Language_6_Proficiency__c
                            FROM SFDC_Employee__c WHERE Employee_Status__c = 'Active' AND Name LIKE: searchString];
        }
    }

    public void searchContract(){
        if (isTokenValid()) {
            String searchString = '%' + this.contractSearchName + '%';
            this.contractList = [SELECT Id, Prime_Contracting_Business_Unit__c, Name, Prime_Contracting_Business_Unit__r.Name,
                                 Safety_Contact__c, Contract_End_Date__c
                                 FROM DContract__c WHERE Status__c IN ('Draft', 'Active') AND Name LIKE: searchString];
        }
    }

    public PageReference signIn() {
        PageReference authPage = new PageReference(SFAuthUtils.getSignInUrl(getSettings(), this.callback));
        authPage.setRedirect(true);
        return authPage;
    }

    public Boolean getAccessGranted() {
        if (Test.isRunningTest()) {
            return true;
        }

        if (this.token != null && this.tokenIsValid == true) {
            return true;
        }
        this.token = null;
        return false;
    }

    public Boolean isTokenValid() {
        if (Test.isRunningTest()) {
            return true;
        }
        String domainName = getSettings().Domain_Name__c;
        String userEmail = SFAuthUtils.callForUserInfo(this.token); // this method will throw an exception if token is not valid
        if (userEmail == this.currentLoginEmail && (domainName == 'gmail.com' || domainName == this.currentLoginEmail.split('@')[1])) {
             this.tokenIsValid = true;
        } else {
            this.token = null;
            this.tokenIsValid = false;
        }
        return this.tokenIsValid;
    }

    private PRO_OAuth_Settings__c getSettings() { // we don't want store settings in StateView
        List<PRO_OAuth_Settings__c> googleSettings = PRO_OAuth_Settings__c.getAll().values();
        if (googleSettings != null && googleSettings.size() > 0) {
            return googleSettings.get(0);
        }
        return null;
    }
}