src/objects/Business_Unit__c.object
<CustomObject>
    <description>The various Dimagi contracting entities.</description>
    <label>Business Unit</label>
    <nameField>
        <label>Business Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Contact Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1- Working - Active Opp Development</fullName>
                </value>
                <value>
                    <fullName>2- Working - Talking</fullName>
                </value>
                <value>
                    <fullName>3- Working - Contacted</fullName>
                </value>
                <value>
                    <fullName>4- Strategic Partner</fullName>
                </value>
                <value>
                    <fullName>5- Active Project Team Member</fullName>
                </value>
                <value>
                    <fullName>6- Active Self Start</fullName>
                </value>
                <value>
                    <fullName>7- Passive &amp; Friendly</fullName>
                </value>
                <value>
                    <fullName>8- Passive &amp; Unfriendly</fullName>
                </value>
                <value>
                    <fullName>9-HOLD Not mine/move</fullName>
                </value>
                <value>
                    <fullName>10-Dimagi Staff</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Channel_Response__c</fullName>
        <description>What Channel is the Opportunity (Sales, B2B, Pre-Bid, Other Competitive Bid, etc.)? 
See https://confluence.dimagi.com/display/BD/BD+Channels</description>
        <inlineHelpText>What Channel is the Opportunity (Sales, B2B, Pre-Bid, Other Competitive Bid, etc.)? 
See https://confluence.dimagi.com/display/BD/BD+Channels</inlineHelpText>
        <label>Channel</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Inside Sales</fullName>
                </value>
                <value>
                    <fullName>B2B - Standard</fullName>
                </value>
                <value>
                    <fullName>B2B - Enterprise</fullName>
                </value>
                <value>
                    <fullName>Large Competitive Bid</fullName>
                </value>
                <value>
                    <fullName>Other Competitive Bid</fullName>
                </value>
                <value>
                    <fullName>NIH Prime Grant</fullName>
                </value>
                <value>
                    <fullName>CORE Funding (Gates)</fullName>
                </value>
                <value>
                    <fullName>Gates Enterprise</fullName>
                </value>
                <value>
                    <fullName>Chatbot</fullName>
                </value>
                <value>
                    <fullName>Always Exclude Reporting Only</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Duration_months__c</fullName>
        <inlineHelpText>How long would this contract be spread over if we win?</inlineHelpText>
        <label>Duration (months)</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Implementation_Type__c</fullName>
        <label>Implementation Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Bundles and Services</fullName>
                </value>
                <value>
                    <fullName>Enterprise</fullName>
                </value>
                <value>
                    <fullName>Self Service</fullName>
                </value>
                <value>
                    <fullName>Managed server</fullName>
                </value>
                <value>
                    <fullName>EMM</fullName>
                </value>
                <value>
                    <fullName>Chatbot</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>of_Execution_budget_for_GS__c</fullName>
        <defaultValue>1</defaultValue>
        <description>This is the % of the remaining budget (after removing expenses and buffer %) that is planned for GS work</description>
        <inlineHelpText>This is the % of the remaining budget (after removing expenses and buffer %) that is planned for GS work</inlineHelpText>
        <label>% of Services budget for GS</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Opportunity_Owning_Entity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Which busniness unit owns this opportunity.</inlineHelpText>
        <label>Opportunity Owner (BU)</label>
        <referenceTo>Business_Unit__c</referenceTo>
        <relationshipLabel>Opportunities (Owning)</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity_Source__c</fullName>
        <description>Describes the source of the actual opportunity (not the lead).</description>
        <inlineHelpText>Choose a source of the opportunity.  Answers the question &quot;Where did we first hear about this opportunity?&quot;</inlineHelpText>
        <label>Opportunity Source</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Applied to RFP</fullName>
                </value>
                <value>
                    <fullName>Existing Project - New Deliverables/Scale Up</fullName>
                    <label>Existing Project - New Deliverables/Scale Up (reactive)</label>
                </value>
                <value>
                    <fullName>Existing Project - Contract Amendment</fullName>
                </value>
                <value>
                    <fullName>Existing Client - New Project</fullName>
                    <label>Existing Client - New Project (reactive)</label>
                </value>
                <value>
                    <fullName>Inbound</fullName>
                </value>
                <value>
                    <fullName>Inbound - Referred within same Org</fullName>
                </value>
                <value>
                    <fullName>Inbound - Referred by Another Org</fullName>
                </value>
                <value>
                    <fullName>Inbound - KAM</fullName>
                </value>
                <value>
                    <fullName>Outbound - Contacted Directly</fullName>
                </value>
                <value>
                    <fullName>Outbound-KAM (Key Account Management)</fullName>
                    <label>Outbound - KAM (Key Account Management)</label>
                </value>
                <value>
                    <fullName>Onboarding Package</fullName>
                </value>
                <value>
                    <fullName>Referred by Dimagi staff</fullName>
                </value>
                <value>
                    <fullName>Referral</fullName>
                </value>
                <value>
                    <fullName>Implementation Renewal</fullName>
                </value>
                <value>
                    <fullName>Implementation renewal - KAM</fullName>
                </value>
                <value>
                    <fullName>Product Renewal</fullName>
                </value>
                <value>
                    <fullName>Product renewal- KAM</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Pro-bono Renewal</fullName>
                </value>
                <value>
                    <fullName>Existing client - Upsell_reactive</fullName>
                    <label>Existing client - Upsell (reactive)</label>
                </value>
                <value>
                    <fullName>ABS (Proactive Account expansion)</fullName>
                </value>
                <value>
                    <fullName>Pre-bid (Crowd In)</fullName>
                </value>
                <value>
                    <fullName>Strategic Fundraising</fullName>
                </value>
                <value>
                    <fullName>Crisis Response Corps</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Renewal_expected__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Select this checkbox if you expect the customer to default to renew their subscriptions.</description>
        <inlineHelpText>Select this checkbox if you expect the customer to default to renew their subscriptions.</inlineHelpText>
        <label>SaaS product renewal expected</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src/classes/LeadConversionController.cls
/**
 * Controller for new Lead conversion button.
 */
public with sharing class LeadConversionController {

    private PageReference cancelPage = null;
    private Lead l;
    private Id leadId;

    public LeadConversionController(ApexPages.StandardController sc) {
        cancelPage = sc.cancel();
        this.leadId = sc.getId();
        this.l = fetchLeadById(sc.getId());
    }

    public PageReference doConversion() {

        PageReference page = null;
        if (l != null) {
            page = convertLead();
        } else {
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR, 'Cannot find lead with ID : ' + this.leadId));
        }

        return page;
    }

    public PageReference goBack() {
        return cancelPage;
    }

    private PageReference convertLead() {
        Database.LeadConvert lc = new Database.LeadConvert();
        lc.setLeadId(l.Id);
        LeadStatus convertStatus = [SELECT Id, MasterLabel FROM LeadStatus WHERE IsConverted = true LIMIT 1];
        lc.setConvertedStatus(convertStatus.MasterLabel);
        Database.LeadConvertResult lcr = Database.convertLead(lc);
        if (lcr.isSuccess()) {
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.CONFIRM, 'Lead was converted.'));

            Id contactId = lcr.getContactId();
            if (contactId != null) {
                Contact newContact = [SELECT Id, Status__c FROM Contact WHERE Id =: contactId];
                newContact.Status__c = '1- Working - Active Opp Development';
                update newContact;
            }

            Id oppId = lcr.getOpportunityId();
            if (oppId != null) {
                Opportunity newOpp = [SELECT Id, StageName, Probability, of_Execution_budget_for_GS__c, Channel_Response__c, Implementation_Type__c, Renewal_expected__c,
                                             Opportunity_Source__c, Duration_months__c, Opportunity_Owning_Entity__c, CloseDate FROM Opportunity WHERE Id =: oppId];
                newOpp.StageName = 'Stage 3 - Prospect';
                newOpp.Probability = 20;
                newOpp.of_Execution_budget_for_GS__c = 0;
                newOpp.Channel_Response__c = 'Inside Sales';
                newOpp.Implementation_Type__c = 'Self Service';
                newOpp.Opportunity_Source__c = 'Inbound';
                newOpp.Duration_months__c = 12;
                newOpp.CloseDate = Date.today().addMonths(1).toStartofMonth().addDays(-1);
                newOpp.Renewal_expected__c = true;

                Business_Unit__c bu = [SELECT Id FROM Business_Unit__c WHERE Name = 'Inc' LIMIT 1];
                if (bu != null) {
                    newOpp.Opportunity_Owning_Entity__c = bu.Id;
                }

                update newOpp;
            }

            PageReference contrPage = new ApexPages.StandardController(l).view();
            contrPage.setRedirect(true);
            return contrPage;
        } else {
            Database.Error[] errors = lcr.getErrors();
            String message = '';
            if (errors.size() > 0) {
                message += errors[0].getMessage();
            }
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR, 'Cannot conver lead : ' + message + '.'));
        }

        return null;
    }

    private Lead fetchLeadById(Id leadId) {
        return [SELECT  Id FROM Lead WHERE Id =: leadId];
    }
}