src/objects/Business_Unit__c.object
<CustomObject>
    <description>The various Dimagi contracting entities.</description>
    <label>Business Unit</label>
    <nameField>
        <label>Business Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Fogbugz_Ticket_Number__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>The ticket number of the corresponding Fogbugz ticket.</inlineHelpText>
        <label>Fogbugz Ticket Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Implementing_Business_Unit__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>The Dimagi BU that will manage the execution of the project.</inlineHelpText>
        <label>Execution Owner (BU)</label>
        <referenceTo>Business_Unit__c</referenceTo>
        <relationshipLabel>Opportunities (Execution)</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/classes/OpportunityTriggersTest.cls
/**
 * Tests the close of a FogBugz case upon Opportunity deletion
 *
 * @author  Virginia Fernández
 * @date    04/16/2013
 */

@isTest
private class OpportunityTriggersTest {

    static testMethod void deleteOpportunityTest() {
        Business_Unit__c bunit = new Business_Unit__c();
        bunit.Name = 'Test';
        insert bunit; 
        
        Opportunity opp = new Opportunity();
        opp.Name = 'Test';
        opp.StageName = 'Stage 1 - Connect';
        opp.CloseDate = Date.newInstance(2013, 4, 9);
        opp.Implementing_Business_Unit__c = bunit.Id;
        opp.Fogbugz_Ticket_Number__c = TestFogBugzAPI.TEST_FB_ID;
        insert opp;
        
        Test.startTest();
        
        delete opp;
        
        Test.stopTest();
    }
}