src/objects/Business_Unit__c.object
<CustomObject>
    <description>The various Dimagi contracting entities.</description>
    <label>Business Unit</label>
    <nameField>
        <label>Business Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SFDC_Employee__c.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business Unit</label>
        <referenceTo>Business_Unit__c</referenceTo>
        <relationshipLabel>Employees</relationshipLabel>
        <relationshipName>Employees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SF_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SF User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>R00N30000001eUPVEA2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/classes/EmployeeGateway.cls
public class EmployeeGateway {

    public static Map<Id, String> getEmployeeBusinessUnitNames(Set<Id> employeeRecordIds) {
        Map<Id, String> businessUnitNames = new Map<Id, String>();
        for(SFDC_Employee__c emp : [SELECT Id, Business_Unit__c, Business_Unit__r.Name
                                    FROM SFDC_Employee__c
                                    WHERE Id IN: employeeRecordIds AND Business_Unit__c != null]) {
            businessUnitNames.put(emp.Business_Unit__c, emp.Business_Unit__r.Name);
        }
        return businessUnitNames;
    }

    public static void setUsersOnEmployees(Map<String, SFDC_Employee__c> employeesByEmail) {
        for(User u : [SELECT Id, Username FROM User WHERE Username IN: employeesByEmail.keySet()]) {
            employeesByEmail.get(u.Username).SF_User__c = u.Id;
        }
    }
}