src/objects/Clockify_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Clockify api url and api key.</description>
    <label>Clockify Settings</label>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Page_Size__c</fullName>
        <label>Page Size</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>URL__c</fullName>
        <label>URL</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>XApikey__c</fullName>
        <label>XApikey</label>
        <length>250</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/DContract__c.object
<CustomObject>
    <description>Tracks all of Dimagi&apos;s Contracts</description>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SFDC_Employee__c.object
<CustomObject>
    <fields>
        <fullName>Email_Address__c</fullName>
        <label>Dimagi Email Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Employee_Status__c</fullName>
        <label>Employee Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LOA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Terminated</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Employee_Type__c</fullName>
        <label>Employee Type</label>
        <picklist>
            <picklistValues>
                <fullName>Employee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contractor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>External Contractor</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Exchange_Rate__c</fullName>
        <label>Exchange Rate (Local:USD)</label>
        <precision>18</precision>
        <required>true</required>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Hire_Date__c</fullName>
        <label>Hire Date</label>
        <type>Date</type>
    </fields>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Status_Log__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <type>TextArea</type>
    </fields>
    <label>Status Log</label>
    <nameField>
        <label>Status Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Status Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Time_Card__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Employee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Employee</label>
        <referenceTo>SFDC_Employee__c</referenceTo>
        <relationshipLabel>Time Cards</relationshipLabel>
        <relationshipName>Time_Cards</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Time Card</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Time Card Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ClockifySyncTest.cls
@isTest
public class ClockifySyncTest {
    @TestSetup
    static void createData(){
        Time_Card__c tcard = new Time_Card__c();
        SFDC_Employee__c emp = new SFDC_Employee__c();
        emp.Name = 'Employee 1';
        emp.Email_Address__c = 'employee@dimagi.com';
        emp.Exchange_Rate__c = 1;
        emp.Employee_Status__c = 'Active';
        emp.Employee_Type__c = 'Employee';
        emp.Hire_Date__c = System.today() - 180;
        insert emp;
        
        DContract__c client = new DContract__c();
        client.Name = 'Overhead';
        insert client;
        tcard.Time_Entry_ID__c = '600d7f09843909186990142g';
        tcard.Date__c = System.today();
        tcard.Employee__c = emp.Id;
        insert tcard;
        
        Clockify_Settings__c clockifySetting = new Clockify_Settings__c();
        clockifySetting.Name__c = 'Clockify';
        clockifySetting.Page_Size__c = 5;
        clockifySetting.XApikey__c = 'APIKEY';
        clockifySetting.URL__c = 'Clockify/test.org/timeEntries';
        insert clockifySetting;
       	System.debug('client: '+client);
    }
    @isTest
    public static void ClockifyManualCalloutController(){
        //visual force page controller
        List<Time_Card__c> timeCard = [SELECT Id from Time_Card__c where Employee__r.Name = 'Employee 1' LIMIT 1];
        PageReference pageRef = Page.ClockifyManualCallout;
        Test.setCurrentPage(pageRef);
        Test.startTest();
        pageRef.getParameters().put('Id', String.valueOf(timeCard[0].Id));
        ApexPages.StandardSetController sc = new ApexPages.StandardSetController(timeCard);
        ClockifyManualCallout clockifyManualCalloutCtrl =  new ClockifyManualCallout(sc);
        clockifyManualCalloutCtrl.runRecalculation();
        System.assert(ApexPages.hasMessages(ApexPages.SEVERITY.CONFIRM));
        Test.stopTest();
        
    }
    @isTest
    public static void testBackPage(){
        List<Time_Card__c> timeCard = [SELECT Id from Time_Card__c where Employee__r.Name = 'Employee 1' LIMIT 1];
        PageReference pageRef = Page.ClockifyManualCallout;
        Test.setCurrentPage(pageRef);
        Test.startTest();
        pageRef.getParameters().put('Id', String.valueOf(timeCard[0].Id));
        ApexPages.StandardSetController sc = new ApexPages.StandardSetController(timeCard);
        ClockifyManualCallout clockifyManualCalloutCtrl =  new ClockifyManualCallout(sc);
        clockifyManualCalloutCtrl.goBack();
        Test.stopTest();
        
        System.assertEquals(false, pageRef.getRedirect());
    }
    @isTest
    public static void testClockifySyncBatch(){
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new ClockifyAPIMockCallout());
        Database.executeBatch(new ClockifySyncBatch(), 1);
        Test.stopTest();
        Time_Card__c timeCard = [SELECT Id,Time_Entry_ID__c,Employee__r.Name from Time_Card__c WHERE Employee__r.Name = 'Employee 1' LIMIT 1];
        System.debug('Employee : ' +timeCard.Employee__r.Name);
        System.assertEquals('Employee 1', timeCard.Employee__r.Name);
    }
    @isTest
    public static void exceptionNonUser(){
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new ClockifyNonUserMock());
        Database.executeBatch(new ClockifySyncBatch(), 1);
        Test.stopTest();
        List<Status_log__c> errorLogs = [SELECT Id,message__c from Status_log__c WHERE Createddate = today];
        System.debug('errorLogs : ' +errorLogs.size());
        System.assert(errorLogs.size()>0) ;
    }
    @isTest
    public static void testClockifySyncScheduler(){
        Test.StartTest();
        Test.setMock(HttpCalloutMock.class, new ClockifyAPIMockCallout());
        ClockifySyncScheduler sh1 = new ClockifySyncScheduler();
        
        String sch = '0 0 10 ? * WED'; 
        System.schedule('Clockify Sync', sch, sh1); 
        Test.stopTest(); 
    }
}