src/objects/Contract_Country__c.object
<CustomObject>
    <description>Links contracts to countries.</description>
    <fields>
        <fullName>Contract__c</fullName>
        <label>Contract</label>
        <referenceTo>DContract__c</referenceTo>
        <relationshipLabel>Countries</relationshipLabel>
        <relationshipName>Contract_Countries</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contract_Countries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Contract Country</label>
    <nameField>
        <displayFormat>CC-{00000}</displayFormat>
        <label>Contract Country Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Countries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Country__c.object
<CustomObject>
    <description>The different countries we work in</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DContract__c.object
<CustomObject>
    <description>Tracks all of Dimagi&apos;s Contracts</description>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ContractCountryTrigger.cls
/**
 * Updates the Country_Text__c field in Contract with the names of the Contract Countries
 * @author  Virginia Fernández
 * @date    04/12/2013
 */
public with sharing class ContractCountryTrigger {

    public static void onUpdate(Contract_Country__c[] newContrCountries) {
        Set<Id> contrIds = new Set<Id>();
        for (Contract_Country__c cci : newContrCountries) {
            contrIds.add(cci.Contract__c);
        }

        Map<Id, DContract__c> mapContracts = new Map<Id, DContract__c>();
        Set<Id> countriesIds = new Set<Id>();
        List<DContract__c> contracts = [SELECT Id, Country_Text__c,
                                        (SELECT Country__c FROM Contract_Countries__r)
                                        FROM DContract__c
                                        WHERE id IN: contrIds];

        for (DContract__c contract : contracts) {
            mapContracts.put(contract.Id, contract);
            for (Contract_Country__c contrCountry : contract.Contract_Countries__r) {
                countriesIds.add(contrCountry.Country__c);
            }
        }

        Map<Id, String> countryNames = new Map<Id, String>();
        for (Country__c country: [SELECT Id, Name FROM Country__c WHERE Id IN: countriesIds]) {
            countryNames.put(country.Id, country.Name);
        }

        for (DContract__c contract : contracts) {
            contract.Country_Text__c = '';
            for (Contract_Country__c contractCountry : contract.Contract_Countries__r) {
                if ((contract.Country_Text__c != '') && (!contract.Country_Text__c.endsWith('; '))) {
                    contract.Country_Text__c += '; ';
                }
                contract.Country_Text__c += countryNames.get(contractCountry.Country__c);
            }
        }
        update contracts;
    }
}