src/objects/Contract_Opportunity__c.object
<CustomObject>
    <description>Linkage between a Opportunities and Contracts</description>
    <label>Opportunity Contract</label>
    <nameField>
        <displayFormat>OC-{00000}</displayFormat>
        <label>Opportunity Contract Link ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Contract</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Contract__c</fullName>
        <label>Contract</label>
        <referenceTo>DContract__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunity_Contract</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contract_Opportunity</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

src/objects/DContract__c.object
<CustomObject>
    <description>Tracks all of Dimagi&apos;s Contracts</description>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Opportunity__c</fullName>
        <description>Used by snapshots to prepopulate fields.</description>
        <inlineHelpText>Used by snapshots to prepopulate fields.</inlineHelpText>
        <label>Snapshot Source Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Opportunity</fullName>
                    <default>true</default>
                    <label>Opportunity</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/classes/ContractOpportunityController.cls
public with sharing class ContractOpportunityController {

    private Id opportunityId;
    private Id contractId;

    public Contract_Opportunity__c coRelation { get; set; }

    public ContractOpportunityController(ApexPages.StandardController sc) {
        this.coRelation = (Contract_Opportunity__c) sc.getRecord();
        this.opportunityId = ApexPages.currentPage().getParameters().get('opportunityId');
        this.contractId = ApexPages.currentPage().getParameters().get('contractId');
        this.coRelation.Opportunity__c = this.opportunityId;
        this.coRelation.Contract__c = this.contractId;
    }

    public PageReference saveNewRelation() {
        upsert this.coRelation;
        PageReference redirectPage = getReturnPage();
        return redirectPage;
    }

    public PageReference goBack() {
        return getReturnPage();
    }

    private PageReference getReturnPage() {
        PageReference redirectPage = null;
        if (this.opportunityId != null) {
            redirectPage = new ApexPages.StandardController(new Opportunity(Id = this.opportunityId)).view();
        } else if (this.contractId != null) {
            DContract__c contract = new DContract__c();
            redirectPage = new ApexPages.StandardController(new DContract__c(Id = this.contractId)).view();
        } else {
            return null;
        }
        redirectPage.setRedirect(true);

        return redirectPage;
    }
}