src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Contact Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1- Working - Active Opp Development</fullName>
                </value>
                <value>
                    <fullName>2- Working - Talking</fullName>
                </value>
                <value>
                    <fullName>3- Working - Contacted</fullName>
                </value>
                <value>
                    <fullName>4- Strategic Partner</fullName>
                </value>
                <value>
                    <fullName>5- Active Project Team Member</fullName>
                </value>
                <value>
                    <fullName>6- Active Self Start</fullName>
                </value>
                <value>
                    <fullName>7- Passive &amp; Friendly</fullName>
                </value>
                <value>
                    <fullName>8- Passive &amp; Unfriendly</fullName>
                </value>
                <value>
                    <fullName>9-HOLD Not mine/move</fullName>
                </value>
                <value>
                    <fullName>10-Dimagi Staff</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Project_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contract_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Email</field>
                <operation>contains</operation>
                <value>@dimagi.com</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contract Contacts</relationshipLabel>
        <relationshipName>Contract_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <label>Contract</label>
        <referenceTo>DContract__c</referenceTo>
        <relationshipLabel>Contract Contacts</relationshipLabel>
        <relationshipName>Contract_Contacts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Person</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Field Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Backstop</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Contract Contact</label>
    <nameField>
        <displayFormat>OC-{000000}</displayFormat>
        <label>Contract Contact Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/DContract__c.object
<CustomObject>
    <description>Tracks all of Dimagi&apos;s Contracts</description>
    <fields>
        <fullName>Backstop__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Who to escalate to for issues.</inlineHelpText>
        <label>Backstop</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Backstop</relationshipLabel>
        <relationshipName>Backstop</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Dimagi PM</inlineHelpText>
        <label>Project Manager</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Contracts_PM</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project_Report_Out__c.object
<CustomObject>
    <label>Project Report Out</label>
    <nameField>
        <label>Project Report Out Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Report Outs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Contract__c</fullName>
        <label>Contract</label>
        <referenceTo>DContract__c</referenceTo>
        <relationshipLabel>Project Report Outs</relationshipLabel>
        <relationshipName>Contract_Project_Report_Outs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Report_Out_Date__c</fullName>
        <inlineHelpText>The last day of the report out period.</inlineHelpText>
        <label>Report Out Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Requires_Developer_Work__c</fullName>
        <label>Internal Developer Deadlines</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Green</fullName>
                    <color>#009900</color>
                    <label>Green</label>
                </value>
                <value>
                    <fullName>Yellow</fullName>
                    <color>#F3D904</color>
                    <label>Yellow</label>
                </value>
                <value>
                    <fullName>Red</fullName>
                    <color>#FF0000</color>
                    <label>Red</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/classes/PROAllProjectsComponentController.cls
public  class PROAllProjectsComponentController {

    public String employeeEmail { get; set; }
    public DimagiToolsController pageController { get; set; }

    public String projectId { get; set; }
    public List<Contract_Contact__c> contractContacts { get; set; }
    public List<Contract_Contact__c> contractContactsProject { get; set; }
    public String removeEmailId { get; set; }
    public Id removeContactId { get; set; }
    public DContract__c project { get; set; }
    public List<Project_Report_Out__c> LastRepotOuts { get; set; }
    public boolean enableAddButton{ get; set; }
    public String selectedProjectId { get; set; }
    private List<Contract_Contact__c> deleteContactList = new List<Contract_Contact__c>();

    public PROAllProjectsComponentController() {
        
    }

    public List<DimagiToolsController.PROProject> getProjectsList() {
        if (!this.pageController.getAccessGranted()) {
            return null;
        }
        List<DimagiToolsController.PROProject> proList = new List<DimagiToolsController.PROProject>();
        DContract__c[] contracts = [SELECT Id, Name, Requires_Developer_Work__c, Last_Report_Out_Date__c, Last_Report_Out_Status__c, Percent_through_Contract__c, Percent_through_SOW_deliverables__c
                                    FROM DContract__c
                                    WHERE Requires_Report_Out__c = 'Yes'
                                    ORDER BY Name];

        if (contracts.size() > 0 && this.selectedProjectId == null) {
            if (this.projectId != null && this.projectId != 'null' && this.projectId != ' ') {
                this.projectId = '' + this.projectId;
                this.selectedProjectId = this.projectId;
                this.projectId = null;
            } else {
                this.selectedProjectId = contracts[0].Id;
            }
            fillProjectDetails();
        }

        for (DContract__c dc : contracts) {
            DimagiToolsController.PROProject prObj = new DimagiToolsController.PROProject();
            prObj.Contract = dc;
            if (selectedProjectId != null && selectedProjectId != '') {
                prObj.cssClass = dc.id == selectedProjectId ? 'bgColorCls' : '';
            }
            proList.add(prObj);
        }

        return proList;
    }

    public void fillProjectDetails() {
        if (!this.pageController.getAccessGranted()) {
            return;
        }
        this.deleteContactList.clear();
        this.contractContacts = new List<Contract_Contact__c>();

        List<DContract__c> contractList = [SELECT Id, Project_Manager__c, Backstop__c, Field_Manager__c, In_Charge_Of_Report_Out__c FROM DContract__c
                                                 WHERE Id =: this.selectedProjectId];

        if (contractList != null && contractList.size() > 0) {
            this.project = contractList[0];
        }

        this.contractContactsProject = [SELECT Id, Contact__c, Contract__c, Type__c, Email__c FROM Contract_Contact__c WHERE Contract__c =: selectedProjectId AND Type__c NOT in('Person','Email')];
        this.contractContacts = [SELECT Id, Contact__c, Contract__c, Type__c, Email__c  FROM Contract_Contact__c WHERE Contract__c =: selectedProjectId AND Type__C in ('Person', 'Email') ORDER BY Type__c DESC];
        this.lastRepotOuts = [SELECT id,Name,status__c,Contract__r.Name,Contract__r.Last_Report_Out_Date__c,Report_Out_Date__c  FROM Project_Report_Out__c
                         WHERE Contract__C =: selectedProjectId ORDER BY Report_Out_Date__c DESC];
        this.enableAddButton = true;
    }

    public PageReference saveProjectOnly() {
        PageReference page = null;
        if (!this.pageController.isTokenValid()) {
            return page;
        }
        saveProjectData();
        return page;
    }

    public PageReference saveProject() {
        PageReference page = null;
        if (!this.pageController.isTokenValid()) {
            return page;
        }
        saveProjectData();
        saveContactData();

        return page;
    }

    public void saveContact() {
        if (!this.pageController.isTokenValid()) {
            return;
        }
        saveContactData();
    }

    public Boolean validateProject() {
        if (this.selectedProjectId == null || this.selectedProjectId == '') {
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR, 'You must select a project.'));
            return false;
        }
        return true;
    }

    public void removeContact() {
        if (this.contractContacts.size() > 0) {
            Integer removeIndex = -1;
            for (Integer index = 0; index < this.contractContacts.size(); index++) {
                Contract_Contact__c ct = this.contractContacts[index];
                if (ct.Contact__c == this.removeContactId) {
                    if (ct.id != null) {
                        this.deleteContactList.add(ct);
                    }

                    removeIndex = index;
                    break;
                }
            }

            if (removeIndex == -1) {
                for (Integer index = 0; index < this.contractContacts.size(); index++) {
                    Contract_Contact__c ct = this.contractContacts[index];
                    if (ct.Type__c == 'Person' && ct.Contact__c == null) {
                        removeIndex = index;
                        break;
                    }
                }
            }

            if (removeIndex != -1) {
                this.contractContacts.remove(removeIndex);
            }
        }
    }

    public void removeEmail() {
        if (this.contractContacts.size() > 0) {
            Integer removeIndex = -1;

            for (Integer index = 0; index < this.contractContacts.size(); index++) {
                Contract_Contact__c ct = this.contractContacts[index];
                if (ct.Email__c == this.removeEmailId) {
                    if (ct.id != null) {
                        this.deleteContactList.add(ct);
                    }

                    removeIndex = index;
                    break;
                }
            }

            if (removeIndex == -1) {
                for (Integer index = 0; index < this.contractContacts.size(); index++) {
                    Contract_Contact__c ct = this.contractContacts[index];
                    if (ct.Type__c == 'Email' && ct.Email__c == null) {
                        removeIndex = index;
                        break;
                    }
                }
            }

            if (removeIndex != -1) {
                this.contractContacts.remove(removeIndex);
            }
        }
    }

    public void addContact() {
        addToContractContacts('Person');
    }

    public void addEmail() {
        addToContractContacts('Email');
    }

    public void addMe() {
        List<Contact> contList = [SELECT Id,Name FROM Contact WHERE Email =: this.employeeEmail];

        if (contList.size() > 0) {
            Contract_Contact__c contractContact = new Contract_Contact__c();
            contractContact.Contract__c = selectedProjectId;
            contractContact.Type__C = 'Person';
            contractContact.Contact__C = contList[0].id;
            this.contractContacts.add(contractContact);
        }
    }


    private void saveProjectData() {
        if (validateProject()) {
            try {
                update this.project;
            } catch (DmlException ex) {
                ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR, ex.getDmlMessage(0)));
            } catch (Exception e) {
                ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR, e.getMessage()));
            }

            this.contractContactsProject = [SELECT Id, Contact__c, Contract__c, Type__c, Email__c FROM Contract_Contact__c
                                            WHERE Contract__C =: this.selectedProjectId AND Type__c NOT IN('Person','Email')];
        }
    }

    private void saveContactData() {
        List<Integer> removeIndex = new List<Integer>();
        if (this.contractContacts != null) {
            for (Integer index = 0; index < this.contractContacts.size(); index++) {
                Contract_Contact__c contContact = this.contractContacts[index];
                if (contContact.Contact__c != null || contContact.Email__c != null) {
                     upsert contContact;
                } else {
                    if (contContact.Id != null) {
                        removeIndex.add(index);
                        delete contContact;
                    }
                }
            }
        }

        for (Integer index = 0 ;index < removeIndex.size(); index++) {
            this.contractContacts.remove(removeIndex[index]);
        }

        if (this.deleteContactList.size() > 0) {
            delete this.deleteContactList;
            this.deleteContactList.clear();
        }
    }

    private void addToContractContacts(String contactType) {
        Contract_Contact__c contractContact = new Contract_Contact__c();
        contractContact.Contract__c = selectedProjectId;
        contractContact.Type__C = contactType;
        this.contractContacts.add(contractContact);
    }
}