src/objects/Contract_Product__c.object
<CustomObject>
    <label>Contract Product</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Contract Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Contract__c</fullName>
        <label>Contract</label>
        <referenceTo>DContract__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

src/objects/DContract__c.object
<CustomObject>
    <description>Tracks all of Dimagi&apos;s Contracts</description>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/classes/ContractProductController.cls
public with sharing class ContractProductController {

    private Id contractId;
    public Contract_Product__c currentRecord { get; set;}

    public ContractProductController(ApexPages.StandardController sc) {
        this.contractId = ApexPages.currentPage().getParameters().get('contractId');

        this.currentRecord = (Contract_Product__c) sc.getRecord();
        this.currentRecord.Contract__c = this.contractId;
    }

    public PageReference saveNewRelation() {
        upsert this.currentRecord;
        PageReference redirectPage = getReturnPage();
        return redirectPage;
    }

    public PageReference goBack() {
        return getReturnPage();
    }

    private PageReference getReturnPage() {
        PageReference redirectPage = null;
        if (this.contractId != null) {
            redirectPage = new ApexPages.StandardController(new DContract__c(Id = this.contractId)).view();
        } else {
            return null;
        }
        redirectPage.setRedirect(true);

        return redirectPage;
    }
}