src/objects/Country__c.object
<CustomObject>
    <description>The different countries we work in</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Location__c.object
<CustomObject>
    <description>Tracks where our projects are executed.  Countries, Regions, States, and Geopoint.</description>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>What country is this opportunity taking place.</inlineHelpText>
        <label>Implementing Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity_Owner_Division__c</fullName>
        <description>This fields describes which division is driving the BD efforts related to this opportunity.</description>
        <inlineHelpText>This fields describes which division is driving the BD efforts related to this opportunity.</inlineHelpText>
        <label>Opportunity Owner (Division)</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Solutions</fullName>
                </value>
                <value>
                    <fullName>SaaS</fullName>
                </value>
                <value>
                    <fullName>GSO</fullName>
                </value>
                <value>
                    <fullName>GTD</fullName>
                </value>
                <value>
                    <fullName>India Division</fullName>
                </value>
                <value>
                    <fullName>USH</fullName>
                </value>
                <value>
                    <fullName>ICDS-CAS</fullName>
                    <isActive>false</isActive>
                    <label>ICDS-CAS</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity_Owner_Sub_Division__c</fullName>
        <description>This fields describes which sub-division or Practice is driving the BD efforts related to this opportunity.</description>
        <inlineHelpText>This fields describes which sub-division or Practice is driving the BD efforts related to this opportunity.</inlineHelpText>
        <label>Opportunity Owner (Sub-Division)</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>GSO - BizOps</fullName>
                </value>
                <value>
                    <fullName>GSO - BizStrat</fullName>
                </value>
                <value>
                    <fullName>GSO - CC Connect</fullName>
                </value>
                <value>
                    <fullName>GSO - Dgtl Adherence</fullName>
                </value>
                <value>
                    <fullName>GSO - Leadership</fullName>
                </value>
                <value>
                    <fullName>GSO - Marketing</fullName>
                </value>
                <value>
                    <fullName>GSO - OoCEO</fullName>
                </value>
                <value>
                    <fullName>GSO - POps</fullName>
                </value>
                <value>
                    <fullName>GSO - RAD</fullName>
                </value>
                <value>
                    <fullName>GTD - Eng Management</fullName>
                </value>
                <value>
                    <fullName>GTD - Leadership</fullName>
                </value>
                <value>
                    <fullName>GTD - QA</fullName>
                </value>
                <value>
                    <fullName>GTD - Team</fullName>
                </value>
                <value>
                    <fullName>Inbound Sales</fullName>
                </value>
                <value>
                    <fullName>India - Delivery</fullName>
                </value>
                <value>
                    <fullName>India - Leadership</fullName>
                </value>
                <value>
                    <fullName>India - Partnerships</fullName>
                </value>
                <value>
                    <fullName>India - Tech</fullName>
                </value>
                <value>
                    <fullName>SaaS - CS</fullName>
                </value>
                <value>
                    <fullName>SaaS - Management</fullName>
                </value>
                <value>
                    <fullName>SaaS - Marketing</fullName>
                </value>
                <value>
                    <fullName>SaaS - Operations</fullName>
                </value>
                <value>
                    <fullName>SaaS - Platform</fullName>
                </value>
                <value>
                    <fullName>SaaS - Product</fullName>
                </value>
                <value>
                    <fullName>SaaS - Sales</fullName>
                </value>
                <value>
                    <fullName>SaaS - Support</fullName>
                </value>
                <value>
                    <fullName>Sol - Delivery</fullName>
                </value>
                <value>
                    <fullName>Sol - Leadership</fullName>
                </value>
                <value>
                    <fullName>Sol - Partnerships</fullName>
                </value>
                <value>
                    <fullName>Sol - Tech</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <description>Used by snapshots to prepopulate fields.</description>
        <inlineHelpText>Used by snapshots to prepopulate fields.</inlineHelpText>
        <label>Snapshot Source Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Opportunity</fullName>
                    <default>true</default>
                    <label>Opportunity</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/objects/Opportunity_Location__c.object
<CustomObject>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Opportunity Locations</relationshipLabel>
        <relationshipName>Opportunity_Locations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Opportunity_Locations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Opportunity Location</label>
    <nameField>
        <displayFormat>OL-{00000}</displayFormat>
        <label>Opportunity Location Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/OpportunityTriggerSyncTest.cls
@isTest
public class OpportunityTriggerSyncTest {

    @isTest
    static void testOpportunityTriggerSyncFlow() {
        Opportunity o = new Opportunity(
            Name = 'Test Opportunity',
            StageName = 'Prospecting',
            CloseDate = System.today(),
            Opportunity_Owner_Division__c = 'Global Solutions',
            Opportunity_Owner_Sub_Division__c = 'Inbound Sales'
        );
        insert o;

        Country__c c = new Country__c(Name = 'United States');
        insert c;

        Location__c l = new Location__c(Name = 'Los Angeles', Country__c = c.Id);
        insert l;

        Opportunity_Location__c ol1 = new Opportunity_Location__c(Opportunity__c = o.Id, Location__c = l.Id);
        insert ol1;

        Opportunity_Location__c ol2 = new Opportunity_Location__c(Opportunity__c = o.Id, Location__c = l.Id);
        insert ol2;

        delete ol1;

        o.StageName = 'Closed Won';
        update o;
    }
}