src/objects/Country__c.object
<CustomObject>
    <description>The different countries we work in</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>What country is this opportunity taking place.</inlineHelpText>
        <label>Implementing Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <description>Used by snapshots to prepopulate fields.</description>
        <inlineHelpText>Used by snapshots to prepopulate fields.</inlineHelpText>
        <label>Snapshot Source Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Opportunity</fullName>
                    <default>true</default>
                    <label>Opportunity</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/objects/OpportunityCountry__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Opportunity Countries (Country)</relationshipLabel>
        <relationshipName>OpportunityCountries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Countries</relationshipLabel>
        <relationshipName>OpportunityCountries</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Opportunity Country</label>
    <nameField>
        <displayFormat>OC-{000000}</displayFormat>
        <label>OpportunityCountry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/OpportunityContractControllerTest.cls
/**************************************************
Class Name: OpportunityContractControllerTest
Class Description: Class for Contract creating from an Opportunity Testing and Coverage
Author: Virginia Fernández (vfernandez@adooxen.com)
Update Date: 2013-04-09
Additional Comments: 
**************************************************/
@isTest(SeeAllData=true)
private class OpportunityContractControllerTest {

    static testMethod void testNewContract() {
    	Opportunity opp = new Opportunity();
    	opp.Name = 'Test';
    	opp.StageName = 'Stage 1 - Connect';
    	opp.CloseDate = Date.newInstance(2013, 4, 9);
    	insert opp;
    	
    	Country__c country = new Country__c();
    	country.Name = 'Test';
    	insert country;
    	
    	OpportunityCountry__c oppcountry = new OpportunityCountry__c();
    	oppcountry.Country__c = country.id;
    	oppcountry.Opportunity__c = opp.id;
    	insert oppcountry;
    	
    	Product2 product = new Product2();
    	product.Name = 'Product';
    	insert product;
    	
    	Pricebook2 pb = [select id from PriceBook2 where isStandard = true limit 1];
    	
    	PricebookEntry pricebook = new PricebookEntry();
    	pricebook.Product2Id = product.id;
    	pricebook.UnitPrice = 1;
    	pricebook.Pricebook2Id = pb.Id;
    	pricebook.IsActive = true;
    	insert pricebook;
    	
    	OpportunityLineItem lineItem = new OpportunityLineItem();
    	lineItem.OpportunityId = opp.id;
    	lineItem.PricebookEntryId = pricebook.id;
    	lineItem.Quantity = 1;
    	lineItem.TotalPrice = 1;
    	insert lineItem;
    	
    	
    	ApexPages.StandardController sc = new ApexPages.standardController(opp);
    	PageReference oppPage = sc.view();
        Test.setCurrentPageReference(oppPage);
    	
        OpportunityContractController opportunityContract = new OpportunityContractController(sc);
        Test.startTest();
        
        PageReference contrPage = opportunityContract.createContract();
        
        System.debug(contrPage.getContent());
        Test.stopTest();
    }
}