src/objects/DContract__c.object
<CustomObject>
    <description>Tracks all of Dimagi&apos;s Contracts</description>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project_Billing_Rate__c.object
<CustomObject>
    <label>Project Billing Rate</label>
    <nameField>
        <label>Project Billing Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Billing Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Date__c</fullName>
        <label>Effective Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
</CustomObject>

src/objects/SFDC_Employee_Snapshot__c.object
<CustomObject>
    <fields>
        <fullName>Employee_Type__c</fullName>
        <label>Employee Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Employee</fullName>
                </value>
                <value>
                    <fullName>Contractor</fullName>
                </value>
                <value>
                    <fullName>External Contractor</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Exchange_Rate__c</fullName>
        <label>Exchange Rate (Local:USD)</label>
        <precision>18</precision>
        <required>true</required>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Per_Week_Hours__c</fullName>
        <inlineHelpText>40 Hours is full time employee</inlineHelpText>
        <label>Hours Per Week</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Salary__c</fullName>
        <label>Annual Salary (local)</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Employee Snapshot</label>
    <nameField>
        <label>Employee Snapshot Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employee Snapshots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Time_Card__c.object
<CustomObject>
    <fields>
        <fullName>Billing_Rate__c</fullName>
        <label>Billing Rate</label>
        <precision>18</precision>
        <scale>10</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client</label>
        <referenceTo>DContract__c</referenceTo>
        <relationshipLabel>Time Cards</relationshipLabel>
        <relationshipName>Time_Cards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Employee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Employee</label>
        <referenceTo>SFDC_Employee__c</referenceTo>
        <relationshipLabel>Time Cards</relationshipLabel>
        <relationshipName>Time_Cards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FTE_only__c</fullName>
        <defaultValue>false</defaultValue>
        <label>FTE only</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Time_Card_Salary__c</fullName>
        <label>Time Card Salary</label>
        <precision>18</precision>
        <scale>8</scale>
        <type>Currency</type>
    </fields>
    <label>Time Card</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Time Card Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EmployeeSnapshotTriggerHandler.cls
/**
 * Trigger handler for Employee Snapshot custom object.
 */
public class EmployeeSnapshotTriggerHandler {

    public static void handleAfterInsert(List<SFDC_Employee_Snapshot__c> newSnapshots) {
        // notice batch size must be small, currently used only by batch job and size is controlled
        List<SFDC_Employee_Snapshot__c> updatedSalary = new List<SFDC_Employee_Snapshot__c>();
        TimeCardCalculatorHelper timeCardHelper = new TimeCardCalculatorHelper();
        for (SFDC_Employee_Snapshot__c emplSnp : newSnapshots) {
            recalculateTimeCardsCost(emplSnp, timeCardHelper);
        }
    }

    public static void handleAfterUpdate(List<SFDC_Employee_Snapshot__c> updatedSnapshots, Map<Id, SFDC_Employee_Snapshot__c> oldSnapshots) {
        List<SFDC_Employee_Snapshot__c> updatedSalary = new List<SFDC_Employee_Snapshot__c>();
        TimeCardCalculatorHelper timeCardHelper = new TimeCardCalculatorHelper();
        for (SFDC_Employee_Snapshot__c emplSnp : updatedSnapshots) {
            SFDC_Employee_Snapshot__c oldSnp = oldSnapshots.get(emplSnp.Id);
            if (oldSnp.Per_Week_Hours__c != emplSnp.Per_Week_Hours__c
                    || oldSnp.Salary__c != emplSnp.Salary__c
                    || oldSnp.Exchange_Rate__c != emplSnp.Exchange_Rate__c
                    || oldSnp.Employee_Type__c != emplSnp.Employee_Type__c) {
                recalculateTimeCardsCost(emplSnp, timeCardHelper);
            }
        }
    }

    public static void recalculateTimeCardsCost(SFDC_Employee_Snapshot__c emplSnp, TimeCardCalculatorHelper timeCardHelper) { // notice batch size must be small, currently used only by batch job and size is controlled
        Date endDate = emplSnp.Snapshot_Date__c;
        Date startDate = endDate.toStartOfMonth();
        Set<Id> contractIds = new Set<Id>();
        List<Time_Card__c> timeCards = [SELECT Id, Time_Card_Salary__c, Billing_Rate__c, Uses_Contractor_Billing_Rate__c,
                                        Client__r.Project_Billing_Rate__c
                                        FROM Time_Card__c WHERE Employee__c =: emplSnp.Employee_Record__c
                                        AND Date__c >=: startDate AND Date__c <=: endDate AND FTE_Only__c != true];
        System.debug('Employee Snapshot : ' + emplSnp.Name + ' ' + emplSnp.Snapshot_Date__c + ' ' + emplSnp.Employee_Type__c);
        if (timeCards.size() > 0) {
            Decimal emplSalary = TimeCardCalculatorUtils.calculateSalaryForEmplSnapshot(emplSnp);
            for (Time_Card__c tc : timeCards) {
                tc.Time_Card_Salary__c = emplSalary;

                String billingRateName = tc.Client__r.Project_Billing_Rate__c;
                if (emplSnp.Employee_Type__c == 'Contractor') {
                    billingRateName = TimeCardTriggerController.CONTRACTOR_RATE_NAME;
                    tc.Uses_Contractor_Billing_Rate__c = true;
                } else {
                    tc.Uses_Contractor_Billing_Rate__c = false;
                }
                tc.Billing_Rate__c = timeCardHelper.getBillingRate(billingRateName, tc.Date__c);

                contractIds.add(tc.Client__c);
            }

            update timeCards;
            TimeCardCalculatorUtils.markContractsToRefresh(contractIds);
        }
    }
}