src/objects/Domain__c.object
<CustomObject>
    <description>CommCare Integration</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SF Account (Organization)</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Domain</relationshipLabel>
        <relationshipName>Domain</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Domain</relationshipLabel>
        <relationshipName>Domain</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Domain</relationshipLabel>
        <relationshipName>Domain</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Domain</label>
    <nameField>
        <label>Domain Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Domain</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Opportunity__c</fullName>
        <description>Used by snapshots to prepopulate fields.</description>
        <inlineHelpText>Used by snapshots to prepopulate fields.</inlineHelpText>
        <label>Snapshot Source Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Opportunity</fullName>
                    <default>true</default>
                    <label>Opportunity</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/classes/classes/DomainTriggerController.cls
public class DomainTriggerController {

    public static void handleBeforeUpdate(List<Domain__c> newDomains, Map<Id, Domain__c> oldMap) {
        Set<Id> opps = new Set<Id>();
        Map<Id, Id> domainToOpp = new Map<Id, Id>();
        for (Domain__c domain : newDomains) {
            Domain__c oldDomain = oldMap.get(domain.Id);
            System.debug('domain : ' + domain.Opportunity__c + ' ' + domain.Name + ' ' + oldDomain.Opportunity__c);
            if ((domain.Opportunity__c != null && oldDomain.Opportunity__c == null)
                || (domain.Opportunity__c != null && domain.Opportunity__c != oldDomain.Opportunity__c)) {
                opps.add(domain.Opportunity__c);
                domainToOpp.put(domain.Id, domain.Opportunity__c);
                System.debug('domain added');
            }
        }

        if (opps.size() > 0) {
            List<OpportunityContactRole> contactRoles = [SELECT ContactId, OpportunityId FROM OpportunityContactRole WHERE IsPrimary = true AND OpportunityId IN: opps];
            Map<Id, Id> oppToContactMap = new Map<Id, Id>();
            for (OpportunityContactRole role : contactRoles) {
                oppToContactMap.put(role.OpportunityId, role.ContactId);
            }
            Map<Id, Opportunity> oppToAccMap = new Map<Id, Opportunity>([SELECT Id, AccountId FROM Opportunity WHERE Id IN: opps]);

            for (Domain__c domain : newDomains) {
                if (!domainToOpp.containsKey(domain.Id)) {
                    continue;
                }
                Id oppId = domainToOpp.get(domain.Id);
                Id accountId = oppToAccMap.get(oppId).AccountId;
                if (oppId != null && oppToContactMap.containsKey(oppId)) {
                    domain.Primary_Contact__c = oppToContactMap.get(oppId);
                }
                if (oppId != null && accountId != null) {
                    domain.Account__c = accountId;
                }
            }
        }
    }
}