src/objects/Domain__c.object
<CustomObject>
    <description>CommCare Integration</description>
    <fields>
        <fullName>Forms_for_Period_TMP__c</fullName>
        <label>Forms for Period TMP</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Wam_TMP__c</fullName>
        <description>Field used for backed calculations, do not use it</description>
        <inlineHelpText>Field used for backed calculations, do not use it</inlineHelpText>
        <label>Wam TMP</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Domain</label>
    <nameField>
        <label>Domain Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Domain</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/HQSyncClearDomainDataBatch.cls
/**
 * Class for removing data from Domain tmp fields.
 */
public class HQSyncClearDomainDataBatch implements Database.Batchable<SObject>, Database.Stateful {

    public HQSyncClearDomainDataBatch() {
    }

    public Database.QueryLocator start(Database.BatchableContext context) {
        return Database.getQueryLocator('SELECT Id, Forms_for_Period_TMP__c, Wam_TMP__c FROM Domain__c');
    }

    public void execute(Database.BatchableContext context, List<SObject> scope) {
        for (SObject oDomain : scope) {
            Domain__c domain = (Domain__c) oDomain;
            domain.Forms_for_Period_TMP__c = 0;
            domain.Wam_TMP__c = 0;
        }
        update scope;
    }

    public void finish(Database.BatchableContext context) {
    }
}