src/objects/Domain__c.object
<CustomObject>
    <description>CommCare Integration</description>
    <fields>
        <fullName>Wam_TMP__c</fullName>
        <description>Field used for backed calculations, do not use it</description>
        <inlineHelpText>Field used for backed calculations, do not use it</inlineHelpText>
        <label>Wam TMP</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Wam__c</fullName>
        <label>Wam</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Domain</label>
    <nameField>
        <label>Domain Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Domain</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/HQSyncWamUpdate.cls
public class HQSyncWamUpdate implements HQSyncDomainFieldUpdater {

    public HQSyncWamUpdate() {
    }

    public void updateSyncField(Domain__c domain) {
        domain.Wam__c = domain.Wam_TMP__c != null ? domain.Wam_TMP__c : 0;
        domain.Wam_TMP__c = 0;
    }

    public Integer getSyncFieldValue(Domain__c domain) {
        return Integer.valueOf(domain.Wam__c);
    }

    public String getSyncFieldName() {
        return 'Wam__c';
    }
}