src/objects/Domain__c.object
<CustomObject>
    <description>CommCare Integration</description>
    <fields>
        <fullName>Forms_for_Period_TMP__c</fullName>
        <label>Forms for Period TMP</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Forms_for_Period__c</fullName>
        <label>Forms for Period</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Wam_TMP__c</fullName>
        <description>Field used for backed calculations, do not use it</description>
        <inlineHelpText>Field used for backed calculations, do not use it</inlineHelpText>
        <label>Wam TMP</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Wam__c</fullName>
        <label>Wam</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Domain</label>
    <nameField>
        <label>Domain Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Domain</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/HQ_Sync_Error__c.object
<CustomObject>
    <fields>
        <fullName>Object_Type__c</fullName>
        <label>Object Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Malt Tables</fullName>
                </value>
                <value>
                    <fullName>GIR</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>HQ Sync Error</label>
    <nameField>
        <displayFormat>a-{000000}</displayFormat>
        <label>HQ Sync Error Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HQ Sync Errors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/HQSyncUpdateDomainFieldsBatch.cls
public class HQSyncUpdateDomainFieldsBatch implements Database.Batchable<Domain__c>, Database.Stateful{

    private Boolean runDomainSnapshot;

    public HQSyncUpdateDomainFieldsBatch(Boolean runDomainSnapshot) {
        this.runDomainSnapshot = runDomainSnapshot;
    }

    public List<Domain__c> start(Database.BatchableContext BC) {
        return [SELECT Id, Name, Wam__c, Wam_TMP__c, Forms_for_Period__c, Forms_for_Period_TMP__c FROM Domain__c];
    }

    public void execute(Database.BatchableContext info, List<Domain__c> scope) {
        for (Domain__c domain : scope) {
            domain.Wam__c = domain.Wam_TMP__c != null ? domain.Wam_TMP__c : 0;
            domain.Wam_TMP__c = 0;
            domain.Forms_for_Period__c = domain.Forms_for_Period_TMP__c != null ? domain.Forms_for_Period_TMP__c : 0;
            domain.Forms_for_Period_TMP__c = 0;
        }
        update scope;
    }

    public void finish(Database.BatchableContext info) {
        List<HQ_Sync_Error__c> errors = [SELECT Id FROM HQ_Sync_Error__c WHERE Object_Type__c = 'Malt Tables' OR Object_Type__c = 'GIR'];
        if (errors.size() > 0) {
            delete errors;
        }

        if (this.runDomainSnapshot) {
            Date snpDate = Date.today().toStartOfMonth().addDays(-1);
            Database.executeBatch(new DomainSnapshotFromHistoryBatch(snpDate));
        }
    }
}