src/objects/Domain__c.object
<CustomObject>
    <description>CommCare Integration</description>
    <fields>
        <fullName>Deployment_Countries__c</fullName>
        <label>Countries</label>
        <length>15000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Deployment_description__c</fullName>
        <label>Deployment description</label>
        <length>15000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Internal_Properties__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Internal Properties</label>
        <referenceTo>Internal_Properties__c</referenceTo>
        <relationshipLabel>Domain</relationshipLabel>
        <relationshipName>Domain</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Domain</label>
    <nameField>
        <label>Domain Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Domain</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Internal_Properties__c.object
<CustomObject>
    <label>Internal Properties</label>
    <nameField>
        <displayFormat>InternalProp={000000}</displayFormat>
        <label>Internal Properties Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Internal Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>notes__c</fullName>
        <label>notes</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
</CustomObject>

src/classes/HQSyncInlineFieldController.cls
public class HQSyncInlineFieldController {

    public Domain__c domain { get; set; }

    public HQSyncInlineFieldController(ApexPages.StandardController stdController)  {
        this.domain = (Domain__c) stdController.getRecord();
        this.domain = [SELECT Id, Deployment_Countries__c, Deployment_description__c, Internal_Properties__r.notes__c FROM Domain__c WHERE Id =: domain.Id LIMIT 1];
    }
}