src/objects/Domain__c.object
<CustomObject>
    <description>CommCare Integration</description>
    <fields>
        <fullName>Deployment_Countries__c</fullName>
        <label>Countries</label>
        <length>15000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Deployment_description__c</fullName>
        <label>Deployment description</label>
        <length>15000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Internal_Properties__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Internal Properties</label>
        <referenceTo>Internal_Properties__c</referenceTo>
        <relationshipLabel>Domain</relationshipLabel>
        <relationshipName>Domain</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Domain</label>
    <nameField>
        <label>Domain Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Domain</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Internal_Properties__c.object
<CustomObject>
    <label>Internal Properties</label>
    <nameField>
        <displayFormat>InternalProp={000000}</displayFormat>
        <label>Internal Properties Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Internal Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>notes__c</fullName>
        <label>notes</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
</CustomObject>

src/classes/classes/HQSyncInlineFieldControllerTest.cls
@isTest
public class HQSyncInlineFieldControllerTest {

    @isTest
    static void testControllerInitialization() {
        Internal_Properties__c internalProps = new Internal_Properties__c(
            notes__c = 'Test notes'
        );
        insert internalProps;

        Domain__c testDomain = new Domain__c(
            Name = 'Test Domain',
            Deployment_Countries__c = 'IN, US',
            Deployment_description__c = 'Test Description',
            Internal_Properties__c = internalProps.Id
        );
        insert testDomain;

        ApexPages.StandardController stdController = new ApexPages.StandardController(testDomain);

        Test.startTest();
        HQSyncInlineFieldController controller = new HQSyncInlineFieldController(stdController);
        Test.stopTest();

        System.assertNotEquals(null, controller.domain);
        System.assertEquals(testDomain.Id, controller.domain.Id);
        System.assertEquals('IN, US', controller.domain.Deployment_Countries__c);
        System.assertEquals('Test Description', controller.domain.Deployment_description__c);
        System.assertNotEquals(null, controller.domain.Internal_Properties__r);
        System.assertEquals('Test notes', controller.domain.Internal_Properties__r.notes__c);
    }
}