src/objects/Employee_History_Archive__c.object
<CustomObject>
    <label>Employee History Archive</label>
    <nameField>
        <displayFormat>EHA-{000000}</displayFormat>
        <label>Employee History Archive Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employee History Archives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Employee_Id__c</fullName>
        <externalId>true</externalId>
        <label>Employee Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>History_Created_Date__c</fullName>
        <label>Record Created Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>History_Field_Name__c</fullName>
        <label>Field Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>History_Id__c</fullName>
        <externalId>true</externalId>
        <label>History Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>History_Is_Deleted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Deleted?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>History_New_Value__c</fullName>
        <label>New Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>History_Old_Value__c</fullName>
        <label>Old Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>History_User_Id__c</fullName>
        <externalId>true</externalId>
        <label>User Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/SFDC_Employee__c.object
<CustomObject>
    <fields>
        <fullName>Effective_Exchange_Rate_Date__c</fullName>
        <label>Effective Exchange Rate Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Effective_Salary_Date__c</fullName>
        <label>Effective Salary Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Employee_ID__c</fullName>
        <description>Emp ID for charting</description>
        <displayFormat>{0000000}</displayFormat>
        <label>Employee ID</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Exchange_Rate__c</fullName>
        <label>Exchange Rate (Local:USD)</label>
        <precision>18</precision>
        <required>true</required>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Per_Week_Hours__c</fullName>
        <inlineHelpText>40 Hours is full time employee</inlineHelpText>
        <label>Hours Per Week</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Salary__c</fullName>
        <label>Annual Salary (local)</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EmployeeArchiveTest.cls
@isTest
public class EmployeeArchiveTest {

    @isTest
    public static void shouldReturnArchivedHistory() {
        SFDC_Employee__c employeeObj = new SFDC_Employee__c(Name = 'Sample Employee', Salary__c = 50000, Exchange_Rate__c = 1, Effective_Salary_Date__c = Date.newInstance(2016, 2, 24),
                                                            Effective_Exchange_Rate_Date__c = Date.newInstance(2016, 2, 24), Per_Week_Hours__c = 40);
        insert employeeObj;
        List<Employee_History_Archive__c> archList = new List<Employee_History_Archive__c>();
        archList.add(new Employee_History_Archive__c(History_Field_Name__c = 'Created', History_Old_Value__c = null, History_New_Value__c = null,
                                                 History_Created_Date__c = DateTime.now().addHours(-2), History_User_Id__c = '', Employee_Id__c = employeeObj.Id));
        archList.add(new Employee_History_Archive__c(History_Field_Name__c = 'Salary__c', History_Old_Value__c = null, History_New_Value__c = '120000',
                                                 History_Created_Date__c = DateTime.now().addHours(-1), History_User_Id__c = '', Employee_Id__c = employeeObj.Id));
        archList.add(new Employee_History_Archive__c(History_Field_Name__c = 'Salary__c', History_Old_Value__c = '120000', History_New_Value__c = null,
                                                 History_Created_Date__c = DateTime.now(), History_User_Id__c = '', Employee_Id__c = employeeObj.Id));
        insert archList;
        ApexPages.StandardController sc = new ApexPages.standardController(employeeObj);
        PageReference emplPage = sc.view();
        Test.setCurrentPageReference(emplPage);

        EmployeeHistoryArchiveController ctrl = new EmployeeHistoryArchiveController(sc);

        Test.startTest();
        System.assertEquals(3, ctrl.getEmployeeArchivedHistory().size());
        Test.stopTest();
    }

    @isTest
    public static void employeeArchiveManagerTest() {
        SFDC_Employee__c employeeObj = new SFDC_Employee__c(Name = 'Sample Employee', Salary__c = 50000, Exchange_Rate__c = 1, Effective_Salary_Date__c = Date.newInstance(2016, 2, 24),
                                                            Effective_Exchange_Rate_Date__c = Date.newInstance(2016, 2, 24), Per_Week_Hours__c = 40);
        insert employeeObj;
        SFDC_Employee__c employeeObj2 = new SFDC_Employee__c(Name = 'Sample Employee 2', Salary__c = 50000, Exchange_Rate__c = 1, Effective_Salary_Date__c = Date.newInstance(2016, 2, 24),
                                                            Effective_Exchange_Rate_Date__c = Date.newInstance(2016, 2, 24), Per_Week_Hours__c = 40);
        insert employeeObj2;

        Test.startTest();
        EmployeeArchiveManager.archiveNewHistoryData();
        Test.stopTest();
        // We cannot mock history data in test,
        // We also can't create object because we will get field not writable exception
        // The only way to test it is creating history wrapper and mock it instead a query
        // We will test what is possible
        System.assertEquals(0, [SELECT Id FROM Employee_History_Archive__c].size());

        DateTime currentTime = DateTime.now();
        insert EmployeeArchiveManager.buildArchiveRecord(employeeObj.Id, 'Test_Field__c', employeeObj2.Id, false,
                                                         24000.99, 21000.00,  currentTime.addHours(-1), null);
        insert EmployeeArchiveManager.buildArchiveRecord(employeeObj2.Id, 'Test_Field_2__c', employeeObj.Id, false,
                                                         'SimpleName', null, currentTime.addHours(-2), null);
 
        System.assertEquals(2, [SELECT Id FROM Employee_History_Archive__c].size());
        List<Employee_History_Archive__c> records = [SELECT Employee_Id__c, History_Field_Name__c, History_Id__c, History_User_Id__c,
                                                     History_Is_Deleted__c, History_New_Value__c, History_Old_Value__c, History_Created_Date__c
                                                     FROM Employee_History_Archive__c ORDER BY History_Created_Date__c DESC];
        assertRecord(records.get(0), employeeObj.Id, 'Test_Field__c', employeeObj2.Id, null, false, '24000.99', '21000.00', currentTime.addHours(-1));
        assertRecord(records.get(1), employeeObj2.Id, 'Test_Field_2__c', employeeObj.Id, null, false, 'SimpleName', null, currentTime.addHours(-2));
    }

    private static void assertRecord(Employee_History_Archive__c record, Id expectedEmployee, String expectedField, Id expectedId,
                                     Id expectedUser, Boolean expectedIsDeleted, String expectedNew, String expectedOld,
                                     DateTime expectedDateTime) {
        System.assertEquals(expectedEmployee, record.Employee_Id__c);
        System.assertEquals(expectedField, record.History_Field_Name__c);
        System.assertEquals(expectedId, record.History_Id__c);
        System.assertEquals(expectedUser, record.History_User_Id__c);
        System.assertEquals(expectedIsDeleted, record.History_Is_Deleted__c);
        System.assertEquals(expectedNew, record.History_New_Value__c);
        System.assertEquals(expectedOld, record.History_Old_Value__c);
        System.assertEquals(expectedDateTime, record.History_Created_Date__c);
    }
}