src/objects/FogBugz_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Default_Opportunity_Owner__c</fullName>
        <description>This is the User Name (not Email) of the default SF owner for new cases created in FB, owned by users that do not exist in SF</description>
        <label>Default Opportunity Owner</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Sync_Filter__c</fullName>
        <label>Sync Filter</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sync_Script_Running__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sync Script Running</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Token__c</fullName>
        <label>Token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>FogBugz Settings</label>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Fogbugz_Assigned_To__c</fullName>
        <inlineHelpText>Who is the Fogbugz ticket assigned to currently.</inlineHelpText>
        <label>Fogbugz Assigned To</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fogbugz_elapsed_time__c</fullName>
        <label>Fogbugz elapsed time</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Fogbugz_Last_Updated_Date__c</fullName>
        <inlineHelpText>The last day the Fogbugz ticket was updated.</inlineHelpText>
        <label>Fogbugz Last Updated Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Fogbugz_Probability__c</fullName>
        <label>Probability</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Fogbugz_Ticket_Number__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>The ticket number of the corresponding Fogbugz ticket.</inlineHelpText>
        <label>Fogbugz Ticket Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Owner_Division__c</fullName>
        <description>This fields describes which division is driving the BD efforts related to this opportunity.</description>
        <inlineHelpText>This fields describes which division is driving the BD efforts related to this opportunity.</inlineHelpText>
        <label>Opportunity Owner (Division)</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Solutions</fullName>
                </value>
                <value>
                    <fullName>SaaS</fullName>
                </value>
                <value>
                    <fullName>GSO</fullName>
                </value>
                <value>
                    <fullName>GTD</fullName>
                </value>
                <value>
                    <fullName>India Division</fullName>
                </value>
                <value>
                    <fullName>USH</fullName>
                </value>
                <value>
                    <fullName>ICDS-CAS</fullName>
                    <isActive>false</isActive>
                    <label>ICDS-CAS</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity_Owner_Sub_Division__c</fullName>
        <description>This fields describes which sub-division or Practice is driving the BD efforts related to this opportunity.</description>
        <inlineHelpText>This fields describes which sub-division or Practice is driving the BD efforts related to this opportunity.</inlineHelpText>
        <label>Opportunity Owner (Sub-Division)</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>GSO - BizOps</fullName>
                </value>
                <value>
                    <fullName>GSO - BizStrat</fullName>
                </value>
                <value>
                    <fullName>GSO - CC Connect</fullName>
                </value>
                <value>
                    <fullName>GSO - Dgtl Adherence</fullName>
                </value>
                <value>
                    <fullName>GSO - Leadership</fullName>
                </value>
                <value>
                    <fullName>GSO - Marketing</fullName>
                </value>
                <value>
                    <fullName>GSO - OoCEO</fullName>
                </value>
                <value>
                    <fullName>GSO - POps</fullName>
                </value>
                <value>
                    <fullName>GSO - RAD</fullName>
                </value>
                <value>
                    <fullName>GTD - Eng Management</fullName>
                </value>
                <value>
                    <fullName>GTD - Leadership</fullName>
                </value>
                <value>
                    <fullName>GTD - QA</fullName>
                </value>
                <value>
                    <fullName>GTD - Team</fullName>
                </value>
                <value>
                    <fullName>Inbound Sales</fullName>
                </value>
                <value>
                    <fullName>India - Delivery</fullName>
                </value>
                <value>
                    <fullName>India - Leadership</fullName>
                </value>
                <value>
                    <fullName>India - Partnerships</fullName>
                </value>
                <value>
                    <fullName>India - Tech</fullName>
                </value>
                <value>
                    <fullName>SaaS - CS</fullName>
                </value>
                <value>
                    <fullName>SaaS - Management</fullName>
                </value>
                <value>
                    <fullName>SaaS - Marketing</fullName>
                </value>
                <value>
                    <fullName>SaaS - Operations</fullName>
                </value>
                <value>
                    <fullName>SaaS - Platform</fullName>
                </value>
                <value>
                    <fullName>SaaS - Product</fullName>
                </value>
                <value>
                    <fullName>SaaS - Sales</fullName>
                </value>
                <value>
                    <fullName>SaaS - Support</fullName>
                </value>
                <value>
                    <fullName>Sol - Delivery</fullName>
                </value>
                <value>
                    <fullName>Sol - Leadership</fullName>
                </value>
                <value>
                    <fullName>Sol - Partnerships</fullName>
                </value>
                <value>
                    <fullName>Sol - Tech</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/classes/classes/TestFogBugzSynchronization.cls
@isTest
public class TestFogBugzSynchronization {

    private static void setupSettings() {
        FogBugz_Settings__c settings = FogBugz_Settings__c.getOrgDefaults();
        settings.Sync_Filter__c = 1;
        settings.Token__c = 'test';
        settings.Sync_Script_Running__c = false;
        settings.Default_Opportunity_Owner__c = 'do@not.exist';
        settings.FB_URL__c = 'https://manage.dimagi.com/api.asp?';
        upsert settings;
    }

    @isTest
    public static void testOpportunityToCaseWithCaseId() {
        setupSettings();
        Test.setMock(HttpCalloutMock.class, new FogBugzHttpCalloutMock());
        Test.startTest();
        Opportunity o = new Opportunity(
            Name = 'Test name',
            StageName = 'Test stage',
            CloseDate = Date.today(),
            Fogbugz_Ticket_Number__c = 'Should not change',
            Opportunity_Owner_Division__c = 'Solutions',
            Opportunity_Owner_Sub_Division__c='Inbound Sales'
        );
        insert o;
        Test.stopTest();
        Opportunity refreshed = [SELECT Id, Fogbugz_Ticket_Number__c FROM Opportunity WHERE Id = :o.Id];
        System.assertEquals('Should not change', refreshed.Fogbugz_Ticket_Number__c, 'Opportunity already had a FogBugz id and was updated');
    }

    @isTest
    public static void testOpportunityToCaseWithoutCaseId() {
        setupSettings();
        Test.setMock(HttpCalloutMock.class, new FogBugzHttpCalloutMock());
        Test.startTest();
        Opportunity o = createTestOpportunity(null);
        Test.stopTest();

        Opportunity refreshed = [SELECT Id, Fogbugz_Ticket_Number__c FROM Opportunity WHERE Id = :o.Id];
        System.assertEquals(FogBugzHttpCalloutMock.TEST_FB_ID, refreshed.Fogbugz_Ticket_Number__c, 'FogBugz id was not updated on Opportunity');
    }

    @isTest
    public static void testFB2SFSyncExistentCase() {
        setupSettings();
        Test.setMock(HttpCalloutMock.class, new FogBugzHttpCalloutMock());
        Test.startTest();
        Opportunity o = createTestOpportunity(FogBugzHttpCalloutMock.TEST_FB_ID);
        Database.executeBatch(new FogBugzSynchronizerBatch(1, true), 1);
        Test.stopTest();

        Opportunity refreshed = [SELECT Id, Name, StageName, Fogbugz_Ticket_Number__c, Fogbugz_Assigned_To__c, Fogbugz_Last_Updated_Date__c, Amount,
                                        Probability, Fogbugz_Probability__c, Fogbugz_elapsed_time__c FROM Opportunity WHERE Id = :o.Id];

        System.assertEquals('Test area', refreshed.StageName, 'Opportunity stage not updated');
        System.assertEquals('Test assignee', refreshed.Fogbugz_Assigned_To__c, 'Assignee not updated');
        System.assertEquals('Test title', refreshed.Name, 'Name not updated');
        System.assertEquals(41.7327995300293, refreshed.Fogbugz_elapsed_time__c, 'Fogbugz_elapsed_time__c wasn\'t updated');
        System.assertEquals(Datetime.newInstanceGMT(2012, 1, 1, 0, 0, 0), refreshed.Fogbugz_Last_Updated_Date__c, 'FB last modified not updated');
    }

    @isTest
    public static void testFB2SFSyncNotExistentCase() {
        setupSettings();
        // We checked the update on the above test case, we'll just cover the batch job code
        // here as there's nothing we can test
        Test.setMock(HttpCalloutMock.class, new FogBugzHttpCalloutMock());
        Test.startTest();
        Database.executeBatch(new FogBugzSynchronizerBatch(1, true), 1);
        Test.stopTest();
    }

    @isTest
    public static void testFB2SFSyncNote() {
        setupSettings();
        Test.setMock(HttpCalloutMock.class, new FogBugzHttpCalloutMock());
        Test.startTest();
        Opportunity o = createTestOpportunity(FogBugzHttpCalloutMock.TEST_FB_ID);

        Task t = new Task(Description = 'Test',
                          Priority = 'Normal',
                          Status = 'Test',
                          WhatId = o.Id,
                          Subject = 'Email: Test subject');
        insert t;
        Test.stopTest();
    }

    public static Opportunity createTestOpportunity(String fbCaseId) {
        setupSettings();
        Opportunity o = new Opportunity(
            Name = 'Change me',
            StageName = 'Change me',
            CloseDate = Date.today(),
            Fogbugz_Assigned_To__c = 'Change me',
            Fogbugz_Ticket_Number__c = fbCaseId,
            Opportunity_Owner_Division__c = 'Solutions',
            Opportunity_Owner_Sub_Division__c='Inbound Sales'
        );
        insert o;
        return o;
    }
}