src/objects/FTE_Tag__c.object
<CustomObject>
    <fields>
        <fullName>Action__c</fullName>
        <label>Action</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Updated</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Tag Deleted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Employee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Employee</label>
        <referenceTo>SFDC_Employee__c</referenceTo>
        <relationshipLabel>FTE Tags</relationshipLabel>
        <relationshipName>FTE_Tags</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FTE_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>FTE Contract</label>
        <referenceTo>DContract__c</referenceTo>
        <relationshipLabel>FTE Tags (FTE Contract)</relationshipLabel>
        <relationshipName>FTE_Tags1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Hours__c</fullName>
        <label>Hours</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TC_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TC Contract</label>
        <referenceTo>DContract__c</referenceTo>
        <relationshipLabel>FTE Tags</relationshipLabel>
        <relationshipName>FTE_Tags</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>FTE Tag</label>
    <nameField>
        <label>FTE Tag Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FTE Tags</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Time_Card__c.object
<CustomObject>
    <fields>
        <fullName>Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client</label>
        <referenceTo>DContract__c</referenceTo>
        <relationshipLabel>Time Cards</relationshipLabel>
        <relationshipName>Time_Cards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Employee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Employee</label>
        <referenceTo>SFDC_Employee__c</referenceTo>
        <relationshipLabel>Time Cards</relationshipLabel>
        <relationshipName>Time_Cards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FTE_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>FTE Contract</label>
        <referenceTo>DContract__c</referenceTo>
        <relationshipLabel>Time Cards (FTE Contract)</relationshipLabel>
        <relationshipName>FTE_Time_Cards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FTE_hours__c</fullName>
        <label>FTE hours</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FTE_only__c</fullName>
        <defaultValue>false</defaultValue>
        <label>FTE only</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Need_recalculation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Need recalculation</label>
        <type>Checkbox</type>
    </fields>
    <label>Time Card</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Time Card Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TimeCardTriggerController.cls
/**
 * Time Card Trigger Handler class. Handles after insert, update and delete events.
 */
public with sharing class TimeCardTriggerController {

    public static void handleAfterInsert(List<Time_Card__c> newTimeCards) {
        Set<Id> contractsIds = new Set<Id>();
        for (Time_Card__c tc : newTimeCards) {
            contractsIds.add(tc.Client__c);
        }
        TimeCardCalculatorUtils.markContractsToRefresh(contractsIds);
    }

    public static void handleAfterUpdate(List<Time_Card__c> updatedTimeCards, Map<Id, Time_Card__c> beforeUpdateTimeCards) {
        if (RecursiveTriggerHelper.hasRecursiveFlag()) {
            return;
        }

        List<FTE_Tag__c> tags = new List<FTE_Tag__c>();
        List<Time_Card__c> timeCardsToUpdate = new List<Time_Card__c>();
        Set<Id> contractsIds = new Set<Id>();

        for (Time_Card__c tc : updatedTimeCards) {
            if (tc.FTE_Only__c != true) {
                Time_Card__c oldTC = beforeUpdateTimeCards.get(tc.Id);
                if (tc.Client__c != oldTC.Client__c) {
                    contractsIds.add(oldTC.Client__c);
                    contractsIds.add(tc.Client__c);
                    Time_Card__c tcToUpdate = null;

                    if (tc.FTE_Contract__c != null) {
                        tags.add(new FTE_Tag__c(Action__c = 'Tag Deleted', Date__c = tc.Date__c, Hours__c = tc.FTE_hours__c,
                                            Employee__c = tc.Employee__c, TC_Contract__c = oldTC.Client__c,
                                            FTE_Contract__c = tc.FTE_Contract__c)); // we can't move time card tags here, it's possible that we will fatch time card with updated client

                        tcToUpdate = new Time_Card__c(Id = tc.Id, FTE_Contract__c = null, FTE_hours__c = 0, Need_recalculation__c = true);
                    }

                    if (tcToUpdate == null) {
                        tcToUpdate = new Time_Card__c(Id = tc.Id, Need_recalculation__c = true);
                    }
                    timeCardsToUpdate.add(tcToUpdate);
                }
            }
        }

        if (tags.size() > 0) {
            insert tags;
        }
        if (timeCardsToUpdate.size() > 0) {
            RecursiveTriggerHelper.setRecursiveFlag();
            update timeCardsToUpdate;
        }
        TimeCardCalculatorUtils.markContractsToRefresh(contractsIds);
    }

    public static void handleAfterDelete(List<Time_Card__c> deletedTimeCards) {
        List<FTE_Tag__c> tags = new List<FTE_Tag__c>();
        Set<Id> contractsIds = new Set<Id>();
        for (Time_Card__c tc : deletedTimeCards) {
            if (tc.FTE_Only__c != true) {
                contractsIds.add(tc.Client__c);
            }
            if (tc.FTE_Contract__c != null) {
                tags.add(new FTE_Tag__c(Action__c = 'Tag Deleted', Date__c = tc.Date__c, Hours__c = tc.FTE_hours__c,
                                            Employee__c = tc.Employee__c, TC_Contract__c = tc.Client__c,
                                            FTE_Contract__c = tc.FTE_Contract__c)); // we can't move time card tags here, it's possible that we will fatch time card to remove
            }
        }

        if (tags.size() > 0) {
            insert tags;
        }
        TimeCardCalculatorUtils.markContractsToRefresh(contractsIds);
    }
}