src/objects/FTE_Tag__c.object
<CustomObject>
    <fields>
        <fullName>Action__c</fullName>
        <label>Action</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Updated</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Tag Deleted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Employee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Employee</label>
        <referenceTo>SFDC_Employee__c</referenceTo>
        <relationshipLabel>FTE Tags</relationshipLabel>
        <relationshipName>FTE_Tags</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FTE_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>FTE Contract</label>
        <referenceTo>DContract__c</referenceTo>
        <relationshipLabel>FTE Tags (FTE Contract)</relationshipLabel>
        <relationshipName>FTE_Tags1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Hours__c</fullName>
        <label>Hours</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TC_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TC Contract</label>
        <referenceTo>DContract__c</referenceTo>
        <relationshipLabel>FTE Tags</relationshipLabel>
        <relationshipName>FTE_Tags</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>FTE Tag</label>
    <nameField>
        <label>FTE Tag Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FTE Tags</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Time_Card__c.object
<CustomObject>
    <fields>
        <fullName>Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client</label>
        <referenceTo>DContract__c</referenceTo>
        <relationshipLabel>Time Cards</relationshipLabel>
        <relationshipName>Time_Cards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Employee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Employee</label>
        <referenceTo>SFDC_Employee__c</referenceTo>
        <relationshipLabel>Time Cards</relationshipLabel>
        <relationshipName>Time_Cards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FTE_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>FTE Contract</label>
        <referenceTo>DContract__c</referenceTo>
        <relationshipLabel>Time Cards (FTE Contract)</relationshipLabel>
        <relationshipName>FTE_Time_Cards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FTE_hours__c</fullName>
        <label>FTE hours</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FTE_only__c</fullName>
        <defaultValue>false</defaultValue>
        <label>FTE only</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Total__c</fullName>
        <inlineHelpText>Total Hours</inlineHelpText>
        <label>Total Hours</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Time Card</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Time Card Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FTEUpdateTagsBatch.cls
/**
 * Batch job used to add FTE Tracker tags from removed time cards.
 */
public without sharing class FTEUpdateTagsBatch implements Database.Batchable<FTE_Tag__c>, Database.Stateful {

    private List<Time_Card__c> timeCardsToUpsert;

    public FTEUpdateTagsBatch() {
        this.timeCardsToUpsert = new List<Time_Card__c>();
    }

    public List<FTE_Tag__c> start(Database.BatchableContext BC) {
        return [SELECT Id, Hours__c, Date__c, Employee__c, TC_Contract__c, FTE_Contract__c FROM FTE_Tag__c
                        WHERE Action__c = 'Tag Deleted'];
    }

    public void execute(Database.BatchableContext BC, List<FTE_Tag__c> scope) {
        // If tag was deleted it means that we need one time car without tag, if not we need add FTE_only time card
        Set<Id> timeCardsIds = new Set<Id>();
        for (FTE_Tag__c removedTag : scope) {
            List<Time_Card__c> timeCards = [SELECT Id, FTE_hours__c, FTE_Contract__c FROM Time_Card__c
                                            WHERE Employee__c =: removedTag.Employee__c AND Client__c != null
                                            AND Client__c =: removedTag.TC_Contract__c
                                            AND (FTE_Contract__c = null OR FTE_Contract__c = '')
                                            AND CALENDAR_MONTH(Date__c) =: removedTag.Date__c.month()
                                            AND CALENDAR_YEAR(Date__c) =: removedTag.Date__c.year()
                                            AND Id NOT IN: timeCardsIds LIMIT 1];
            if (timeCards.size() > 0) {
                Time_Card__c tc = timeCards.get(0);
                tc.FTE_Contract__c = removedTag.FTE_Contract__c;
                tc.FTE_hours__c = removedTag.Hours__c;
                timeCardsIds.add(tc.Id);
                timeCardsToUpsert.add(tc);
            } else {
                timeCardsToUpsert.add(new Time_Card__c(Client__c = removedTag.TC_Contract__c, Employee__c = removedTag.Employee__c,
                                                       Date__c = removedTag.Date__c, FTE_Contract__c = removedTag.FTE_Contract__c,
                                                       FTE_only__c = true, Total__c = 0, FTE_hours__c = removedTag.Hours__c));
            }
        }
    }

    public void finish(Database.BatchableContext BC) {
        if (this.timeCardsToUpsert.size() > 0) {
            upsert this.timeCardsToUpsert;
        }
        List<FTE_Tag__c> tagsToDelete = [SELECT Id FROM FTE_Tag__c WHERE Action__c = 'Tag Deleted'];
        if (tagsToDelete.size() > 0) {
            delete tagsToDelete;
        }
    }
}