src/objects/FTE_Day_Card__c.object
<CustomObject>
    <description>This object is used to store Monthly Timecard day-wise records with respect to projects.</description>
    <label>FTE Day Card</label>
    <nameField>
        <displayFormat>Day-Card-{0000}</displayFormat>
        <label>FTE Day Card Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FTE Day Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Available_Hours__c</fullName>
        <description>This field uses to store max available hours to update any day hours value.</description>
        <label>Available Hours</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>DContract__c</referenceTo>
        <relationshipLabel>FTE Day Cards</relationshipLabel>
        <relationshipName>FTE_Day_Cards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Employee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Employee</label>
        <referenceTo>SFDC_Employee__c</referenceTo>
        <relationshipLabel>FTE Day Cards</relationshipLabel>
        <relationshipName>FTE_Day_Cards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>hours__c</fullName>
        <description>This field is used to store a day working hours with respect to projects.</description>
        <label>hours</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Work_Card_Total_Hours__c</fullName>
        <label>Work Card Total Hours</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
</CustomObject>

src/objects/FTE_Work_Card__c.object
<CustomObject>
    <fields>
        <fullName>Employee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Employee</label>
        <referenceTo>SFDC_Employee__c</referenceTo>
        <relationshipLabel>FTE Work Cards</relationshipLabel>
        <relationshipName>FTE_Work_Cards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>FTE Work Card</label>
    <nameField>
        <displayFormat>Work-Card-{00000}</displayFormat>
        <label>FTE Work Card Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FTE Work Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FTEWorkCardTriggerHandler.cls
public class FTEWorkCardTriggerHandler {
    private Integer monthDays;
    
    public static void handleAfterInsert(List<FTE_Work_Card__c> workCards) {        
        List<FTE_Day_Card__c> dayCardsToBeInserted = new List<FTE_Day_Card__c>();
        for(FTE_Work_Card__c wc: workCards){
            for(Integer i=1; i<=12; i++){
                Decimal monthValue = (Decimal) wc.get('Month_'+ i + '__c');
                if(monthValue > 0) {
                    Integer year = (Integer) wc.Year__c;
                    Integer monthDays =  Date.daysInMonth(year, i);
                    Integer workingDays = getMonthWorkingDays(i, year);
                    
                    for (Integer j = 1; j <= monthDays; j++) {                        
                        if(('Saturday').equals(DateTime.newInstance(year, i, j).format('EEEE')))
                        {
                            FTE_Day_Card__c dayCardSat = new FTE_Day_Card__c(Contract__c = wc.Contract__c, Employee__c = wc.Employee__c, hours__c = 0, Available_Hours__c = 0,
                                                                             Work_Card_Total_Hours__c = monthValue, Date__c = Date.newInstance(year, i, j));
                            dayCardsToBeInserted.add(dayCardSat);
                        } else if(('Sunday').equals(DateTime.newInstance(year, i, j).format('EEEE'))) {
                            FTE_Day_Card__c dayCardSun = new FTE_Day_Card__c(Contract__c = wc.Contract__c, Employee__c = wc.Employee__c, hours__c = 0, Available_Hours__c = 0,
                                                                             Work_Card_Total_Hours__c = monthValue, Date__c = Date.newInstance(year, i, j));
                            dayCardsToBeInserted.add(dayCardSun);
                        } else {
                            FTE_Day_Card__c dayCard = new FTE_Day_Card__c(Contract__c = wc.Contract__c, Employee__c = wc.Employee__c, hours__c = (monthValue/workingDays)*8, Available_Hours__c = 0,
                                                                          Work_Card_Total_Hours__c = monthValue, Date__c = Date.newInstance(year, i, j));
                            dayCardsToBeInserted.add(dayCard);
                        }
                    }
                }
            }            
        }
        insert dayCardsToBeInserted;
        
    }
    
    public static Integer getMonthWorkingDays(Integer month, Integer year){
        Integer workingDays= 0;
        Integer monthDays =  Date.daysInMonth(year, month);
        for(Integer k=1; K<=monthDays; k++){
            
            if(('Saturday').equals(DateTime.newInstance(year, month, k).format('EEEE')))
            {
            } else if(('Sunday').equals(DateTime.newInstance(year, month, k).format('EEEE')))
            {
            } else {
                workingDays = workingDays+1;                
            }
        }
        return workingDays;
    }
}