src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Failed_Qualifying_process_at_least_once__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Failed  Qualifying process at least once</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Follow_up_calls_held__c</fullName>
        <description>Calls in addition to the exploratory call.</description>
        <inlineHelpText>Calls in addition to the exploratory call.</inlineHelpText>
        <label>Follow-up calls held</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Lead_Status_Reason__c</fullName>
        <description>This field contains the list of reasons for selecting the lead status.</description>
        <inlineHelpText>Choose a reason that helps clarify the lead status.</inlineHelpText>
        <label>Lead Status Reason</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Status</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Contacted - Sent Email #1</fullName>
                </value>
                <value>
                    <fullName>Contacted - Sent Email #2</fullName>
                </value>
                <value>
                    <fullName>Contacted - Sent Email #3</fullName>
                </value>
                <value>
                    <fullName>Working - Exploratory Call - Trying for</fullName>
                </value>
                <value>
                    <fullName>Working - Exploratory Call Scheduled</fullName>
                </value>
                <value>
                    <fullName>Working - No show reminder #1</fullName>
                </value>
                <value>
                    <fullName>Working - No show reminder #2</fullName>
                </value>
                <value>
                    <fullName>Working - No show reminder #3</fullName>
                </value>
                <value>
                    <fullName>Working - Nudge #1</fullName>
                </value>
                <value>
                    <fullName>Working - Nudge #2</fullName>
                </value>
                <value>
                    <fullName>Working - Nudge #3</fullName>
                </value>
                <value>
                    <fullName>Working - Nudge #4</fullName>
                </value>
                <value>
                    <fullName>Incorrect or invalid email address</fullName>
                </value>
                <value>
                    <fullName>Recruiting / Hiring</fullName>
                </value>
                <value>
                    <fullName>Stopped responding</fullName>
                </value>
                <value>
                    <fullName>Opportunity identified but timeline &gt; 6 months out</fullName>
                </value>
                <value>
                    <fullName>Existing client / project</fullName>
                </value>
                <value>
                    <fullName>No response</fullName>
                </value>
                <value>
                    <fullName>Email opt-out</fullName>
                </value>
                <value>
                    <fullName>Spam</fullName>
                </value>
                <value>
                    <fullName>Competitor</fullName>
                </value>
                <value>
                    <fullName>Partner program</fullName>
                </value>
                <value>
                    <fullName>No opportunity identified yet</fullName>
                </value>
                <value>
                    <fullName>Test email address</fullName>
                </value>
                <value>
                    <fullName>Speaking request / research</fullName>
                </value>
                <value>
                    <fullName>Contact information request</fullName>
                </value>
                <value>
                    <fullName>Decided to use another solution</fullName>
                </value>
                <value>
                    <fullName>Request for sponsorship</fullName>
                </value>
                <value>
                    <fullName>Invited user</fullName>
                </value>
                <value>
                    <fullName>Former Dimagier</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Lead_Qualifying_Process__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Threshold__c</fullName>
        <label>Threshold</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Lead Qualifying Process</label>
</CustomObject>

src/classes/LeadQualifyProcessTest.cls
@isTest
public class LeadQualifyProcessTest {

    public static testMethod void triggerShouldSetFailingProcessField() {
        Lead testLead1 = new Lead(FirstName = 'Tom', LastName = 'Smith', Company = 'Smith IT Company', Lead_Status_Reason__c = 'Working - Exploratory Call - Trying for',
                                  Status = 'Working - Talking', Follow_up_calls_held__c = 8);
        insert testLead1;
        Lead testLead2 = new Lead(FirstName = 'Tom 1', LastName = 'Smith 1', Company = 'Smith IT Company 1', Lead_Status_Reason__c = 'Working - Exploratory Call - Trying for',
                                  Status = 'Working - Talking', Follow_up_calls_held__c = 88);
        insert testLead2;
        Lead testLead3 = new Lead(FirstName = 'Tom 2', LastName = 'Smith 2 ', Company = 'Smith IT Company 2', Lead_Status_Reason__c = 'Working - Exploratory Call - Trying for',
                                  Status = 'Working - Talking', Follow_up_calls_held__c = 6);
        insert testLead3;

        testLead1.Company = 'New Company 1';
        testLead2.Company = 'New Company 2';
        testLead3.Company = 'New Company 3';

        List<Lead> toUpdate = new List<Lead>();
        toUpdate.add(testLead1);
        toUpdate.add(testLead2);
        toUpdate.add(testLead3);

        Test.startTest();

        update toUpdate;

        Test.stopTest();

        List<Lead> leadsFromDB = [SELECT Id, Failed_Qualifying_process_at_least_once__c FROM Lead ORDER BY CreatedDate];
        System.assertEquals(true, leadsFromDB.get(0).Failed_Qualifying_process_at_least_once__c);
        System.assertEquals(true, leadsFromDB.get(1).Failed_Qualifying_process_at_least_once__c);
        System.assertEquals(false, leadsFromDB.get(2).Failed_Qualifying_process_at_least_once__c);

    }

    public static testMethod void jobShouldSetFailingProcessField() {
        Lead testLead1 = new Lead(FirstName = 'Tom', LastName = 'Smith', Company = 'Smith IT Company', Lead_Status_Reason__c = 'Working - Exploratory Call - Trying for',
                                  Status = 'Working - Talking', Follow_up_calls_held__c = 8);
        insert testLead1;
        Lead testLead2 = new Lead(FirstName = 'Tom 1', LastName = 'Smith 1', Company = 'Smith IT Company 1', Lead_Status_Reason__c = 'Working - Exploratory Call - Trying for',
                                  Status = 'Working - Talking', Follow_up_calls_held__c = 88);
        insert testLead2;
        Lead testLead3 = new Lead(FirstName = 'Tom 2', LastName = 'Smith 2 ', Company = 'Smith IT Company 2', Lead_Status_Reason__c = 'Working - Exploratory Call - Trying for',
                                  Status = 'Working - Talking', Follow_up_calls_held__c = 6);
        insert testLead3;

        testLead1.Company = 'New Company 1';
        testLead2.Company = 'New Company 2';
        testLead3.Company = 'New Company 3';

        List<Lead> toUpdate = new List<Lead>();
        toUpdate.add(testLead1);
        toUpdate.add(testLead2);
        toUpdate.add(testLead3);

        Test.startTest();

        Database.executeBatch(new LeadQualifyProcessBatch(), 200);

        Test.stopTest();

        List<Lead> leadsFromDB = [SELECT Id, Failed_Qualifying_process_at_least_once__c FROM Lead ORDER BY CreatedDate];
        System.assertEquals(true, leadsFromDB.get(0).Failed_Qualifying_process_at_least_once__c);
        System.assertEquals(true, leadsFromDB.get(1).Failed_Qualifying_process_at_least_once__c);
        System.assertEquals(false, leadsFromDB.get(2).Failed_Qualifying_process_at_least_once__c);

    }

    public static testMethod void shouldUseSettings() {
        Lead_Qualifying_Process__c setting = Lead_Qualifying_Process__c.getOrgDefaults();
        setting.Threshold__c = 2;
        insert setting;

        Lead testLead1 = new Lead(FirstName = 'Tom', LastName = 'Smith', Company = 'Smith IT Company', Lead_Status_Reason__c = 'Working - Exploratory Call - Trying for',
                                  Status = 'Working - Talking', Follow_up_calls_held__c = 8);
        insert testLead1;
        Lead testLead2 = new Lead(FirstName = 'Tom 1', LastName = 'Smith 1', Company = 'Smith IT Company 1', Lead_Status_Reason__c = 'Working - Exploratory Call - Trying for',
                                  Status = 'Working - Talking', Follow_up_calls_held__c = 3);
        insert testLead2;
        Lead testLead3 = new Lead(FirstName = 'Tom 2', LastName = 'Smith 2 ', Company = 'Smith IT Company 2', Lead_Status_Reason__c = 'Working - Exploratory Call - Trying for',
                                  Status = 'Working - Talking', Follow_up_calls_held__c = 1);
        insert testLead3;

        testLead1.Company = 'New Company 1';
        testLead2.Company = 'New Company 2';
        testLead3.Company = 'New Company 3';

        List<Lead> toUpdate = new List<Lead>();
        toUpdate.add(testLead1);
        toUpdate.add(testLead2);
        toUpdate.add(testLead3);

        Test.startTest();

        Database.executeBatch(new LeadQualifyProcessBatch(), 200);

        Test.stopTest();

        List<Lead> leadsFromDB = [SELECT Id, Failed_Qualifying_process_at_least_once__c FROM Lead ORDER BY CreatedDate];
        System.assertEquals(true, leadsFromDB.get(0).Failed_Qualifying_process_at_least_once__c);
        System.assertEquals(true, leadsFromDB.get(1).Failed_Qualifying_process_at_least_once__c);
        System.assertEquals(false, leadsFromDB.get(2).Failed_Qualifying_process_at_least_once__c);
    }
}