src/objects/Opportunity.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Amount_Minus_Expense_Income__c</fullName>
        <description>Total Amount of Agreement minus Pass Through Amount</description>
        <formula>Amount - Expense_Income__c -  Interdivision_Expense_Income__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Total Amount of Agreement minus Pass Through Amount</inlineHelpText>
        <label>Amount Minus Expense Income</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Channel_Response__c</fullName>
        <description>What Channel is the Opportunity (Sales, B2B, Pre-Bid, Other Competitive Bid, etc.)? 
See https://confluence.dimagi.com/display/BD/BD+Channels</description>
        <inlineHelpText>What Channel is the Opportunity (Sales, B2B, Pre-Bid, Other Competitive Bid, etc.)? 
See https://confluence.dimagi.com/display/BD/BD+Channels</inlineHelpText>
        <label>Channel</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Inside Sales</fullName>
                </value>
                <value>
                    <fullName>B2B - Standard</fullName>
                </value>
                <value>
                    <fullName>B2B - Enterprise</fullName>
                </value>
                <value>
                    <fullName>Large Competitive Bid</fullName>
                </value>
                <value>
                    <fullName>Other Competitive Bid</fullName>
                </value>
                <value>
                    <fullName>NIH Prime Grant</fullName>
                </value>
                <value>
                    <fullName>CORE Funding (Gates)</fullName>
                </value>
                <value>
                    <fullName>Gates Enterprise</fullName>
                </value>
                <value>
                    <fullName>Chatbot</fullName>
                </value>
                <value>
                    <fullName>Always Exclude Reporting Only</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Country_Text__c</fullName>
        <inlineHelpText>Text field to display attached Countries for reporting. Populated automatically when you add a location.</inlineHelpText>
        <label>Country</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>What country is this opportunity taking place.</inlineHelpText>
        <label>Implementing Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Duration_months__c</fullName>
        <inlineHelpText>How long would this contract be spread over if we win?</inlineHelpText>
        <label>Duration (months)</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Expected_Buffer__c</fullName>
        <description>Percent of the Total Contract minus Expenses that will not be directly allocated via Fogbugz or Intacct data, and is expected to fund other core activities.</description>
        <inlineHelpText>Percent of the Total Contract minus Expenses that will not be directly allocated via Fogbugz or Intacct data, and is expected to fund other core activities.</inlineHelpText>
        <label>Expected Buffer (%)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Expense_Income__c</fullName>
        <description>The amount ($) of the total contract amount that will go to external expenses (travel, vendors, or Subcontracts), and are &quot;pass through&quot; from Dimagi to other parties (and therefore we shouldn&apos;t count toward Dimagi&apos;s EV).</description>
        <inlineHelpText>The amount ($) of the total contract amount that will go to external expenses (travel, vendors, or Subcontracts), and are &quot;pass through&quot; from Dimagi to other parties (and therefore we shouldn&apos;t count toward Dimagi&apos;s EV).</inlineHelpText>
        <label>External Expense Income</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Funder_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>The account that is supplying the money for the opportunity. i.e. USAID funds CARE who then pays us. USAID is the &quot;Funder Account&quot;, CARE is the &quot;Account&quot;.</inlineHelpText>
        <label>Funding Source</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities (Funding Source)</relationshipLabel>
        <relationshipName>Opportunities_Funded</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity_Owning_Entity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Which busniness unit owns this opportunity.</inlineHelpText>
        <label>Opportunity Owner (BU)</label>
        <referenceTo>Business_Unit__c</referenceTo>
        <relationshipLabel>Opportunities (Owning)</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <description>Used by snapshots to prepopulate fields.</description>
        <inlineHelpText>Used by snapshots to prepopulate fields.</inlineHelpText>
        <label>Snapshot Source Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Opportunity</fullName>
                    <default>true</default>
                    <label>Opportunity</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Text__c</fullName>
        <description>Populated by a trigger.</description>
        <inlineHelpText>Read only field for reporting on products. Add products at bottom of page.</inlineHelpText>
        <label>Products</label>
        <type>TextArea</type>
    </fields>
</CustomObject>

src/objects/Pipeline_Snapshot__c.object
<CustomObject>
    <description>Used to store historic pipeline information for pipeline reporting. Automatically populated each month.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Opportunity_Snapshots</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Amount_Minus_Expense_Income__c</fullName>
        <label>Amount Minus Expense Income</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <inlineHelpText>Amount at the time of the snapshot.

For Opportuity:  Amount = Opp Amount
For Closed Contract: Amount = Total Amount of Contract
For Outstanding Contract: Total Amount Remaining</inlineHelpText>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CloseDate__c</fullName>
        <label>Opportunity Close Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Duration_months__c</fullName>
        <inlineHelpText>The Duration at the time the snapshot was taken.

Opps: entered on opportunity manually
Contracts: End Date - Start Date</inlineHelpText>
        <label>Duration (months)</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Expected_Buffer__c</fullName>
        <label>Expected % Buffer</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Funder_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Funding Source</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Opportunity_Snapshots1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Month_Date__c</fullName>
        <inlineHelpText>The month of this snapshot.</inlineHelpText>
        <label>Month</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity_Amount_Minus_Expense_Income__c</fullName>
        <label>Opportunity Amount Minus Expense Income</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity_Amount__c</fullName>
        <label>Opportunity Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity_Duration__c</fullName>
        <inlineHelpText>The duration of the opportunity.</inlineHelpText>
        <label>Opportunity Duration</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunity_Expense_Income__c</fullName>
        <label>Opportunity Expense Income</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Opportunity_Snapshots</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Owning_Entity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Opportunity Owner (different from Execution Owner and Contract Owner)</inlineHelpText>
        <label>Owner (BU)</label>
        <referenceTo>Business_Unit__c</referenceTo>
        <relationshipLabel>Pipeline Snapshots</relationshipLabel>
        <relationshipName>Opportunity_Snapshots</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Probability__c</fullName>
        <inlineHelpText>The probability at the time the snapshot was taken.  (Contracts = 100%)</inlineHelpText>
        <label>Probability (%)</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Products__c</fullName>
        <label>Products</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RFP_Response__c</fullName>
        <label>RFP Response</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Non-RFP</fullName>
                </value>
                <value>
                    <fullName>Prime-RFP</fullName>
                </value>
                <value>
                    <fullName>Sub-RFP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Source_Type__c</fullName>
        <inlineHelpText>Did this come from a contract or an opportunity?</inlineHelpText>
        <label>Source Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Contract</fullName>
                </value>
                <value>
                    <fullName>Opportunity</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Pipeline Snapshot</label>
    <nameField>
        <label>Pipeline Snapshot Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pipeline Snapshots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Pipeline_Snapshot_EV_DIff__c.object
<CustomObject>
    <fields>
        <fullName>Month_Date__c</fullName>
        <label>Month_Date</label>
        <type>Date</type>
    </fields>
    <label>Pipeline Snapshot EV DIff</label>
    <nameField>
        <label>Pipeline Snapshot EV DIff Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pipeline Snapshot EV DIffs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/OpportunityPipelineSnapshotBatch.cls
/**
 * OpportunityPipelineSnapshotBatch for generating new Pipeline Snapshots.
 */
public class OpportunityPipelineSnapshotBatch implements Database.Batchable<Opportunity>, Database.Stateful {

    private Date runDate;

    public OpportunityPipelineSnapshotBatch() {
        this(Date.today());
    }

    public OpportunityPipelineSnapshotBatch(Date runDate) {
        this.runDate = runDate;
    }

    public List<Opportunity> start(Database.BatchableContext BC) {
        List<Pipeline_Snapshot_EV_DIff__c> evToRemove = [SELECT Id FROM Pipeline_Snapshot_EV_DIff__c WHERE Month_Date__c =: this.runDate];
        List<Pipeline_Snapshot__c> psTORemove = [SELECT Id FROM Pipeline_Snapshot__c WHERE Month_Date__c =: this.runDate AND Source_Type__c = 'Opportunity'];
        if (evToRemove.size() > 0) {
            delete evToRemove;
        }
        if (psTORemove.size() > 0) {
            delete psTORemove;
        }

        return [SELECT Id, Name, AccountId, Amount, Amount_Minus_Expense_Income__c, Country_Text__c, Duration_months__c, Expected_Buffer__c,
                    Funder_Account__c, Expense_Income__c, Opportunity_Owning_Entity__c, Probability, Product_Text__c,
                    Channel_Response__c, StageName, CloseDate, OwnerId
                    FROM Opportunity
                    WHERE StageName = 'Stage 4 - Proposal Development'
                    OR StageName = 'Stage 5 - Submitted'
                    OR StageName = 'Stage 6 - In Negotiations'
                    OR StageName = 'Cash on Hand'
                    OR StageName = 'Predicted pipeline'
                    OR StageName = 'Core run rate'];
    }

    public void execute(Database.BatchableContext BC, List<Opportunity> scope) {
        List<Pipeline_Snapshot__c> newSnapshots = new List<Pipeline_Snapshot__c>();
        for (Opportunity opp : scope) {
            Pipeline_Snapshot__c lastMonthSnapshot = getOldSnapshots(opp.Id, this.runDate);

            Pipeline_Snapshot__c newPs = new Pipeline_Snapshot__c(
                    Name = opp.Name + ' - ' + this.runDate.month() + '/' + this.runDate.year(),
                    Month_Date__c = this.runDate,
                    Opportunity__c = opp.Id,
                    Account__c = opp.AccountId,
                    Amount__c = opp.Amount,
                    Amount_Minus_Expense_Income__c = opp.Amount_Minus_Expense_Income__c,
                    Country__c = opp.Country_Text__c,
                    Duration_months__c = opp.Duration_months__c,
                    Expected_Buffer__c = opp.Expected_Buffer__c,
                    Funder_Account__c = opp.Funder_Account__c,
                    Opportunity_Amount__c = opp.Amount,
                    Opportunity_Amount_Minus_Expense_Income__c = opp.Amount_Minus_Expense_Income__c,
                    CloseDate__c = opp.CloseDate,
                    Opportunity_Duration__c = opp.Duration_months__c,
                    Opportunity_Expense_Income__c = opp.Expense_Income__c,
                    OwnerId = opp.OwnerId,
                    Owning_Entity__c = opp.Opportunity_Owning_Entity__c,
                    Probability__c = opp.Probability,
                    Products__c = opp.Product_Text__c,
                    RFP_Response__c = opp.Channel_Response__c,
                    Source_Type__c = 'Opportunity',
                    Stage__c = opp.StageName
                );

            newPs.recalculateFormulas();
            newPs.Buffer_EV_for_Period__c = (newPs.Buffer_EV__c != null ? newPs.Buffer_EV__c : 0) - (lastMonthSnapshot.Buffer_EV__c != null ? lastMonthSnapshot.Buffer_EV__c : 0);
            newSnapshots.add(newPs);
        }

        if (newSnapshots.size() > 0) {
            insert newSnapshots;
        }

        NetEVDifferenceTriggerGateway evDiffHelper = new NetEVDifferenceTriggerGateway();
        evDiffHelper.processLastMonthSnapshots(newSnapshots);
    }

    public void finish(Database.BatchableContext BC) {
        if (!Test.isRunningTest()) {
            NetEVDifferenceTriggerGateway.processPriorMonthSnapshotsWithClosedStatus(this.runDate);
            EmailHelper.sendEmail(BatchDefaultSettings__c.getOrgDefaults().Error_Emails__c.split(','), 'Opportunity Pipeline Snapshots', 'Job finished : ' + Date.today() + ' created for : ' + this.runDate);
        }
    }

    private Pipeline_Snapshot__c getOldSnapshots(Id oppId, Date monthDate) {
        List<Pipeline_Snapshot__c> oldSnapshots;
        oldSnapshots = [SELECT Id, Opportunity__c, Buffer_EV__c FROM Pipeline_Snapshot__c
                            WHERE Opportunity__c =: oppId AND Month_Date__c < :monthDate AND Month_Date__c > :monthDate.addMonths(-6)
                            AND Stage__c != 'Total' ORDER BY Month_Date__c DESC];

        if (oldSnapshots.size() > 0) {
            return oldSnapshots.get(0);
        }
        return new Pipeline_Snapshot__c();
    }
}