src/objects/Opportunity.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Opportunity_Owner_Division__c</fullName>
        <description>This fields describes which division is driving the BD efforts related to this opportunity.</description>
        <inlineHelpText>This fields describes which division is driving the BD efforts related to this opportunity.</inlineHelpText>
        <label>Opportunity Owner (Division)</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Solutions</fullName>
                </value>
                <value>
                    <fullName>SaaS</fullName>
                </value>
                <value>
                    <fullName>GSO</fullName>
                </value>
                <value>
                    <fullName>GTD</fullName>
                </value>
                <value>
                    <fullName>India Division</fullName>
                </value>
                <value>
                    <fullName>USH</fullName>
                </value>
                <value>
                    <fullName>ICDS-CAS</fullName>
                    <isActive>false</isActive>
                    <label>ICDS-CAS</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity_Owner_Sub_Division__c</fullName>
        <description>This fields describes which sub-division or Practice is driving the BD efforts related to this opportunity.</description>
        <inlineHelpText>This fields describes which sub-division or Practice is driving the BD efforts related to this opportunity.</inlineHelpText>
        <label>Opportunity Owner (Sub-Division)</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>GSO - BizOps</fullName>
                </value>
                <value>
                    <fullName>GSO - BizStrat</fullName>
                </value>
                <value>
                    <fullName>GSO - CC Connect</fullName>
                </value>
                <value>
                    <fullName>GSO - Dgtl Adherence</fullName>
                </value>
                <value>
                    <fullName>GSO - Leadership</fullName>
                </value>
                <value>
                    <fullName>GSO - Marketing</fullName>
                </value>
                <value>
                    <fullName>GSO - OoCEO</fullName>
                </value>
                <value>
                    <fullName>GSO - POps</fullName>
                </value>
                <value>
                    <fullName>GSO - RAD</fullName>
                </value>
                <value>
                    <fullName>GTD - Eng Management</fullName>
                </value>
                <value>
                    <fullName>GTD - Leadership</fullName>
                </value>
                <value>
                    <fullName>GTD - QA</fullName>
                </value>
                <value>
                    <fullName>GTD - Team</fullName>
                </value>
                <value>
                    <fullName>Inbound Sales</fullName>
                </value>
                <value>
                    <fullName>India - Delivery</fullName>
                </value>
                <value>
                    <fullName>India - Leadership</fullName>
                </value>
                <value>
                    <fullName>India - Partnerships</fullName>
                </value>
                <value>
                    <fullName>India - Tech</fullName>
                </value>
                <value>
                    <fullName>SaaS - CS</fullName>
                </value>
                <value>
                    <fullName>SaaS - Management</fullName>
                </value>
                <value>
                    <fullName>SaaS - Marketing</fullName>
                </value>
                <value>
                    <fullName>SaaS - Operations</fullName>
                </value>
                <value>
                    <fullName>SaaS - Platform</fullName>
                </value>
                <value>
                    <fullName>SaaS - Product</fullName>
                </value>
                <value>
                    <fullName>SaaS - Sales</fullName>
                </value>
                <value>
                    <fullName>SaaS - Support</fullName>
                </value>
                <value>
                    <fullName>Sol - Delivery</fullName>
                </value>
                <value>
                    <fullName>Sol - Leadership</fullName>
                </value>
                <value>
                    <fullName>Sol - Partnerships</fullName>
                </value>
                <value>
                    <fullName>Sol - Tech</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/classes/classes/OpenOpportunityFieldsUIControllerTest.cls
@IsTest
private class OpenOpportunityFieldsUIControllerTest {

    @IsTest
    static void test_setStageContainer_populatesHtml() {
        Account a = new Account(Name = 'Test Acc');
        insert a;

        Opportunity opp = new Opportunity(
            Name = 'Test Opp',
            StageName = 'Prospecting',
            CloseDate = Date.today().addDays(15),
            AccountId = a.Id,
            Opportunity_Owner_Division__c = 'Global Solutions',
            Opportunity_Owner_Sub_Division__c = 'GS - Leadership'
        );
        insert opp;

        String jsonString =
            '{"opportunities":[{' +
                '"attributes":{"type":"Opportunity"},' +
                '"Id":"' + opp.Id + '",' +
                '"Name":"' + String.escapeSingleQuotes(opp.Name) + '",' +
                '"StageName":"' + opp.StageName + '",' +
                '"CloseDate":"' + String.valueOf(opp.CloseDate) + '"' +
            '}]}';

        OpenOpportunityListData wrapper =
            (OpenOpportunityListData) JSON.deserialize(jsonString, OpenOpportunityListData.class);

        OpenOpportunityFieldsUIController controller = new OpenOpportunityFieldsUIController();
        controller.stageName = 'Prospecting';

        Test.startTest();
        controller.setStageContainer(wrapper);
        Test.stopTest();

        System.assertEquals(wrapper, controller.getStageContainer(),
            'Stage container should match the wrapper');
        System.assertNotEquals(null, controller.htmlTable,
            'HTML table should be populated');
        System.assertEquals(1, controller.getStageContainer().opportunities.size(),
            'Wrapper should contain our Opportunity');
    }
}