src/objects/Opportunity.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Fogbugz_Assigned_To__c</fullName>
        <inlineHelpText>Who is the Fogbugz ticket assigned to currently.</inlineHelpText>
        <label>Fogbugz Assigned To</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stage_Name_Updated_Date__c</fullName>
        <label>Stage Name Updated Date</label>
        <type>Date</type>
    </fields>
</CustomObject>

src/classes/OpenOpportunityUtils.cls
public with sharing class OpenOpportunityUtils {

    public static void handleBeforeInsert(Opportunity[] opportunities) {
        for (Opportunity opportunity :opportunities) {
            opportunity.Stage_Name_Updated_Date__c = Date.today();
        }
    }

    public static void handleBeforeUpdate(Opportunity[] opportunities, Map<Id, Opportunity> oldOpportunities) {
        for (Opportunity opportunity :opportunities) {
            Opportunity oldOpportunity = oldOpportunities.get(opportunity.Id);
            if (oldOpportunity.StageName != opportunity.StageName) {
                opportunity.Stage_Name_Updated_Date__c = Date.today();
                if (opportunity.Fogbugz_Assigned_To__c == 'CLOSED' && opportunity.IsClosed == false
                        && oldOpportunity.IsClosed == true) { // Opportunity was reopened
                    opportunity.Fogbugz_Assigned_To__c = 'REOPENED';
                }
            }
        }
    }
}