src/objects/Opportunity.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Opportunity_Owner_Division__c</fullName>
        <description>This fields describes which division is driving the BD efforts related to this opportunity.</description>
        <inlineHelpText>This fields describes which division is driving the BD efforts related to this opportunity.</inlineHelpText>
        <label>Opportunity Owner (Division)</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Solutions</fullName>
                </value>
                <value>
                    <fullName>SaaS</fullName>
                </value>
                <value>
                    <fullName>GSO</fullName>
                </value>
                <value>
                    <fullName>GTD</fullName>
                </value>
                <value>
                    <fullName>India Division</fullName>
                </value>
                <value>
                    <fullName>USH</fullName>
                </value>
                <value>
                    <fullName>ICDS-CAS</fullName>
                    <isActive>false</isActive>
                    <label>ICDS-CAS</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity_Owner_Sub_Division__c</fullName>
        <description>This fields describes which sub-division or Practice is driving the BD efforts related to this opportunity.</description>
        <inlineHelpText>This fields describes which sub-division or Practice is driving the BD efforts related to this opportunity.</inlineHelpText>
        <label>Opportunity Owner (Sub-Division)</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>GSO - BizOps</fullName>
                </value>
                <value>
                    <fullName>GSO - BizStrat</fullName>
                </value>
                <value>
                    <fullName>GSO - CC Connect</fullName>
                </value>
                <value>
                    <fullName>GSO - Dgtl Adherence</fullName>
                </value>
                <value>
                    <fullName>GSO - Leadership</fullName>
                </value>
                <value>
                    <fullName>GSO - Marketing</fullName>
                </value>
                <value>
                    <fullName>GSO - OoCEO</fullName>
                </value>
                <value>
                    <fullName>GSO - POps</fullName>
                </value>
                <value>
                    <fullName>GSO - RAD</fullName>
                </value>
                <value>
                    <fullName>GTD - Eng Management</fullName>
                </value>
                <value>
                    <fullName>GTD - Leadership</fullName>
                </value>
                <value>
                    <fullName>GTD - QA</fullName>
                </value>
                <value>
                    <fullName>GTD - Team</fullName>
                </value>
                <value>
                    <fullName>Inbound Sales</fullName>
                </value>
                <value>
                    <fullName>India - Delivery</fullName>
                </value>
                <value>
                    <fullName>India - Leadership</fullName>
                </value>
                <value>
                    <fullName>India - Partnerships</fullName>
                </value>
                <value>
                    <fullName>India - Tech</fullName>
                </value>
                <value>
                    <fullName>SaaS - CS</fullName>
                </value>
                <value>
                    <fullName>SaaS - Management</fullName>
                </value>
                <value>
                    <fullName>SaaS - Marketing</fullName>
                </value>
                <value>
                    <fullName>SaaS - Operations</fullName>
                </value>
                <value>
                    <fullName>SaaS - Platform</fullName>
                </value>
                <value>
                    <fullName>SaaS - Product</fullName>
                </value>
                <value>
                    <fullName>SaaS - Sales</fullName>
                </value>
                <value>
                    <fullName>SaaS - Support</fullName>
                </value>
                <value>
                    <fullName>Sol - Delivery</fullName>
                </value>
                <value>
                    <fullName>Sol - Leadership</fullName>
                </value>
                <value>
                    <fullName>Sol - Partnerships</fullName>
                </value>
                <value>
                    <fullName>Sol - Tech</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/classes/TaskTriggerTest.cls
@isTest
public class TaskTriggerTest {

    @isTest
    static void testbatch() {
        Account theAccount = new Account(
            Name ='Test Account'
        );
        insert theAccount;

        Contact theContact = new Contact(
            LastName = 'Test Contact 1',
            AccountId = theAccount.Id
        );
        insert theContact;

        Opportunity theOpp1 = new Opportunity(
            Name = 'Test Opp',
            CloseDate = date.today()+ 1,
            StageName = 'Stage 2 - Talking',
            Opportunity_Owner_Division__c = 'Solutions',
            Opportunity_Owner_Sub_Division__c='Inbound Sales'
        );
        insert theOpp1;

        Opportunity theOpp2 = new Opportunity(
            Name = 'Test Opp2',
            CloseDate = date.today()+ 1,
            StageName = 'Stage 2 - Talking',
            Opportunity_Owner_Division__c = 'Solutions',
            Opportunity_Owner_Sub_Division__c='Inbound Sales'
        );
        insert theOpp2;

        OpportunityContactRole contactRole1 = new OpportunityContactRole(
            OpportunityId = theOpp1.id,
            ContactId = theContact.Id
        );
        insert contactRole1;

        OpportunityContactRole contactRole2 = new OpportunityContactRole(
            OpportunityId = theOpp2.id,
            ContactId = theContact.Id
        );
        insert contactRole2;

        Task theTask = new Task(
            Subject = 'Call',
            WhoId = theContact.Id,
            Status = 'Not Started',
            Priority = 'Normal'
        );
        insert theTask;

        List<Task> taskList = [SELECT Id FROM Task WHERE WhatId =: theOpp2.Id];
        System.assertNotEquals(taskList, null);
    }
}