src/objects/Opportunity.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Opportunity__c</fullName>
        <description>Used by snapshots to prepopulate fields.</description>
        <inlineHelpText>Used by snapshots to prepopulate fields.</inlineHelpText>
        <label>Snapshot Source Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Opportunity</fullName>
                    <default>true</default>
                    <label>Opportunity</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/objects/Pipeline_Snapshot__c.object
<CustomObject>
    <description>Used to store historic pipeline information for pipeline reporting. Automatically populated each month.</description>
    <fields>
        <fullName>Expected_Value_Minus_Expense__c</fullName>
        <formula>Amount_Minus_Expense_Income__c * Probability__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Expected Value Minus Expense</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Month_Date__c</fullName>
        <inlineHelpText>The month of this snapshot.</inlineHelpText>
        <label>Month</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity_Amount_Minus_Expense_Income__c</fullName>
        <label>Opportunity Amount Minus Expense Income</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity_Name__c</fullName>
        <formula>Opportunity__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opportunity_Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Opportunity_Snapshots</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>X12_Month_Cash_Minus_Expense_Income_EV__c</fullName>
        <formula>if(ispickval(Source_Type__c,&apos;Opportunity&apos;), 
IF( (MONTH(CloseDate__c ) + 12*YEAR(CloseDate__c)) &gt; (Month( Month_Date__c ) + 12*YEAR( Month_Date__c ) + 12) 
|| (BLANKVALUE(Duration_months__c,0) = 0) 
|| (CloseDate__c &lt; Month_Date__c), 
0, 
if( (12*YEAR(Month_Date__c)+ MONTH(Month_Date__c) + 12) &gt; (12*YEAR(CloseDate__c)+MONTH(CloseDate__c)+Duration_months__c),  Expected_Value_Minus_Expense__c , 
( Expected_Value_Minus_Expense__c  / Duration_months__c) * (MONTH( Month_Date__c) + 12*YEAR( Month_Date__c ) + 12 - MONTH(CloseDate__c) - 12*YEAR(CloseDate__c)))), 


if( (month(Contract_End_Date__c)+12*year(Contract_End_Date__c)) &lt; (month(Month_Date__c)+12*Year(Month_Date__c) + 13), 
 Amount_Minus_Expense_Income__c , 
(12 *  Amount_Minus_Expense_Income__c ) / 
( 
(month(Contract_End_Date__c) + 12*year(Contract_End_Date__c)) - (month(Month_Date__c) + 12*year(Month_Date__c)))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>12 Month Cash Minus Expense Income (EV)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>X18_Month_Cash_Minus_Expenses_Income_EV__c</fullName>
        <formula>if(ispickval(Source_Type__c,&apos;Opportunity&apos;), 
IF( (MONTH(CloseDate__c ) + 12*YEAR(CloseDate__c)) &gt; (Month( Month_Date__c ) + 12*YEAR( Month_Date__c ) + 18) 
|| (BLANKVALUE(Duration_months__c,0) = 0) 
|| (CloseDate__c &lt; Month_Date__c), 
0, 
if( (12*YEAR(Month_Date__c)+ MONTH(Month_Date__c) + 18) &gt; (12*YEAR(CloseDate__c)+MONTH(CloseDate__c)+Duration_months__c), 
Expected_Value_Minus_Expense__c , 
( Expected_Value_Minus_Expense__c / Duration_months__c) * (MONTH( Month_Date__c) + 12*YEAR( Month_Date__c ) + 18 - MONTH(CloseDate__c) - 12*YEAR(CloseDate__c)))), 


if( (month(Contract_End_Date__c)+12*year(Contract_End_Date__c)) &lt; (month(Month_Date__c)+12*Year(Month_Date__c) + 19), 
Amount_Minus_Expense_Income__c , 
(18 * Amount_Minus_Expense_Income__c ) / 
( 
(month(Contract_End_Date__c) + 12*year(Contract_End_Date__c)) - (month(Month_Date__c) + 12*year(Month_Date__c)))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>18 Month Cash Minus Expenses Income (EV)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>X24_Month_Cash_Minus_Expense_Income_EV__c</fullName>
        <formula>if(ispickval(Source_Type__c,&apos;Opportunity&apos;), 
IF( (MONTH(CloseDate__c ) + 12*YEAR(CloseDate__c)) &gt; (Month( Month_Date__c ) + 12*YEAR( Month_Date__c ) + 24) 
|| (BLANKVALUE(Duration_months__c,0) = 0) 
|| (CloseDate__c &lt; Month_Date__c), 
0, 
if( (12*YEAR(Month_Date__c)+ MONTH(Month_Date__c) + 24) &gt; (12*YEAR(CloseDate__c)+MONTH(CloseDate__c)+Duration_months__c), 
Expected_Value_Minus_Expense__c , 
( Expected_Value_Minus_Expense__c / Duration_months__c) * (MONTH( Month_Date__c) + 12*YEAR( Month_Date__c ) + 24 - MONTH(CloseDate__c) - 12*YEAR(CloseDate__c)))), 


if( (month(Contract_End_Date__c)+12*year(Contract_End_Date__c)) &lt; (month(Month_Date__c)+12*Year(Month_Date__c) + 25), 
Amount_Minus_Expense_Income__c , 
(24 * Amount_Minus_Expense_Income__c ) / 
( 
(month(Contract_End_Date__c) + 12*year(Contract_End_Date__c)) - (month(Month_Date__c) + 12*year(Month_Date__c)))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>24 Month Cash Minus Expense Income (EV)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Pipeline Snapshot</label>
    <nameField>
        <label>Pipeline Snapshot Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pipeline Snapshots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Pipeline_Snapshot_EV_DIff__c.object
<CustomObject>
    <fields>
        <fullName>DIFF_12_Month_Cash_Minus_Expense_Income__c</fullName>
        <description>EV DIFF - 12 Month Cash Minus Expense Income (EV)</description>
        <label>DIFF-12 Month Cash Minus Expense Income</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>DIFF_18_Month_Cash_Minus_Expenses_Income__c</fullName>
        <description>EV DIFF - 18 Month Cash Minus Expenses Income (EV)</description>
        <label>DIFF-18 Month Cash Minus Expenses Income</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>DIFF_24_Month_Cash_Minus_Expense_Income__c</fullName>
        <description>EV DIFF - 24 Month Cash Minus Expense Income (EV)</description>
        <label>DIFF-24 Month Cash Minus Expense Income</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>DIFF_Amount_Minus_Expense_Income__c</fullName>
        <description>EV DIFF - Opportunity Amount Minus Expense Income</description>
        <label>DIFF-Amount Minus Expense Income</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>DIFF_Expected_Value_Minus_Expense__c</fullName>
        <description>EV DIFF - Expected Value Minus Expense</description>
        <label>DIFF-Expected Value Minus Expense</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Delta_Type__c</fullName>
        <label>Delta Type</label>
        <picklist>
            <picklistValues>
                <fullName>No Change</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Opp EV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Increased EV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Decreased EV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed Opp - Lost / No Go</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed Opp - Won</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Month_Date__c</fullName>
        <label>Month_Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity_Name__c</fullName>
        <label>Opportunity_Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Pipeline Snapshot EV DIff</label>
    <nameField>
        <label>Pipeline Snapshot EV DIff Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pipeline Snapshot EV DIffs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BatchCalculateEVDiff.cls
global class BatchCalculateEVDiff implements Database.Batchable<sObject>
{
	global final String Query;
    private Map<Id, Pipeline_Snapshot__c> lastMonthSnapshotRecords;
    private Map<Id, Pipeline_Snapshot__c> priorToLastMothSnapshotRecords;
    private Map<Id, Pipeline_Snapshot__c> oldSnapshotRecords;
    private Date currentDate;
    private List<Pipeline_Snapshot_EV_DIff__c> snapShotDiffs;

    global BatchCalculateEVDiff (String q)
    {
    	Query=q;
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC)
    {
        return Database.getQueryLocator(query);
    }
    
   	global void execute(Database.BatchableContext BC, List<sObject> scope)
    {
        
        if(!NetEVDifferenceTriggerGateway.getInstance().IfCUrrentMonthRecordExists())
        {
            LoadCachedData(scope);
            for(Sobject s : scope)
            {
                ProcessRecord(s);
            }
            
            if(snapShotDiffs != null && snapShotDiffs.size() > 0)
            {
                try
                {
                    insert snapShotDiffs;
                    system.debug(snapShotDiffs);
                }
                catch(DmlException ex)
                {
                    System.debug('An unexpected error has occurred while inserting in snapshot difference table: ' + ex.getMessage());
                } 
            }  
        }
    }
    
    global void finish(Database.BatchableContext BC)
    {
    }
    
    private void LoadCachedData(List<Pipeline_Snapshot__c> snapShots)
    {
        currentDate = NetEVDifferenceTriggerGateway.getInstance().getCurrentDate(snapShots);  
        if(currentDate != null)
        {
            lastMonthSnapshotRecords = NetEVDifferenceTriggerGateway.getInstance().getLastMonthSnapShotRecords(currentDate);
            priorToLastMothSnapshotRecords = NetEVDifferenceTriggerGateway.getInstance().getPriorToLastMonthSnapShotRecords(currentDate);
            oldSnapshotRecords = NetEVDifferenceTriggerGateway.getInstance().getOldSnapShotRecords(currentDate);
            snapShotDiffs = new List<Pipeline_Snapshot_EV_DIff__c>();   
        }
    }
    
    private void ProcessRecord(SObject so)
	{
        system.debug('Entered after Insert Method');
        Pipeline_Snapshot__c newSnapShotObj = (Pipeline_Snapshot__c)so;
        system.debug('lastmonthsnapshotrecords --> ');
        system.debug(lastMonthSnapshotRecords);
        Pipeline_Snapshot__c lastMonthSnapShotObj = lastMonthSnapshotRecords.get(newSnapShotObj.Opportunity__c);
        system.debug('LAST MONTH SNAPSHOT RECORDS -->');
        system.debug(lastMonthSnapshotRecords);
        system.debug('NEW SNAPHOT OBJ OPP -->');
        system.debug(newSnapShotObj.Opportunity__c);
        system.debug(lastMonthSnapShotObj);
        
        Pipeline_Snapshot_EV_DIff__c snapShotsDiff = new Pipeline_Snapshot_EV_DIff__c();
        snapShotsDiff.Name = newSnapShotObj.Name;
        snapShotsDiff.Opportunity_Name__c = newSnapShotObj.Opportunity__r.Name;
        snapShotsDiff.Month_Date__c = newSnapShotObj.Month_Date__c;
        
        if(lastMonthSnapShotObj != null)
        {
            system.debug('LAST MONTH SNAP SHOT OBJ IS NOT NULL');
            snapShotsDiff.DIFF_12_Month_Cash_Minus_Expense_Income__c = (newSnapShotObj.X12_Month_Cash_Minus_Expense_Income_EV__c != null ? newSnapShotObj.X12_Month_Cash_Minus_Expense_Income_EV__c : 0) - (lastMonthSnapShotObj.X12_Month_Cash_Minus_Expense_Income_EV__c != null ? lastMonthSnapShotObj.X12_Month_Cash_Minus_Expense_Income_EV__c : 0);
            snapShotsDiff.DIFF_18_Month_Cash_Minus_Expenses_Income__c = (newSnapShotObj.X18_Month_Cash_Minus_Expenses_Income_EV__c != null ? newSnapShotObj.X18_Month_Cash_Minus_Expenses_Income_EV__c : 0) - (lastMonthSnapShotObj.X18_Month_Cash_Minus_Expenses_Income_EV__c != null ? lastMonthSnapShotObj.X18_Month_Cash_Minus_Expenses_Income_EV__c : 0);
            snapShotsDiff.DIFF_24_Month_Cash_Minus_Expense_Income__c = (newSnapShotObj.X24_Month_Cash_Minus_Expense_Income_EV__c != null ? newSnapShotObj.X24_Month_Cash_Minus_Expense_Income_EV__c : 0) - (lastMonthSnapShotObj.X24_Month_Cash_Minus_Expense_Income_EV__c != null ? lastMonthSnapShotObj.X24_Month_Cash_Minus_Expense_Income_EV__c : 0);
            snapShotsDiff.DIFF_Amount_Minus_Expense_Income__c = (newSnapShotObj.Opportunity_Amount_Minus_Expense_Income__c != null ? newSnapShotObj.Opportunity_Amount_Minus_Expense_Income__c : 0) - (lastMonthSnapShotObj.Opportunity_Amount_Minus_Expense_Income__c != null ? lastMonthSnapShotObj.Opportunity_Amount_Minus_Expense_Income__c : 0);
            snapShotsDiff.DIFF_Expected_Value_Minus_Expense__c = (newSnapShotObj.Expected_Value_Minus_Expense__c != null ? newSnapShotObj.Expected_Value_Minus_Expense__c : 0) - (lastMonthSnapShotObj.Expected_Value_Minus_Expense__c != null ? lastMonthSnapShotObj.Expected_Value_Minus_Expense__c : 0);
            
            if(snapShotsDiff.DIFF_Amount_Minus_Expense_Income__c > 0)
            {
                snapShotsDiff.Delta_Type__c = 'Increased EV';
            }
            else if(snapShotsDiff.DIFF_Amount_Minus_Expense_Income__c < 0)
            {
                snapShotsDiff.Delta_Type__c = 'Decreased EV';                
            }
            else
            {
                snapShotsDiff.Delta_Type__c = '	No Change';
            }
            
            Pipeline_Snapshot__c oldSnapShotObj = oldSnapshotRecords.get(newSnapShotObj.Opportunity__c); 
            
            if(oldSnapShotObj == null)
            {
                snapShotsDiff.Delta_Type__c = 'New Opp EV';
            }
            
            snapShotDiffs.add(snapShotsDiff);
            
        }
        else
        {
            Pipeline_Snapshot__c priorToLastMonthSnapShotObj = priorToLastMothSnapshotRecords.get(newSnapShotObj.Opportunity__c); 
            system.debug('PRIOR TO LAST MONTH SNAPSHOT RECORDS -->');
            system.debug(priorToLastMothSnapshotRecords);
            system.debug('NEW SNAPHOT OBJ OPP -->');
            system.debug(newSnapShotObj.Opportunity__c);
            if(priorToLastMonthSnapShotObj != null)
            {            
                system.debug('PRIOR TO LAST MONTH SNAP SHOT OBJ IS NOT NULL');
                snapShotsDiff.DIFF_12_Month_Cash_Minus_Expense_Income__c = 0;
                snapShotsDiff.DIFF_18_Month_Cash_Minus_Expenses_Income__c = 0;
                snapShotsDiff.DIFF_24_Month_Cash_Minus_Expense_Income__c = 0;
                snapShotsDiff.DIFF_Amount_Minus_Expense_Income__c = 0;
                snapShotsDiff.DIFF_Expected_Value_Minus_Expense__c = 0;

                if(priorToLastMonthSnapShotObj.Opportunity__r.StageName == 'Closed - Lost' || priorToLastMonthSnapShotObj.Opportunity__r.StageName == 'Closed - No Go')
                {
                    snapShotsDiff.Delta_Type__c = 'Closed Opp - Lost / No Go'; 
                }
                else if(priorToLastMonthSnapShotObj.Opportunity__r.StageName == 'Closed - Won')
                {
                    snapShotsDiff.Delta_Type__c = 'Closed Opp - Won'; 
                }
                
                snapShotDiffs.add(snapShotsDiff);
            }
        }

        system.debug('SNAP SHOT DIFFERENCE before insert--- > ');
        system.debug(snapShotDiffs);
	}
    
}