src/objects/Opportunity.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Opportunity__c</fullName>
        <description>Used by snapshots to prepopulate fields.</description>
        <inlineHelpText>Used by snapshots to prepopulate fields.</inlineHelpText>
        <label>Snapshot Source Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Opportunity</fullName>
                    <default>true</default>
                    <label>Opportunity</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/objects/Pipeline_Snapshot__c.object
<CustomObject>
    <description>Used to store historic pipeline information for pipeline reporting. Automatically populated each month.</description>
    <fields>
        <fullName>Month_Date__c</fullName>
        <inlineHelpText>The month of this snapshot.</inlineHelpText>
        <label>Month</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Opportunity_Snapshots</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Source_Type__c</fullName>
        <inlineHelpText>Did this come from a contract or an opportunity?</inlineHelpText>
        <label>Source Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Contract</fullName>
                </value>
                <value>
                    <fullName>Opportunity</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Stage 1 - Connect</fullName>
                    <color>#0B6FCE</color>
                </value>
                <value>
                    <fullName>Stage 2 - Talking</fullName>
                    <color>#78C953</color>
                </value>
                <value>
                    <fullName>Stage 3 - Prospect</fullName>
                    <color>#E27001</color>
                </value>
                <value>
                    <fullName>Stage 4 - Proposal Development</fullName>
                    <color>#DDDDDD</color>
                </value>
                <value>
                    <fullName>Stage 5 - Submitted</fullName>
                    <color>#BBBBBB</color>
                </value>
                <value>
                    <fullName>Stage 6 - In Negotiations</fullName>
                    <color>#999999</color>
                </value>
                <value>
                    <fullName>Closed</fullName>
                    <color>#A845DC</color>
                </value>
                <value>
                    <fullName>Outstanding Contracted</fullName>
                    <color>#F3D904</color>
                </value>
                <value>
                    <fullName>Total</fullName>
                    <color>#A53711</color>
                </value>
                <value>
                    <fullName>Cash on Hand</fullName>
                    <color>#009900</color>
                </value>
                <value>
                    <fullName>Predicted pipeline</fullName>
                    <color>#0B6FCE</color>
                </value>
                <value>
                    <fullName>Core run rate</fullName>
                    <color>#FF0000</color>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Submitted_this_month__c</fullName>
        <label>Submitted this month</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Pipeline Snapshot</label>
    <nameField>
        <label>Pipeline Snapshot Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pipeline Snapshots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ScriptBatchJob.cls
/**
 * This is editable class, should be used to do data migration. For example filling new fields with relation.
 */
public class ScriptBatchJob implements Database.Batchable<SObject>, Database.AllowsCallouts, Database.Stateful {

    private Date helperDate;

    public ScriptBatchJob() {
        this.helperDate = Date.today();
    }

    public ScriptBatchJob(Date helperDate) {
        this.helperDate = helperDate;
    }

    public Database.QueryLocator start(Database.BatchableContext context) {
        return Database.getQueryLocator('SELECT Id, Stage__c, Month_Date__c, Opportunity__c, Submitted_this_month__c FROM Pipeline_Snapshot__c WHERE Source_Type__c = \'Opportunity\' AND Month_Date__c =: helperDate');
    }

    public void execute(Database.BatchableContext context, List<SObject> scope) {
        List<Pipeline_Snapshot__c> toUpdate = new List<Pipeline_Snapshot__c>();
        for (SObject objRec : scope) {
            Pipeline_Snapshot__c ps = (Pipeline_Snapshot__c) objRec;
            ps.Submitted_this_month__c = OpportunityPipelineSnapshotBatch.isSubmittedThisMonth(ps);
            toUpdate.add(ps);
        }

        if (toUpdate.size() > 0) {
            update toUpdate;
        }
    }

    public void finish(Database.BatchableContext context) {

    }
}