src/objects/SFDC_Employee__c.object
<CustomObject>
    <fields>
        <fullName>Email_Address__c</fullName>
        <label>Dimagi Email Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Employee_Status__c</fullName>
        <label>Employee Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LOA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Terminated</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Employee_Type__c</fullName>
        <label>Employee Type</label>
        <picklist>
            <picklistValues>
                <fullName>Employee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contractor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>External Contractor</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Exchange_Rate__c</fullName>
        <label>Exchange Rate (Local:USD)</label>
        <precision>18</precision>
        <required>true</required>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Hire_Date__c</fullName>
        <label>Hire Date</label>
        <type>Date</type>
    </fields>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SFDC_Employee_Snapshot__c.object
<CustomObject>
    <fields>
        <fullName>Email_Address__c</fullName>
        <label>Dimagi Email Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Employee_Status__c</fullName>
        <label>Employee Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>LOA</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Employee_Type__c</fullName>
        <label>Employee Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Employee</fullName>
                </value>
                <value>
                    <fullName>Contractor</fullName>
                </value>
                <value>
                    <fullName>External Contractor</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Exchange_Rate__c</fullName>
        <label>Exchange Rate (Local:USD)</label>
        <precision>18</precision>
        <required>true</required>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Hire_Date__c</fullName>
        <label>Hire Date</label>
        <type>Date</type>
    </fields>
    <label>Employee Snapshot</label>
    <nameField>
        <label>Employee Snapshot Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employee Snapshots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EmployeeSnapshotTest.cls
@isTest
public class EmployeeSnapshotTest {

    @testSetup
    public static void addTestData() {
        insert new SFDC_Employee__c(Name = 'Empl One', Email_Address__c = '1test-email-adress@test-email.com', Hire_Date__c = Date.today(), Employee_Type__c = 'Contractor', Exchange_Rate__c = 2, Employee_Status__c = 'Active');
        insert new SFDC_Employee__c(Name = 'Employee Two', Email_Address__c = '2test-email-adress@test-email.com', Hire_Date__c = Date.today().addDays(-40), Employee_Type__c = 'Employee', Exchange_Rate__c = 1, Employee_Status__c = 'Active');
    }

    @isTest
    public static void shouldCreateEmployeeSnapshots() {
        Test.startTest();
        Database.executeBatch(new EmployeeSnapshotBatch());
        Test.stopTest();

        System.assertEquals(2, [SELECT Id FROM SFDC_Employee_Snapshot__c].size());
        SFDC_Employee_Snapshot__c snp1 = [SELECT Email_Address__c, Hire_Date__c, Employee_Type__c, Exchange_Rate__c, Employee_Status__c FROM SFDC_Employee_Snapshot__c WHERE Name = 'Empl One'];
        System.assertEquals('1test-email-adress@test-email.com', snp1.Email_Address__c);
        System.assertEquals(Date.today(), snp1.Hire_Date__c);
        System.assertEquals('Contractor', snp1.Employee_Type__c);
        System.assertEquals(2, snp1.Exchange_Rate__c);
        System.assertEquals('Active', snp1.Employee_Status__c);

        SFDC_Employee_Snapshot__c snp2 = [SELECT Email_Address__c, Hire_Date__c, Employee_Type__c, Exchange_Rate__c, Employee_Status__c FROM SFDC_Employee_Snapshot__c WHERE Name = 'Employee Two'];
        System.assertEquals('2test-email-adress@test-email.com', snp2.Email_Address__c);
        System.assertEquals(Date.today().addDays(-40), snp2.Hire_Date__c);
        System.assertEquals('Employee', snp2.Employee_Type__c);
        System.assertEquals(1, snp2.Exchange_Rate__c);
        System.assertEquals('Active', snp2.Employee_Status__c);
    }
}